### ISSUE TITLE
CGAL does not add -frounding-math on gcc >= 5.0

### ISSUE THREAD

**Issue by bo0ts** [CGAL/cgal#104]
In `Installation/CMakeLists.txt` we set-up the flag `-frounding-math` when `"${GCC_VERSION}" MATCHES "^4."`. This regex does not match `gcc >= 5.0`.

AFAIK nothing changed in the new gcc releases with respect to that flag, but I might be wrong.

Is this the intended behavior or a bug? If it is the intended behavior, the message `Using gcc version 4 or later` should be changed.

**Comment by lrineau** [comment]
That is a bug. We are as bad as:

    if windowsVersion.StartsWith("Windows 9")

What could be a good robust test to check for 4.0 or later? The following can be good for a while:

    "${GCC_VERSION}" MATCHES "^[4-9]."

Anyway already officially no longer support gcc<4.0. And the unofficial support (needed until now by an important customer of GeometryFactory) will soon be dropped (because the customer will have finished to upgrade the machine fleet all over the world to RHEL5).

**Comment by lrineau** [comment]
Once that bug is fixed in `master` and `releases/CGAL-4.6-branch`, I will publish CGAL-4.6.1. I think it is time to.
