### ISSUE TITLE
assertion firing due to degenerate triangles

### ISSUE THREAD

**Issue by jamesd-twice** [CGAL/cgal#107]
Ran into the following while running all_intersections() on an AABB tree with an arbitrary Segment, repeatably: 

    CGAL error: assertion violation!
    Expression :
    File       : /opt/local/include/CGAL/internal/Intersections_3/Triangle_3_Segment_3_intersection.h
    Line       : 389
    Explanation:
    Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
    libc++abi.dylib: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
    File: /opt/local/include/CGAL/internal/Intersections_3/Triangle_3_Segment_3_intersection.h
    Line: 389
    Abort trap: 6  

The tree was loaded with Triangles from the well known Stanford Dragon PLY, read in via lib assimp.

 The following typedefs were in place:

    typedef CGAL::Simple_cartesian<CGAL::Gmpq> K;

    typedef K::Point_3 Point;
    typedef K::Ray_3 Ray;
    typedef K::Plane_3 Plane;
    typedef K::Vector_3 Vector;
    typedef K::Segment_3 Segment;
    typedef K::Triangle_3 Triangle;

    typedef std::list<Triangle>::iterator Iterator;
    typedef CGAL::AABB_triangle_primitive<K, Iterator> Primitive;
    typedef CGAL::AABB_traits<K, Primitive> AABB_triangle_traits;
    typedef CGAL::AABB_tree<AABB_triangle_traits> Tree;

    typedef boost::optional< Tree::Intersection_and_primitive_id<Segment>::Type > Segment_intersection;

After much head scratching I thought to add a check for is_degenerate on the Triangle's I was passing into the tree; there were some and removing these appears to have stopped this assert from firing.

If that's actually what was the issue, flagging because `assert` style handling should not be used as a replacement for guarding user input error / proper Error Handling (http://stackoverflow.com/questions/1854302/is-assert-evil).

Also reporting in to hit Google cache so somebody else in the future has something to find, even if you decide this was programmer error.

**Comment by lrineau** [comment]
Actually, the default error behavior of CGAL is not `assert`, but the throwing of a `CGAL::Assertion_exception`, as we can see on the error your reported: `terminating with uncaught exception of type CGAL::Assertion_exception`.

You can customize that behavior with the global functions documented in [the section "Assertions and Failure Behaviour" of the CGAL manual](http://doc.cgal.org/latest/STL_Extension/group__PkgStlExtensionAssertions.html).

The error handling in CGAL has been discussed a lot. The problem is that a full handling of errors at runtime would penalize a lot the efficiency, even for the class of data sets that would never trigger any error. That is why the decision was made to use preconditions and assertions, in CGAL, when `NDEBUG` and `CGAL_NDEBUG` are not defined, to help the user of CGAL to detect the issue, and fortify the user code, so that is can have the maximal efficiency once `NDEBUG` is defined.

After those explanation, I am willing to close the bug. Would you agree? If not, can you please clarify the title of the bug, and your position?

**Comment by jamesd-twice** [comment]
If I understand correctly, my feedback is that the naming chosen and output text is somewhat misleading; as a programmer new to CGAL I do not know about all the flags and intricacies and gotchas.  When my program is crashing and I don't know why even after some thorough time spent poking and I'm seeing the cause of crash as "assertion violation!" and a request to lookup bug-reporting instructions, my first inclination is that I've hit an assert in your code, not that things are working As Intended and that I have a data error that I should be try/catching.  I say this not to be pesky but just in case I'm not alone: you might consider opening a much lower priority bug to revisit naming/output/documentation.

As for this thread, if it is expected behavior that the presence of degenerate primitives in the AABB tree can cause exceptions to be thrown during distance queries, and that's all this is, agreed there is no bug, ok to close.

(If so, and if feasible, a request that a section be added to http://doc.cgal.org/latest/AABB_tree/, or at least a link added to whatever other relevant section of the manual/documentation, pointing out pragmatics of dealing with real world data, esp. with regards to common guards on input primitives and/or common try/catch scenarios or cases.)

**Comment by lrineau** [comment]
Bug in the documentation
---------------------------------
I agree that the documentation of AABB tree should mention that the triangles must not be degenerated. That is a bug of the documentation.

Strange behavior
----------------------
As regard, the assertion itself... there is something strange. The comment around the assertion says that it can crash only if the triangle is flat (degenerated). But at the very beginning of the function, there are two preconditions:
```
  CGAL_kernel_precondition( ! k.is_degenerate_3_object()(t) ) ;
  CGAL_kernel_precondition( ! k.is_degenerate_3_object()(s) ) ;
```
If the bug was caused by a degenerated triangle, then the preconditions should have failed!

Can you extract from your code and data set a self-contained code, and data set, that exposes the bug? I suggest you attach the two files to [Gist](https://gist.github.com/) to avoid big copy-pastes here.

**Comment by lrineau** [comment]
@jamesd-twice , do you still have the strange behavior of CGAL?

**Comment by sloriot** [comment]
See #508
