### ISSUE TITLE
Support Qt 5.7 in CGAL demos

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1149]
Qt 5.7 release candidate was published:
https://blog.qt.io/blog/2016/06/03/qt-5-7-0-release-candidate-available
Nothing was done is CGAL to support it. Our demos will break pretty on
rolling Linux distributions, like Debian testing, Fedora Rawhide...

There are two scenarios:
* Current setting (not header only): When configuring libCGAL_Qt5, we check for the version of Qt. If it is prior to 5.7 nothing changes. If it is 5.7 or latter and cmake is >=3.1 we check c++11 mode is on and if not we show an error saying to switch off WITH_CGAL_Qt5 or to switch c++11 mode on. If cmake is < 3.1 we only display a warning message.

* Header only: The same logic described above should be applied for all demos using QT. This can be done inside a macro and that macro can be called in each cmake script.

@lrineau  was suggesting to switch ON the c++11 mode but I would prefer the user to be really aware of what's going on.

**Comment by gdamiand** [comment]
In header only, we can do this test directly in the use_component macro, when we search for qt5; no need for a specific macro.

(please, could we postpone this after the integration of header only mode in order to avoid me a long work to merge branch with conflicts?)

**Comment by lrineau** [comment]
Actually there is nothing special to do. As soon your version of CMake supports the target property `INTERFACE_COMPILE_FEATURES` (it seems to be CMake>=3.3), the C++11 support is setup automatically by the CMake scripts shipped with Qt-5.7. The trick is just one line in `Qt5CoreConfigExtras.cmake`:
```cmake
set_property(TARGET Qt5::Core PROPERTY INTERFACE_COMPILE_FEATURES cxx_decltype)
```
I have impressed by the concision of the CMake command needed to trigger the support for C+11 in the compiler.

**Comment by mglisse** [comment]
https://cmake.org/cmake/help/v3.1/prop_tgt/INTERFACE_COMPILE_FEATURES.html seems to indicate that it existed in version 3.1...

**Comment by lrineau** [comment]
Right. I saw something with "if CMake<3.3" in Qt-5.7 CMake scripts. According to [releases notes of CMake-3.2][2] and [those of CMake-3.3][3], it might because the support of compile features in CMake-3.1 and CMake-3.2 was only for mainstream compilers and platforms. They have added support for compile features for more and more compilers and platforms from CMake-3.1 to CMake-3.6 (see [3.4][4], [3.5][5], and [3.6][6]).

[2]: https://cmake.org/cmake/help/v3.3/release/3.2.html
[3]: https://cmake.org/cmake/help/v3.3/release/3.3.html
[4]: https://cmake.org/cmake/help/v3.6/release/3.4.html
[5]: https://cmake.org/cmake/help/v3.6/release/3.5html
[6]: https://cmake.org/cmake/help/v3.6/release/3.6.html
