### ISSUE TITLE
Remove Mesh_3 demo

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1190]
I think that all the functionality of the demo is now available in the polyhedron demo.
@janetournois and @lrineau do you agree?
(I also have the same question for Surface_mesher demo)

**Comment by lrineau** [comment]
For the Mesh_3 demo, I do not know. I have not really used it in the past.

For the Surface_mesher demo,
  1. Is the use of `Surface_mesher` instead of `Mesh_3` a "feature"? `Surface_mesher` is not officially deprecated, and the `Surface_mesher demo is the only demo that can fully demonstrate its possibilities.
  2. And one missing feature, for sure, is the possibility to mesh several iso-values at the same time. But that feature is not really useful, in my opinion.

**Comment by janetournois** [comment]
I will check about the `Mesh_3` demo asap

**Comment by janetournois** [comment]
The `c3t3_rib_exporter_plugin` is still missing from the `Polyhedron` demo, and should be transferred from the `Mesh_3` demo.
I think it's the last thing to be done before we can delete the `Mesh_3` demo
@maxGimeno can you have a look please?

@lrineau the use of `Surface_mesher` concerns the `Surface_mesher` demo, right? not the `Mesh_3` demo?

**Comment by lrineau** [comment]
(I think we should not speak about the `Surface_mesher` in this issue. That is confusing. @janetournois: yes, Sébastien and I were talking about the Surface Mesher Demo.)

**Comment by lrineau** [comment]
The Mesh_3 demo is now removed from `master`! :-)
