### ISSUE TITLE
One cannot search anything about the BGL in the search box of the doc

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1246]
The documentation of specializations of `boost::graph_traits`, for 4.8.1, are in [the documentation page of the group `PkgBGLTraits`](http://doc.cgal.org/4.8.1/BGL/group__PkgBGLTraits.html).

<s>
## 1st, a small documentation bug

<s>There is a bug, in a description of two iterator types, for `Polyhedron_3`:

| Member | Value |
| --- | --- |
| halfedge_iterator | Polyhedron_3::Halfedge_iterator |
| face_iterator | Polyhedron_3::Face_iterator |

It cannot be true, because the value types of the iterators of the polyhedron are not descriptors but directly the pointed type.
</s> (**update:** see the dedicated bug entry #1251).
</s>
## 2nd, one cannot search anything about the BGL in the search box of the doc

In the Doxygen search box, one cannot search "graph_traits", "faces", "num_faces", and so on... That is a real usability issue. I think all the files `BGL/include/CGAL/boost/graph/graph_traits_*.h` should be processed by Doxygen, with a rough documentation that links to [the page of the group `PkgBGLTraits`](http://doc.cgal.org/4.8.1/BGL/group__PkgBGLTraits.html).

**Comment by lrineau** [comment]
And see also the issue #1145, that is related.

**Comment by sloriot** [comment]
@afabri already tried to use Doxygen for that but it seems that partial specialization are not handled as we expect.

**Comment by afabri** [comment]
In order to address the second issue, I've moved the tables with the API on a [single page](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-6/output/BGL/group__PkgBGLConcepts.html) and documented the API on each concept page (for example [`FaceGraph`](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-6/output/BGL/classFaceGraph.html)) with doxygen.
)
