### ISSUE TITLE
Snapshot with transparent background

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1313]
Very useful when preparing slides: default option should be "transparent" background, or current color, or user-selected color.

**Comment by lrineau** [comment]
@maxGimeno Do you know if one can draw the OpenGL scene in a transparent texture, with a clear-color that is fully transparent?

**Comment by maxGimeno** [comment]
@lrineau I think I did something similar when testing possibilities for the
ID printing,  so I'm quite sure this is possible.

Le 29 juil. 2016 10:03 AM, "Laurent Rineau" <notifications@github.com> a
écrit :

@maxGimeno <https://github.com/maxGimeno> Do you know if one can draw the
OpenGL scene in a transparent texture, with a clear-color that is fully
transparent?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CGAL/cgal/issues/1313#issuecomment-236119444>, or mute
the thread

**Comment by lrineau** [comment]
> @lrineau I think I did something similar when testing possibilities for the ID printing, so I'm quite sure this is possible.

For the ID printing, I think you did 2D paintings using the `QPainter` API, did not you? Here that is different: make 3D drawing using OpenGL calls, to a transparent texture.

**Comment by maxGimeno** [comment]
@lrineau Yes but before that I tried printing transparent textures directly on the facet. I dropped the idea because it was not very lisible, but the transparent background was working well.
