### ISSUE TITLE
Can`t create convex hull from points

### ISSUE THREAD

**Issue by martinmisa** [CGAL/cgal#1349]
CGAL can`t create convex hull from this points. Assertion in Graham Andrew scan algorithm.
I used latest version of CGAL 4.9 beta1 and compiled c++ code with C++11 compiler.

Example:
[https://gist.github.com/martinmisa/ce67c3ff0b2bb06d154d6ff0dedca578](https://gist.github.com/martinmisa/ce67c3ff0b2bb06d154d6ff0dedca578)

**Comment by sgiraudot** [comment]
Thank you for this self-contained bug report.

The problem here is that your points are aligned, which is exactly the kind of specific cases that won't work with a Simple Cartesian kernel. You can read more about that on [the CGAL website](http://www.cgal.org/FAQ.html#inexact_NT).

As you might have tested, it works with the Exact kernel (I c. However, as the Exact kernel can be pretty slow and limited, I would advise you to use `CGAL::Exact_predicate_inexact_constructions_kernel` which is a good compromise between exactness and efficiency. Your specific case works with this kernel.

**Comment by martinmisa** [comment]
thank you for response
