### ISSUE TITLE
Static variables in Surface_mesher package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1404]
- [ ] `Surface_mesher/include/CGAL/Surface_mesher/Profile_counter.h:35:          static CGAL::Profile_branch_counter NAME(Y); ++NAME;`
- [ ] `Surface_mesher/include/CGAL/Surface_mesher/Profile_counter.h:39:          static CGAL::Profile_branch_counter_3 NAME(Y); ++NAME;`
- [ ] `Surface_mesher/include/CGAL/Surface_mesher/Profile_timer.h:30:          static CGAL::Profile_timer CGAL_profile_timer_tmp(NAME); \`

**Comment by lrineau** [comment]
Those variables have to be `static`. In my opinion, our profiling tools are meaningless in a multi-threading run. But, if we want them to have a meaning, then the bug is in the profiling tools, that must use atomic variables so that they are thread-safe even when used from different threads at the same time.
