### ISSUE TITLE
Epick_d no longer compile on recent Debian testing

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1429]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-141/NewKernel_d/TestReport_lrineau_Debian-Testing.gz
> /usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:74:8: error: no type named 'Literal' in 'struct Eigen::NumTraits<CGAL::Interval_nt<false> >'

**Comment by mglisse** [comment]
The issue is in package Number_types. Beta versions of Eigen (which Debian decided to package, surprisingly) seem to require a new typedef in NumTraits. We can add `typedef Real Literal;` to all our specializations of NumTraits. Eigen developers seems to recommend deriving from `GenericNumTraits<Type>` instead. This is less likely to break on future upgrades, but on the other hand we won't notice so fast if some default values are wrong for our types.

**Comment by lrineau** [comment]
So, what is the soiution? 

Clément, Marc, have you decided anything since the last message? Both 4.9 and 4.8.2 should be published pretty soon (by the end of the week). We are on a tight schedule.

**Comment by lrineau** [comment]
This bug was initially targeting the milestone 4.8.2.

As the patch in #1452 is not so trivial, I wonder if it could be backported to CGAL-4.8.2.

@mglisse Do you think the modifications from #1452 applies smoothly on `releases/CGAL-4.8-branch`?

**Comment by mglisse** [comment]
The PR says: "mglisse wants to merge 2 commits into CGAL:releases/CGAL-4.8-branch from mglisse:Number_types-Eigen_Literal-glisse". Does that answer your question?

**Comment by lrineau** [comment]
Oops. My bad.. Thanks!

**Comment by lrineau** [comment]
Fixed by #1452.
