### ISSUE TITLE
CMP0043 with CMake>=3.0.2 when Qt5 is used

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#152]
http://www.cmake.org/cmake/help/v3.0/policy/CMP0043.html

In the macro `macro(qt5_use_modules _target _link_type)` from `/usr/lib64/cmake/Qt5Core/Qt5CoreMacros.cmake` on Fedora 21, with the RPM `qt5-qtbase-devel-5.4.2-1.fc21.x86_64`, line 281:
```
            set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS_RELEASE QT_NO_DEBUG)
            set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS_RELWITHDEBINFO QT_NO_DEBUG)
            set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS_MINSIZEREL QT_NO_DEBUG)

```
I think all `CMakeLists.txt` of all Qt5 demos should specify:
```
if(POLICY CMP0043)
  # Do not ignore `COMPILE_DEFINITIONS_<Config>` properties
  #   defined by `qt5_use_modules`, in Qt5CoreMacros.cmake
  # http://www.cmake.org/cmake/help/v3.0/policy/CMP0043.html
  cmake_policy(SET CMP0043 OLD)
endif()
```

**Comment by lrineau** [comment]
CC @bo0ts , @maxGimeno

**Comment by bo0ts** [comment]
AFAIK we cannot use the `qt5_use_modules` macro anyway since it is not supported on CMake versions <2.8.0, but otherwise setting the policy to old seems the right thing to do.

I think this should also be patched in Qt5: qt5_use_modules should only set those variables in CMake 2.8.9, but should use a generator expression in all other cases.

**Comment by lrineau** [comment]
Oops. You are right @bo0ts! [`qt5_use_modules` is for CMake>=2.8.9!][qt_cmake-manual]

That means that the branch `CGAL-Qt5_support-GF` will renew the requirements of CGAL for CMake: if you want to be able to compile Qt5 demos, then you need CMake>=2.8.9.

[qt_cmake-manual]: http://doc.qt.io/qt-5/cmake-manual.html#using-qt-5-with-cmake-older-than-2-8-11

**Comment by lrineau** [comment]
@bo0ts : the only test platform that has CMake<2.8.9 is CentOS5. Let's keep it that way, and never install Qt5 on that platform. Then we can documentation that CMake-2.6.4 is supported, but CMake-2.8.9 or later is mandatory:
  - on Windows
  - to compile Qt5 demos.

**Comment by bo0ts** [comment]
I'm not a fan of complicating our requirements matrix even more, but that seems the only solution given that CentOS5 is a must.

**Comment by lrineau** [comment]
I agree that is unfortunate. The current section of `Installation/INSTALL` is:
```
   * CMake (>= 2.6.3), the build system used by CGAL
     Required for building CGAL
     On Windows, CMake >= 2.8.6 is required.
```
it will become:
```
   * CMake (>= 2.6.3), the build system used by CGAL
     Required for building CGAL
     On Windows, CMake >= 2.8.9 is required.
     To compile the Qt5 demos of CGAL, CMake >= 2.8.9 is required.
```

Another solution could be to only documentation that CMake >= 2.8.9 is required, and *privately* communicate to the only customer of GeometryFactory that still uses RHEL 5, that CMake-2.6.4 is also partially supported.

**Comment by lrineau** [comment]
I will contact them, to check if:
  - they still use RHEL 5,
  - and if they can install install a newer CMake on top of their RHEL 5.

**Comment by lrineau** [comment]
I got an answer from the clients who use RHEL 5: they have their own CMake, external to the system, and they agree that we can bump our requirement to CMake-2.8.9.

I propose to bump to CMake>=2.8.11 directly, because that is the lowest version that is tested by our testsuite.

**Comment by bo0ts** [comment]
:+1:

**Comment by lrineau** [comment]
... I want to change my proposal: [it seems that CMake-2.8.11 cannot be build on CentOS 5, but only version 2.8.10.2][1].

Should we require only 2.8.10.2?

[1]: http://linuxtoolkit.blogspot.be/2013/07/july-22-2013-installing-cmake-28-on.html

**Comment by lrineau** [comment]
What is more, @bo0ts, are you aware of [`CMP0062` (since CMake-3.3)](www.cmake.org/cmake/help/v3.3/policy/CMP0062.html)? It is related to `export()` and `install()`, and I wonder if this PR #152 is impacted by that new policy.

**Comment by bo0ts** [comment]
@lrineau Do you mean PR #133 ? It should not be impacted because it uses both `install(EXPORT)` and `export` which the policy mentions as the correct way to use write files containing imported targets. What that policy forbids is the following:

    export(... FILE bla.config)
    install(FILES bla.config DESTINATION ...)

because that would install a file which contains imported targets for the build directory. This should only ever happen by accident because it does not do anything useful.

**Comment by bo0ts** [comment]
Also regarding 2.8.10: I really would like 2.8.11 because it introduced the `target_include_directories` and `target_compile_definitions` commands and target usage requirements. This would finally allow us to propagate include directories and compile definitions (e.g. `-frounding-math` via the `CGAL` target instead of passing around variables).

**Comment by lrineau** [comment]
I have not tried to compile CMake-2.8.10 for CentOS 5. For the moment I trusted [the web page saying it was not possible][1].

[1]: http://linuxtoolkit.blogspot.be/2013/07/july-22-2013-installing-cmake-28-on.html
