### ISSUE TITLE
halfspace_intersection_3 doesn't construct polyhedron that satisfies level 1 is_valid()

### ISSUE THREAD

**Issue by econoraptor** [CGAL/cgal#1610]
I noticed this in my own code, but it seems to also be true for the example: http://doc.cgal.org/latest/Convex_hull_3/Convex_hull_3_2halfspace_intersection_3_8cpp-example.html

Adding `P.is_valid(true, 1);` just before the return statement demonstrates that the polyhedron doesn't pass the is_valid check.

**Comment by afabri** [comment]
The documentation of [`Polyhedron_3:is_valid(bool verbose, int level)`](http://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__3.html#a8b0eb680b5e4bd3f172cad8f73da35c8) states that for  `level == 1`  the normalization of the border edges is checked too.  As `normalize_border()` has not been called you should not call the function with level 1, although I agree that one might assume that the test passes, because a convex hull has no border.
