### ISSUE TITLE
Polyhedron demo: bad display when coordinates are large

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1652]
This is a known problem but I'm filling this issue so that we can keep track of it.

When loading an item that has "large" coordinates (what is the "large" limit is a gray area to me), the display looks bad: for example, with a point set, points flicker when moving the objects and look falsy "aligned" on a grid.

The solution I use for now is to recenter the object, but that's obviously not ideal: one may want to work on an item without changing its coordinates (if it needs to be saved and used with other registered items, it's not possible). Could there be a way to, for example, only "virtually" move if from the OpenGl point of view while keeping the real coordinates in memory?

(cc @maxGimeno @lrineau)

**Comment by maxGimeno** [comment]
I thougt of that but what I can't figure out for now is how to display several items in that case.  The space between them would be wrong.  Maybe a simple scale factor?

**Comment by lrineau** [comment]
I think we should consider sometime to translate the whole scene. We need:\

1. a way for the scene to decide that everything needs to be translated,
2. a way for the scene to communicate the wanted translation to all objects, so that they can recompute their OpenGL buffers with new coordinates,
3. to modify all the picking methods so that they take the translation into account.

Let's say the scene have a new internal member, that is a translation vector `trans`, initially set to (0,0,0).

For point 1, if the scene current center `center` is such that the maximal coordinate of `center + trans` has a `log2` greater than, let's say, 12, that means that the current display wastes 12 bits of precision among the 24 bits of precision available in `float`. In that case, the scene could recompute new translation vector (with the same three coordinates as the center of the scene), and communicate the change to all `Scene_item` with a dedicated signal). As that completely change the API of `Scene_item`, I would purposely break the backward compatibility, and pass that vector to all the draw functions:
```C++
  void Scene_item::draw(Viewer_interface*, vec3)
```

The signal of the scene could also have the vector:
```C++
Scene::new_translation_vector(vec3_
```
if the implement of some `Scene_item` class would like to recompute the buffer as soon as the signal is received (instead of just invalidate the buffer and let them be reconstructed at the next call to `draw()`).

In reaction to the dedicated signal of the `Scene`, all the items must as least invalidate their OpenGL buffers, or recompute them as soon as possible (actually each item could spawn a thread¹, or a TBB task, for that).

¹) The C++11 thread API will pretty soon be available in the Polyhedron Demo, by the way: the PR #1620 will enforce C++11/14 for the demo.

**Comment by afabri** [comment]
We should first find out if that is really important for us, and also ask users with such data how they do it in their current application.

**Comment by lrineau** [comment]
I have already reported similar issues in the paste, with OFF that have coordinates around 600000 (log2 is around 19, so only 5 bits of precision are left for the display): when we zoom, the display flickers a lot. That issue is on real data, that I have been using daily for several weeks.

**Comment by sgiraudot** [comment]
I agree, it's definitely important to us, especially because we share our demo with customers who have such data sets that flicker.

**Comment by maxGimeno** [comment]
I thought we could find a way to "break" the double sent to the buffers into several ones and re-compute it in the shader, it would be far easier to implement but I fear for the performance. Plus it would have to be tested as I am not sure if the imprecision comes from the buffers or the shader itself, in such case this solution would be useless.

**Comment by lrineau** [comment]
Let's implement, if we do not have it, a plugin that recenter a bunch of `Scene_polyhedron_item`, and let's see if that solves the display issue when one zooms.

**Comment by sgiraudot** [comment]
For information, I already had made a plugin that recenters one `Scene_points_with_normal_item`: https://github.com/CGAL/cgal-public-dev/tree/Polyhedron_demo-Recenter-GF

(It's only for one item at a time and only a point set.)

**Comment by lrineau** [comment]
With Google "openscenegraph large coordinates", I found:

http://forum.openscenegraph.org/viewtopic.php?p=52482#52482
> The OSG avoids the precision issues that would occur normally with
OpenGL and systems with large coordinate values that would be an issue
with floats by using doubles in the Camera and internal Transform
nodes, and during the cull traversal accumulates the projection and
modelview matrices all in doubles maintaining the precisions as long
as possible before it's passed to OpenGL where the driver typically
casts down to floats.
