### ISSUE TITLE
Use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1685]
The red testsuite of the [2D Tiangulation demo](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-47/Triangulation_2_Demo/TestReport_lrineau_ArchLinux-CXX14.gz) already says what is to do, but I don't know if and how that has to be fiddled into the CMakeLists.txt 
See also [boost trac](https://svn.boost.org/trac/boost/ticket/9240) .  Maybe we simply have to upgrade boost?

**Comment by afabri** [comment]
@lrineau can you please have  a look

**Comment by lrineau** [comment]
That bug is due to a bug in gcc: [#77948].

 [#77948]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77948

The bug is triggered by the addition of `-std=c++14` (a strict C++14 mode) and `-std=gnu++11` (C++11 with the GNU extensions). The workaround from CGAL/cgal-testsuite-dockerfiles@1e929fe is to use `-std=gnu++14` to enable C++14 with GNU extensions.
