### ISSUE TITLE
hole filling should allow to select a border by a selection of edges

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1707]
Request for enhancement: make the hole filling plugin accept a selection of edges as hole.

**Comment by sloriot** [comment]
What's the point? If you have a hole and the whole cycle is detected and you can simply selected it.

**Comment by lrineau** [comment]
Try the hole filling on the data `e.off` I just send you. You will see that the detect of holes is problematic because the hole we want to fill is joined with the boundary of the surface. If the hole was a selection, the hole filling would work.

**Comment by sloriot** [comment]
I think it is a _bug_ in the hole filling plugin. Using the deformation plugin I edited your model and we cab see 4 different cycles of border halfedges, thus 4 differents holes. I put bug in italic because with this data set, I'm pretty sure `is_valid()` will return false for this polyhedron.
[e-mod.off.zip](https://github.com/CGAL/cgal/files/606389/e-mod.off.zip)
