### ISSUE TITLE
3D demo (Polyhedron_3) crashes while trying to open a large .ply file.

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1754]
Versions: Using CGAL 4.9 64 bits, Polyhedron_3 
OS: Fedora 24 x86_64 
Processor: Intel Core i7-6820HQ CPU @ 2.70GHz x4 
Memory: 32 GB 
Graphics Card: Nvidia GM107GLM Quadro M2000M with 4GB of memory

Bug Description: When Polyhedron_3 is loading a very large point set with color attributes, from a .ply file (3.4Gb; 61,020,661 vertices) it crashes after 6 minutes,  and closes - nothing is rendered on the screen. However the name of the file is displayed on the item list. 

Note: Cédric Portaneri (newly recruited engineer at Inria) reported the bug and can provide you with the file. You can contact him at cedric.portaneri@inria.fr

Steps to Reproduce: 
	1. Go to File > Load...
	2. Open C3DC_StatueZ2-Clean.ply

**Comment by afabri** [comment]
With 4.9  you mean the latest public release. Did you try master?

**Comment by afabri** [comment]
@CedricPortaneri told me that he has the problem with master.

**Comment by CedricPortaneri** [comment]
PS: We suspect the way VBOs are handled  (the cutting in VBOs).

Note: For a big **mesh** (13M triangles) Polyhedron is way faster than Mashlab while Meshlab is even fast with this very large point set (The graphic card is quite impressive).

**Comment by maxGimeno** [comment]
Displaying triangles is faster than displaying points in our demo because there is no culling for points. This means that only visible triangles are actually displayed when all of the points are.

**Comment by maxGimeno** [comment]
The problem is caused by a Qt function. When we try to draw the normals, we need twice the number of points, times 3 times sizeof(double) and this number exceeds MAX_INT, and is given to a Qt function that requires an int. What we are about to do as a temporary workaround is use floats instead of doubles for displaying the point sets, as we are currently doing for the Polyhedrons. And one day I will go through all of our displaying code and optimize the data type for memory allocation. Maybe we could also determine dynamically how many VBOs we should use for data sets that are too big to be stored into a single one.

**Comment by palliez** [comment]
Thanks Maxime! I am glad you found the isssue.
