### ISSUE TITLE
class vs struct in the doc

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1771]
In the doc, we get a random mix of struct and class. See for instance http://doc.cgal.org/latest/STL_Extension/group__PkgStlExtensionUtilities.html with 3 structs in the middle of many classes. I don't mind, but Monique complained about it in a review. Would it be easy to have the tools that build the doc show structs with the word "class"?

**Comment by sloriot** [comment]
I could do a post-processing but I don't really see the point either. @MoniqueTeillaud is it something really important for you?

**Comment by afabri** [comment]
We could unify it in the code, but it seems a bad idea to write `struct` in the code and `class` in the doc: When a user then forward declares it as `class`, some compilers warn about that it is a `struct`.

**Comment by mglisse** [comment]
Are there good reasons for a user to write a forward declaration of a CGAL class? I would be more worried about partial specializations (I don't know if those are also affected by the visual studio bug), which are required when providing a custom number type for instance.

**Comment by lrineau** [comment]
@mglisse Do you consider that mix of `struct` and `class` as a bug, or it is only Monique who complained?

I agree with Andreas that we should not lie: if it is a `struct`, then it is not a `class`. You might want to forward-declare a struct,  a class, or a template from CGAL:
  - to specialize something on it without the need to include its full definition,
  - to break a dependency loop between two sets of headers (but that it mostly a motive for CGAL developers),
  - to be able to declare pointers to something in a compilation unit without the need for the full declaration (used in CGAL in `demo/Polyhedron/`),
  - maybe other uses.

Anyway, there is at least one compiler that warns when two declarations differs on struct/class, and I think that compiler is right to warn, because that breaks the C++ rules. And that is why we cannot lie and document a `class` when the actual type is a `struct`.

On the other hand, we can also convert `Null_functor`, `Sequential_tag` and `Parallel_tag` to `class` instead of `struct`, and I am pretty sure that will not break any code.

**Comment by mglisse** [comment]
I don't care about the mix of struct and class, Monique does.
> breaks the C++ rules

Nope. struct and class can be mixed in any way you like, in standard C++. The issue was always a bug in Visual Studio, which illegally includes struct/class in name mangling. Clang's warning is to help you notice this before porting your code to windows.

In my case, those are inner classes (hard for forward declarations), documented as classes but they are actually typedefs in real code. Whatever game a user might try, they are going to lose. I am fine with replacing struct with class (and adding a bunch of public everywhere) if that helps...

**Comment by lrineau** [comment]
Fixed in CGAL-4.12 by #2608.
