### ISSUE TITLE
Experiment git-submodule for data-set

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1803]
- [ ] Add all data set in a dedicated package, this should not break the release creation or testing
- [ ] Update cmake scripts so that in branch-build testing a package is still working
- [ ] Make the data set package a git-submodule
- [ ] Update release creation script to accomodate git-submodule
- [ ] Document how to use git-submodule for the data-set
- [ ] See how easy it would be to add another submodule with other data-set that would also bring new tests
- [ ] Split the data set package for tests and examples+demos (only one out of the two ends up in a release) ?

**Comment by sgiraudot** [comment]
Do we want to stop separating data sets from one package to another? (I'm not sure if this is how you see things, would it be something like `Data_sets/data/one_data_set.off` or `Data_sets/data/Polygon_mesh_processing/one_data_set.off`?)

I think it would be good to dump the package separation, because some packages actually duplicate data (like point set processing and point set shape detection). Maybe we could still separate the data files (in order to avoid having one directory with hundreds of files) by their types? Point sets, polygon meshes, etc.?

**Comment by sloriot** [comment]
For example `PMP/test/PMP/data/abc.off` would be moved to `Test_data/test/PMP/data/abc.off`, and `PMP/example/PMP/data/abc.off` would be moved to `Release_data/test/PMP/data/abc.off`.

**Comment by efifogel** [comment]
First, I think that one repository called cgal_data should suffice. (This
may not conflict with previous posts.)
Secondly, I think we should allow sharing data (i) between examples, tests,
and demos, and (ii) between different packages.

How about the following: Each set is associated to a pair of a specific
package and a specific type of app. (either examples, tests, or demos), so
for example:

cgal_data/polygon_2
cgal_data/polygon_3
cgal_data/polyhedron_3
cgal_data/point_2
cgal_data/point_3
cgal_data/segment_2
cgal_data/segment_3
cgal_data/surface_3
cgal_data/circle_2
cgal_data/sphere_3

The problem is that a certain set can become huge, while only a small
portion of it is used by specific package/app-type pairs. In this case, we
can split it either \

cgal_data/polygon_xxx_2

or

cgal_data/polygon_2/xxx

The rest can be handled with scripts...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Why do we need to keep the package separation ? I agree with Simon, it would be easier to use and it would avoid data duplication if all the files were in the root cgal_data directory.

**Comment by sloriot** [comment]
That was a first step as it does no require to heavily modify scripts (that is to focus on the technical git-submodule part).

**Comment by sloriot** [comment]
Regrouping data has been done in #4229. I no longer see any need for a submodule. We are not planning to filter all data from history so we won't win any size in the repo history.
