### ISSUE TITLE
warnings in Point set processing 3 on Windows 32 bits

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1806]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10-Ic-95.shtml#Point_set_processing_3

Simon, Andreas, those warnings are probably related to #1633 ("Point Set Structuring", merged in `master`). Can you have a look and find out if pragmas can quiet them?

**Comment by sgiraudot** [comment]
We've already tried pragmas and it's hard to make them work properly (especially because these warning come from the counting iterators of boost and if the user already included the file before including CGAL, then there's no way to prevent it from happening).

This warning is very hard to understand, especially because we managed to suppress it from Andreas' machine with the same configuration as the ones failing on the testsuite... It seems the only way to remove them entirely is to do it from the `CMakeLists`, as it is already done in spatial searching:
```
if (MSVC)
    # Turn off VC++ warning
    SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4244")
endif()
```

This is obviously not satisfactory at all, as users may use the code generating the warning but not the `CMakeLists`. I'm not sure what we should do with this.

**Comment by lrineau** [comment]
I also see similar warnings in Advancing_front_surface_reconstruction:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-95/Advancing_front_surface_reconstruction_Examples/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz

Could we suppress those warnings only for MSVC **and** 32 bits ?

**Comment by afabri** [comment]
A little be less general is

` #pragma warning(push)`
`#pragma warning(disable: 4244)`
`#include <xutility>`
`#pragma warning(pop)`

**BEFORE**

`#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>`

in the testfile.

But to suppress the warning in CMakeLists.txt is ok.  Is it possible in a CMakeLists.txt to differentiate between 32 and 65 bit?
