### ISSUE TITLE
Polyhedron demo: Store color in a comment in an off file 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1882]
## Issue Details

When I  have several mesh patches and I have given them colors by hand, I would like to get the color information be stored in the mesh when I save it to a file.  This could go in a comment line in the off file.
Also it should be read and applied.

**Comment by sgiraudot** [comment]
I think this feature request was mostly motivated by the fact that, when loading several items, they used to all have the same colors (which is not handy if we want to distinguish several part of a same object stored in several files). This was fixed by https://github.com/CGAL/cgal/pull/2062.

@afabri do you still think this would be a useful feature for you even if we can already easily assign a different color to a set of items (at loading or afterwards, both are possible now)?

**Comment by sgiraudot** [comment]
@afabri ping
