### ISSUE TITLE
Set WITH_CGAL_Qt3 to OFF by default

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#193]
For the moment, the CMake option `WITH_CGAL_Qt3` is set to `ON` by default (like all the `WITH_CGAL_<compoment>` options). It should be set to `OFF` by default.

**Comment by bo0ts** [comment]
I think defaulting `WITH_CGAL_Qt3` to `OFF` is the appropriate solution for 4.7. For 4.8 we should aim at the following behavior: Enable a component when all its requirements are met, unless it is explicitly disabled. See [CMakeDepedentOption](http://www.cmake.org/cmake/help/v3.3/module/CMakeDependentOption.html) for a CMake module that makes that very easy.

**Comment by lrineau** [comment]
In my opinion, most of the issue we have with those CMake variables/options is the lack of documentation of their semantic.

In my opinion (but yours seems to differ), the CMake option `WITH_CGAL_Qt3` means that the user wants to enable our support of Qt3. Then the CMake scripts should search for the dependencies, report if they are missing, and set **another** variable if the CGAL component was actually correctly configured. In fb4975f, for example, I have used the target (imported or aliased) itself as the second variable.

**Comment by bo0ts** [comment]
We really do have a different opinion about what those variables should mean. I'm always confused when `WITH_CGAL_Qt3` is set to `ON`, but `CGAL_Qt3` is not build because I don't have Qt3 installed. I would expect the build to fail under those circumstances instead of quietly proceeding.

I think my interpretation is clearer and leaves less room for error, is easier to document and straight forward to use. Imagine the following:

> WITH_CGAL_Qt3: If enabled, try to build the CGAL_Qt3 component.
>                The build will fail if the dependencies cannot be satisfied. 
>                Defaults to OFF.

vs.

> WITH_CGAL_Qt3: If enabled,try to build the CGAL_Qt3 component. 
>                If the dependencies cannot be satisfied, the component will not be build 
>                and no target CGAL::CGAL_Qt3 will be exported. A message will be printed.
>                Defaults to OFF.

There is also a problem with using a target to indicate a component: a component could possibly consists of multiple targets. We do not have that case yet, but it is easy to conceive when you have INTERFACE targets: the main component should consist of the `CGAL` library target, the `CGALIncludes` INTERFACE target and so on.

**Comment by lrineau** [comment]
For the long term, my plan is:
  - first define the variables, by their semantic (a precise documentation),
  - then chose the name of the variables.

And do that for both:
  - the CMake variables and options,
  - and also for the precompiler macros, like the hated macro `CGAL_USE_<something>`.

**Comment by lrineau** [comment]
What is your proposal for the documentation of the other variables? For example, what would be the default value of `WITH_CGAL_Qt5`?

**Comment by bo0ts** [comment]
I would document it exactly the same way as the one for `Qt3` with the default being `ON`. We should probably include a link to the documentation of the package that is associated with the component. That documentation should give further details such as the exact dependencies required (`Qt5Svg` etc).

**Comment by lrineau** [comment]
Fixed by #211.
