### ISSUE TITLE
Polyhedron Demo: Memory leak in the off_plugin or Scene_polyhedron_item

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1957]
## Issue Details

There seems to be an important memory leak in the Polyhedron Demo, while loading/erasing polyhedron items.

That should be fixed as soon as possible.

## Source Code

The following command line loads a Qt Script that loads/erases an OFF file 500 times. The memory usage of the application increases, even if the items are destroyed, up to 7.0GB on my machine.

```shell
./Polyhedron_3 qtscript:'for(i=0; i< 500; ++i) { main_window.open("data/man.off", "off_plugin"); scene.erase(scene.item(0)); print(i);}'
```

I have chosen `data/man.off` for the OFF file. Adapt the path to it on your machine.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): **Linux 64 bits, Fedora 24**
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: **master**, commit 2e7d96f87e88f5950e24d14bede00a87ef646e74
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by maxGimeno** [comment]
I don't think there is a leak. 

The problem comes from deleteLater(). While the script is running, the items are loaded and Scene::erase() calls item->deleteLater, which stacks the call to delete, but does not perform it. 

When the script is finished, Qt destacks all the deleteLater()  calls and destroys the 500 items. But the memory has been stacked, and I think the memory you think has leaked is simply marked reallocable or something : when I tried loading some items after the script, the RES value in top decreased.
 
 I made a test that tends to confirm my theory : replacing item->deleteLater() by delete item in Scene::erase() eradicates the leak. The problem is that with the signals/slots system we use, using delete makes the demo unstable, notably in the Selection_plugin, as items are inter-connected.
