### ISSUE TITLE
Windows: Creation of dev/null file

### ISSUE THREAD

**Issue by mama10** [CGAL/cgal#1988]
## Issue Details

On Windows:
If "dev" folder is present, a "dev/null" file is created.
In CGAL/Tools/Log.h null_ stream opens null device file "/dev/null" which is only correct on Unix.

## Environment

* Operating system: Windows 8.1
* CGAL version: 4.9

**Comment by lrineau** [comment]
@CGAL/developers: The bug is from KDS, in `Kinetic_data_structures/include/CGAL/Tools/Log.h`. In my opinion, the  `std::ofstream` `null_`should stay closed. [One can write to an unopen `ofstream`.](http://stackoverflow.com/questions/28499630/is-it-allowed-to-write-to-a-ofstream-when-it-is-not-opened-in-c)

**Comment by lrineau** [comment]
Thanks @mama10. The bug will be fixed in CGAL-4.10.
