### ISSUE TITLE
BGL documentation: missing models + wrong link

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#2051]
CGAL version: 4.9.1

1- In concept FaceListGraph (and related concepts in the hierarchy)
the only 2 models listed are CGAL::Polyhedron_3 and CGAL::Surface_mesh
see for instance http://doc.cgal.org/latest/BGL/classFaceListGraph.html

Sébastien explained to me that boost::graph_traits< CGAL::Triangulation_2<GT, TDS> > is also a model, see http://doc.cgal.org/latest/BGL/group__PkgBGLTraits.html#BGLT2GT

So this should be documented in the ref manual of relevant BGL concepts. 

2- Is there also a specialization for TDS_2 ? In case this is already available in the CGAL code, then it should be documented. 
If this is not done, then I would suggest to add this specialization. It would be more general than only for triangulations embedded in R^2 (for instance it would allow to represent a surface mesh with a TDS2, which is more efficient in memory). 

3- Note also that the link to EdgeAndVertexListGraph on http://doc.cgal.org/latest/BGL/group__PkgBGLTraits.html leads to error 404 (I did not check other links)

**Comment by MaelRL** [comment]
2- There is a graph_traits file for the TDS2 ([here](https://github.com/CGAL/cgal/blob/master/Triangulation_2/include/CGAL/boost/graph/graph_traits_Triangulation_data_structure_2.h)). No idea what is its status or why it is not documented.

3- The whole page was a mess; it's fixed in the parameterization branch, see [here](https://cgal.geometryfactory.com/~mrouxell/Parameterization_doc/BGL/group__PkgBGLTraits.html) for the clean page.

I can look into these things.

**Comment by lrineau** [comment]
What is the current status of this issue?

The PR #2077 has been merged in `master`, and the PR #2086 also modifies something related (to fix the issue #1246). Will that improve the situation sufficiently to close this issue?

**Comment by MaelRL** [comment]
The parameterization branch (https://github.com/CGAL/cgal/pull/1917) is also necessary for the third point.

**Comment by lrineau** [comment]
Can this issue be marked as fixed, now that #1917 (Parameterization Facegraph) is merged?

**Comment by MaelRL** [comment]
I believe so, the other PRs took care of the 1st and 2nd items.
