### ISSUE TITLE
Documentation that Boost-1.48 is required

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#22]
With new testsuite configurations, we only test Boost-1.53 and later. We should document the new requirement.

**Comment by thijsvanlankveld** [comment]
The linking process of boost should also be fixed, at least on Windows
using Visual Studio when working from the master branch.


I've just upgraded to boost 1.57.0, prompting me to run CMake again for
CGAL.
Firstly, CMake cannot correctly find boost even though I have correctly set
all relevant variables. I have set the following environment variables
(partially redundantly):
* BOOST_ROOT = [...]\boost-1_57_0
* BOOST_DIR = %BOOST_ROOT%
* BOOST_INCLUDEDIR = %BOOST_ROOT%\
* BOOST_LIBRARYDIR = %BOOST_ROOT%\lib64
I can get some of the required variables in CMake to be set automatically
by manually setting BOOST_ROOT in CMake to the same value it already has.

Secondly, after CMake generates the solution files, when trying to run an
application requiring boost, it cannot find the boost_threads[...] library,
even though this lib is in BOOST_LIBRARYDIR, which is set in the PATH
environment variable. I can probably fix this by manually setting the
directories used by the project.


Both of these issues can be fixed by manual interaction, but this shouldn't
be necessary with a build system like CMake and the correct CMakeLists.

**Comment by lrineau** [comment]
@thijsvanlankveld : you are off-topic. Please fill another bug.

**Comment by lrineau** [comment]
Actually, `<boost/container/deque.h>` exists since Boost-1.48. We should documentation that version.

**Comment by lrineau** [comment]
I have change the minimal required version to 1.48, in commit CGAL/cgal-dev@57c0185ffd6cc843a251f42feb232154a120b28d.

**Comment by lrineau** [comment]
I have recreated a branch for it: https://github.com/CGAL/cgal-dev/commit/4eef28be7e4d929c695eaefcda9e573fb5f458ac

**Comment by lrineau** [comment]
Merged in `master`: 1b2dbf118129d56636ba2f371b63325fd4badf68
