### ISSUE TITLE
QP_Solver iterator matrix for A and D

### ISSUE THREAD

**Issue by ng5** [CGAL/cgal#2266]
Is it possible to accept simple T* or double * for A&D, dimensions are already known to QPSolver via M and N. I already have a container that has array allocated on heap for MxN. Code will have much better locality if raw array can be accepted as an input. At the moment, I'm forced to store vector of vector iterator in order to pass to this function, that means I can not use 1D contiguous array as matrix input. I understand this iterator of iterators design was probably done to save space that can not be done via array. But please let me know if there is a better way to solve this?

typedef CGAL::Quadratic_program_from_iterators
<double ** , // for A
 double*, // for b
 CGAL::Const_oneset_iterator<CGAL::Comparison_result>, // for r
 bool*, // for fl
 double*, // for l
 bool*, // for fu
 double*, // for u
 double**, // for D
 double*> // for c 
Program;

**Comment by ng5** [comment]
OK, so this is what I've come up with so far. I'm using boost multiarray to allocate contiguous 1D array. 
it still requires 1 pointer to be stored for each row. But I believe having raw pointer can eliminate this requirement totally.

typedef CGAL::Quadratic_program_from_iterators
<std::vector<boost::detail::multi_array::sub_array<double, 1>::iterator>::iterator, // for A
 double*, // for b
 CGAL::Const_oneset_iterator<CGAL::Comparison_result>, // for r
 bool*, // for fl
 double*, // for l
 bool*, // for fu
 double*, // for u
 double**, // for D
 double*> // for c 
Program;

===================
Then I can now use multiarray:

	boost::multi_array<double, 2> array_2d(boost::extents[2][2]);
	array_2d[0][1] = 1;
	array_2d[0][1] = -1;
	array_2d[1][0] = 1;
	array_2d[1][1] = 3;

	std::vector<boost::detail::multi_array::sub_array<double, 1>::iterator> A;
	A.push_back(array_2d[0].begin());
	A.push_back(array_2d[1].begin());

	Program qp(2, 2, A.begin(), b, r, fl, l, fu, u, D, c, c0);

**Comment by HoffmannMichael** [comment]
Please check this example. It shows how to work with plain arrays.

http://doc.cgal.org/latest/QP_solver/QP_solver_2first_qp_from_iterators_8cpp-example.html

hth, Michael

Am 17.07.2017 um 17:35 schrieb Rohit Vishwakarma <notifications@github.com<mailto:notifications@github.com>>:


OK, so this is what I've come up with so far. I'm using boost multiarray to allocate contiguous 1D array.
it still requires 1 pointer to be stored for each row. But I believe having raw pointer can eliminate this requirement totally.

typedef CGAL::Quadratic_program_from_iterators
<std::vector<boost::detail::multi_array::sub_array<double, 1>::iterator>::iterator, // for A
double*, // for b
CGAL::Const_oneset_iteratorCGAL::Comparison_result, // for r
bool*, // for fl
double*, // for l
bool*, // for fu
double*, // for u
double**, // for D
double*> // for c
Program;

===================
Then I can now use multiarray:

boost::multi_array<double, 2> array_2d(boost::extents[2][2]);
array_2d[0][1] = 1;
array_2d[0][1] = -1;
array_2d[1][0] = 1;
array_2d[1][1] = 3;

std::vector<boost::detail::multi_array::sub_array<double, 1>::iterator> A;
A.push_back(array_2d[0].begin());
A.push_back(array_2d[1].begin());

Program qp(2, 2, A.begin(), b, r, fl, l, fu, u, D, c, c0);

**Comment by ng5** [comment]
hi Michael, 

thank you for your reply. I had already looked into 3 examples given in tutorial. But this is not what i was looking for.

Example 1 - compile time array
Example 2 - MPS format (Not using it)
Example 3 - iterators

Problem with 1 & 3 is still the same. Here A & D are not 1-D array rather they are pointer to 1D array. Therefore A & D matrix are not able to take advantage of cache lines. My question was if A & D both can be acceptable as simple pointer, then code will be much more localized. 
Underlying library can access elements of matrix A & D via single pointer because dimensions are already known. So it should be easy to work out.
A[i][j] = A[i*M+j]

however because example code allows for variable length columns, therefore I believe single pointer is not an easy option to support in the library. Please let me know if i've missed something or else I will close this issue. Once again, thank you for looking into this.

**Comment by HoffmannMichael** [comment]
You can always build your own iterators to access A and D if these matrices are stored in a flat format (as 1-d arrays), see this example that does it for A: http://doc.cgal.org/latest/QP_solver/QP_solver_2solve_convex_hull_containment_lp_8h-example.html.

hth, Michael

Am 18.07.2017 um 13:24 schrieb Rohit Vishwakarma <notifications@github.com<mailto:notifications@github.com>>:


hi Michael,

thank you for your reply. I had already looked into 3 examples given in tutorial. But this is not what i was looking for.

Example 1 - compile time array
Example 2 - MPS format (Not using it)
Example 3 - iterators

Problem with 1 & 3 is still the same. Here A & D are not 1-D array rather they are pointer to 1D array. Therefore A & D matrix are not able to take advantage of cache lines. My question was if A & D both can be acceptable as simple pointer, then code will be much more localized.
Underlying library can access elements of matrix A & D via single pointer because dimensions are already known. So it should be easy to work out.
A[i][j] = A[i*M+j]

however because example code allows for variable length columns, therefore I believe single pointer is not an easy option to support in the library. Please let me know if i've missed something or else I will close this issue. Once again, thank you for looking into this.

**Comment by ng5** [comment]
thanks, that's what I did in the example code I posted, boost's multi_array essentially is 1D wrapper for multidimensional array with STL like iterators support. It requires 1 pointer per row to be saved in the vector. but this is an acceptable compromise. thank you for this library, great work.
