### ISSUE TITLE
Possible bug / incorrect usage of halfspace_intersection_3

### ISSUE THREAD

**Issue by bombax** [CGAL/cgal#233]
I long for the day this function works perfectly for me hehehe.

The problem is posted in full here: https://stackoverflow.com/questions/31790127/geometry-rounding-problems-minimally-disturbed-plane-messes-up-halfspace-inters

In summary: A tiny plane offset (1e-17) on geometry on scale of 1e0 causes the function to produce a very strange polyhedron with non-planar facets!

![ImageOfProblem](http://i.imgur.com/dJVjwgI.png)

**Comment by sgiraudot** [comment]
This issue has been opened for a year, I'm really sorry that you had absolutely no response since then. I am currently trying to review all the issues of CGAL that are still opened.

As @mglisse pointed out on your _Stack Overflow_ topic, it seems difficult to help without a full compilable code that reproduces the bug. Can you provide this please?

**Comment by bombax** [comment]
IIRC this was because I used the inexact kernel and did not fully understand the consequences.

**Comment by sgiraudot** [comment]
Okay, thanks very much for the update. I'm closing the bug.
