### ISSUE TITLE
How were checksums computed? 

### ISSUE THREAD

**Issue by mkandes** [CGAL/cgal#2485]
Hi,

I'm trying to verify the checksums for that latest tarballs, but I'm not getting any matches [1]. How were the checksums computed? I'm using [2]. Note also sha256sum and sha512sum don't match either.

Marty

[1]

[mkandes@comet-ln3 cgal]$ ls
checksums  tarballs
[mkandes@comet-ln3 cgal]$ cat checksums/CGAL-4.11/md5sum.txt | grep CGAL-4.11.tar.gz
8f21af7ffb4f638e289ae6efd3da0787  CGAL-4.11.tar.gz
[mkandes@comet-ln3 cgal]$ md5sum tarballs/CGAL-4.11.tar.gz 
e67dc4e9dd8d1701b43a5fb7d7d88e07  tarballs/CGAL-4.11.tar.gz
[mkandes@comet-ln3 cgal]$ cat checksums/CGAL-4.10.1/md5sum.txt | grep CGAL-4.10.1.tar.gz
9f05f34871eef029ada84e3ef09939b2  CGAL-4.10.1.tar.gz
[mkandes@comet-ln3 cgal]$ md5sum tarballs/CGAL-4.10.1.tar.gz a65a276ffaea1c081c336ec6dd977525  tarballs/CGAL-4.10.1.tar.gz

[2]

[mkandes@comet-ln3 cgal]$ md5sum --version
md5sum (GNU coreutils) 8.4
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.

**Comment by lrineau** [comment]
Those files `CGAL-4.11.tar.gz` and `CGAL-4.10.1.tar.gz` you have downloaded are files that are automatically generated by the Github web interface. They follow the files layout of the CGAL Git repository, whereas our releases tarballs are generated differently.

I have removed the `.gz` and `.bz2` lines from checksum files, because I no longer publish those versions.

In the **Downloads** section, at https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.11, the two links "Source code" (zip and gz) should be ignored. What do you think I should write in the text just above to explain that?
