### ISSUE TITLE
make_surface_mesh() parts of mesh sometimes inverted, sometimes missing

### ISSUE THREAD

**Issue by Philius** [CGAL/cgal#2513]
I used CGAL to generate a mesh.
See [here](http://philipashmore.blogspot.ie/2017/09/event-horizons-of-approaching-black.html)
You can download the code I used from [here](https://sourceforge.net/projects/event-horizon/)
If you run the `event-horizon-process-igl` program you can adjust the distance parameter directly.
What you'll see is two "lobes" that merge if they get close enough.
As you adjust the distance via the GUI, sometimes one or both lobes are inverted, sometimes one is missing.

* Operating system Linux 64 bits: Debian Stretch
* Compiler: built with g++(6.3.0) example built with clang++ 3.8.1-24 (tags/RELEASE_381/final)
* Release or debug mode: release -O3
* Specific flags used (if any):
* CGAL version: 4.12-I-900
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.2, Intel TBB

**Comment by Philius** [comment]
[make.txt](https://github.com/CGAL/cgal/files/1364023/make.txt)

**Comment by sloriot** [comment]
From what I understand, you should check for each connected component of your mesh whether it is outward oriented. You can do so by using the functions [`is_outward_oriented()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad71360b56f0d5340bf3006febd49286c) and [`reverse_face_orientations()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad8a3439883e3e76651f96d15ba58b2bc).
After looking at the code, you are simply using `CGAL::output_surface_facets_to_off()` and the output of the various components are not consistent. This is the case because the function does not expect the output to be closed. I guess we should write a higher level function that is making the surface outward oriented and add it in the Polygon Mesh Processing package.

**Comment by Philius** [comment]
Is there some example for seeding the mesh to achieve this?
Also, before the event horizons connect, sometimes one or the other has its normals inverted, as in my blog picture.
Maybe these issues are related.
When the event horizons merge a hole forms in the middle so then the entire mesh isn't outward facing.

**Comment by sloriot** [comment]
Not really, that's why I flagged the issue as feature request.
Basically, you need to split the mesh into connected components and orient each component, taking into account the inclusion of theses components (in case of nested components). I almost did the work in the function [`does_bound_a_volume()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga808a0177bf30833d2c1e390e533fec7f) which is checking the consistent orientation of each components. Maybe @lrineau can comment on the fact that no nested meshes could be generated and a simple orientation of each components using [`is_outward_oriented()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad71360b56f0d5340bf3006febd49286c) and [`reverse_face_orientations()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad8a3439883e3e76651f96d15ba58b2bc) would do the job.
