### ISSUE TITLE
CGAL 4.11 compilation issue with boost 1.53

### ISSUE THREAD

**Issue by VincentRouvreau** [CGAL/cgal#2524]
## Issue Details

I used to compile different CGAL versions (4.3, 4.4, 4.5, 4.6, ... 4.9.1) with the same Boost version 1.53 to insure my code (Gudhi) is compatible with all CGAL versions. But the latest CGAL 4.11 does not compile.

It seems to be a boost issue :
   $ make
Scanning dependencies of target CGAL
[ 33%] Building CXX object src/CGAL/CMakeFiles/CGAL.dir/all_files.cpp.o
In file included from /usr/local/include/boost/atomic.hpp:12:0,
                 from /home/vincentrouvreau/workspace/CGAL-4.11/include/CGAL/atomic.h:30,
                 from /home/vincentrouvreau/workspace/CGAL-4.11/include/CGAL/Kinetic/internal/debug_counters.h:25,
                 from /home/vincentrouvreau/workspace/CGAL-4.11/src/CGAL/KDS_Log.cpp:23,
                 from /home/vincentrouvreau/workspace/CGAL-4.11/src/CGAL/all_files.cpp:13:
/usr/local/include/boost/atomic/atomic.hpp:166:16: error: ‘uintptr_t’ was not declared in this scope
 typedef atomic<uintptr_t> atomic_uintptr_t;
                ^
/usr/local/include/boost/atomic/atomic.hpp:166:25: error: template argument 1 is invalid
 typedef atomic<uintptr_t> atomic_uintptr_t;

You can find CMake logs attached.
[cmake.log](https://github.com/CGAL/cgal/files/1372392/cmake.log)

For your information, header only version of CGAL 4.11 is fine with compiling my piece of code.

## Source Code

The error occured while compiling CGAL library (cmake . && make)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04 x64
* Compiler: gcc 5.4.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version: 1.53.0
* Other libraries versions if used (Eigen, TBB, etc.):
   GMP_VERSION = '6.1.0'
   MPFR_VERSION = '3.1.4'
   ZLIB_VERSION = '1.2.8'

**Comment by lrineau** [comment]
That seems to be a bug of Boost-1.53.0 and 1.54.0, that was fixed in later versions:
https://svn.boost.org/trac10/ticket/7979

You can either:
 - update to a more recent Boost version,
 - or use the compiler flags to use C++11 or later, so that CGAL uses C++11 atomic variables, instead of Boost ones.

I think there is nothing that can be done in CGAL to workaround that issue. I cannot even blacklist Boost-1.53 completely, because it is tested in our daily testsuite, and it does work. That must be a bad combination of compiler+Boost version.
