### ISSUE TITLE
Can we get a minor release?

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#2726]
## Issue Details

There was an issue with the latest release (https://github.com/Microsoft/vcpkg/issues/2471) that causes `set_target_properties` to be missing from `CGALExports.cmake` after installation. After some testing I realized it is actually fixed in recent commits. Could we get a minor release with the latest master that contains the fix?

**Comment by lrineau** [comment]
The PR you are talking about is #2700. I was about a bug introduced in CGAL `master` branch after the release CGAL-4.11, and thus it did not impact any released version (such as CGAL-4.10.1 or CGAL-4.11). The patch will be released in CGAL-4.12-beta1 (planned in a month), and then CGAL-4.12 (planned in two months). Until then, it will be only in the un-released `master` branch, and that is appropriate because the bug was only there.

What I do not understand is the bug https://github.com/Microsoft/vcpkg/issues/2471, that seems to be about the packaged version of CGAL in vcpkg. But [its control file][1] says that the current version that is packaged is CGAL-4.11. I do not understand. As far as I know, the bug you reported in #2700 does not exist in CGAL-4.11. So, what exactly is the bug in https://github.com/Microsoft/vcpkg/issues/2471?

[1]: https://github.com/Microsoft/vcpkg/commits/master/ports/cgal/portfile.cmake

**Comment by jasjuang** [comment]
This problem is different from #2700. With the latest release the entire block of `set_target_properties` is missing in `CGALExports.cmake` after installation. Right before the merge of #2700 `set_target_properties` is already there in `CGALExports.cmake`, it's just that the entry of `INTERFACE_INCLUDE_DIRECTORIES` is wrong hence #2700 corrects it.

Therefore the conclusion is somewhere before the latest release and the commit right before the merge of #2700 fixes the missing entire block of `set_target_properties` is missing in `CGALExports.cmake` after installation issue.
