### ISSUE TITLE
Compilation flag "frounding-math" incorrectly propagated to CUDA NVCC compiler

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#2775]
## Environment

* Operating system: Ubuntu 16.04
* Compiler: GCC 5.4
* CGAL version: Latest
* Boost version: 1.58

## Issue Details

For some weird reason the compilation flag `frounding-math` is propagated by CGAL to my CUDA application, and because the NVCC compiler cannot recognize it, it causes a compilation error.

## Source Code

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX CUDA)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cu)

find_package( CGAL REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

main.cu
```
int main(){
return 0;
}
```

After the usual `mkdir build`, `cd build`, `cmake ..`, `make`, here is the error

```
[ 33%] Building CUDA object CMakeFiles/Example.dir/main.cu.o
nvcc fatal   : Unknown option 'frounding-math'
```

I tried to debug myself, according to `/usr/lib/x86_64-linux-gnu/CGAL/CGALConfig.cmake`, there is a line `set(CGAL_CXX_FLAGS_INIT " -frounding-math" )`, so I went back to the source code and trace the variable `CGAL_CXX_FLAGS_INIT` and saw it in `Installation/cmake/modules/CGALConfig_install.cmake.in` and `Installation/cmake/modules/CGAL_SetupFlags.cmake`, and it seems to be related to `CMAKE_CXX_FLAGS` only, nothing suspicious, and I have no idea what to look for afterwards to track down the bug. Can someone look into this?

I also tried modifying the `CMAKE_CXX_FLAGS` manually in the minimal example without linking to CGAL and it doesn't affect NVCC, 

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX CUDA)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -DNDEBUG")

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cu)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})
```

Compiles without a problem. Seems like somewhere in CGAL it forces propagation of the `frounding-math` flag to non C++ compilers that causes the issue.

**Comment by lrineau** [comment]
The installation of CGAL in `/usr/lib/x86_64-linux-gnu/` was not compiled by the CUDA compiler. It is not compatible with it.

When you say:
> CGAL version: Latest
please be more precise. Let us know how you have installed CGAL on that machine.

You can try the header-only mode of latest Git version of CGAL in the `master` branch (that will be published as CGAL-4.12): for `CGAL_DIR`, use the path to the root of the Git working directory.

By the way, do you really think that CUDA can be used with CGAL? That is not a setup that is tested and supported.

**Comment by jasjuang** [comment]
@lrineau I wasn't asking CGAL to support CUDA. I was simply asking CGAL to not break when my project contains CUDA code and it also has to be linked to CGAL, and it should be able to not break it. I have no problems linking to OpenCV and PCL since they don't propagate flags that is intended for GCC to NVCC. The problem is CGAL does it and I am unable to track down how that happens. I am also only using CGAL in my cpp files. My cu files are completely irrelevant to CGAL, they just happen to be in the same project.

My CGAL is compiled separately without CUDA, and it is compiled with the very standard

```
git clone https://github.com/CGAL/cgal
cd cgal
mkdir build
cd build
cmake ..
make -j
sudo make -j install
```

**Comment by sloriot** [comment]
The flag propagation has been fixed at least a month ago by @lrineau. What is the HEAD of the CGAL your using?

**Comment by lrineau** [comment]
`-frounding-math` is added to the flags anyway, if the GCC compiler is detected.

**Comment by lrineau** [comment]
@jasjuang, in https://github.com/CGAL/cgal/issues/2775#issuecomment-362361184 said:
> @lrineau I wasn't asking CGAL to support CUDA. I was simply asking CGAL to not break when my project contains CUDA code and it also has to be linked to CGAL, and it should be able to not break it. I have no problems linking to OpenCV and PCL since they don't propagate flags that is intended for GCC to NVCC.

Good. I had not understood that. Thanks for the explanation. I should have known, because you probably cannot develop a full project using only the CUDA compiler, but you need a regular compiler targeting your CPU as well.

Indeed, the current version of CGAL you are using (note that you have not yet told us which version, probably [4.7][1]), the flags are propagated to the CMake cache variable `CMAKE_CXX_FLAGS` (and similar ones), in your user project. You can block that behavior if you set the CMake cache variable `CGAL_DONT_OVERRIDE_CMAKE_FLAGS` to `TRUE`, right before the first time `UseCGAL.cmake` is included in the project. If you do that, make sure `-frounding-math` is added to compilation flags of all targets that use CGAL, otherwise the CGAL code will break for sure.

Alternatively, you can opt for the very last development version of CGAL, in the `master` branch of the Git repo, that will become CGAL-4.12-beta1 in the following month., and then CGAL-4.12. That version of CGAL uses modern CMake technics, to ensure that `-frounding-math` is added only to targets linked with the imported target `CGAL::CGAL`.

[1]: https://launchpad.net/ubuntu/xenial/+source/cgal

**Comment by lrineau** [comment]
We can continue the discussion here, but I close the issue, that is already fixed in the development branch targeting CGAL-4.12-beta1.

**Comment by lrineau** [comment]
For the records, was fixed by #1436.

**Comment by jasjuang** [comment]
@lrineau @sloriot As you can see from my previous comment, I did not switch branches during my cgal installation, therefore by default it is from the latest master, `git log --oneline` shows 

```
2e7c3ee Merge branch 'releases/CGAL-4.11-branch'
36514e2 Merge pull request #2759 from maxGimeno/Minor_feature_requests-GF
66b19d9 Merge pull request #2779 from lrineau/Mesh_3-fix_bugs-GF
```

I am assuming master contains all the latest fix including #1436. I also don't see any development branch available that I can check out called CGAL-4.12-beta1, and yes, as mentioned in my very first post, I am using `CGAL::CGAL` instead of the outdated `UseCGAL.cmake`.

This is still broken for me. Are you not able reproduce the problem with the minimal code? I can open up an AWS instance for you to ssh in with CUDA and CGAL installed along with the minimal code to demonstrate this problem exist if needed.

**Comment by lrineau** [comment]
Sorry. That is right that you gave us how you installed CGAL in https://github.com/CGAL/cgal/issues/2775#issuecomment-362361184:
```
git clone https://github.com/CGAL/cgal
cd cgal
mkdir build
cd build
cmake ..
make -j
sudo make -j install
```

Then maybe you have two versions of CGAL installed on your system:
- one with `CGALConfig.cmake` at  `/usr/lib/x86_64-linux-gnu/CGAL/CGALConfig.cmake`, installed by the Ubuntu package manager (CGAL version 4.7),
- and another one you installed from Git, at `/usr/local/lib/CGAL/CGALConfig.cmake`.

Can you check the value of `CGAL_DIR` in the CMake cache?

**Comment by jasjuang** [comment]
@lrineau I installed the latest CGAL on my private ppa so in my local machine I can simply so `sudo apt install cgal` to install it. I am not using the one from Ubuntu package manager. If I were using it `CGAL::CGAL` would've failed. I didn't bring this up initially because I don't want to complicate things. `CGAL_DIR` is showing `/usr/lib/x86_64-linux-gnu/CGAL ` as expected. I can reproduce the same problem if I install CGAL on my local machine without going through my private ppa.

**Comment by lrineau** [comment]
Thanks @jasjuang for those explanations.

So indeed you are probably using a very recent version of the `master` branch of CGAL.

If you have a look at the file `CGALExports.cmake` that is generated by CMake in the binary directory, you can see:
```cmake
set_target_properties(CGAL::CGAL PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-frounding-math"
#...
```
So that compilation option `-frounding-math` will be added to all compilation of sources used to generated any target linked with `CGAL::CGAL`. If one of those sources uses the CUDA compiler instead of the C++ compiler, it seems that can fail.

The only solution I see is to compile the code using CGAL and the CUDA in different targets. You could for example separate the CUDA code into a separated library (static of shared, you choice), and link it with the target that uses the CGAL code. Alternatively, you could separate the C++ code that uses CGAL in a library. That way, the flag `-frounding-mode`would only apply to the target that uses `CGAL::CGAL` and not to the CUDA code.

If you see another way to setup the target `CGAL::CGAL`, let me know. Maybe we could use the generator expression `$<CXX_COMPILER_ID:comp>` in `INTERFACE_COMPILE_OPTIONS`, to check that the compiler is a GNU compiler. What do you think?

**Comment by jasjuang** [comment]
@lrineau You are right, it is the problem of `target_compile_options`. Adding the generator expression actually solves it for me. I will submit a PR in a little bit.
