### ISSUE TITLE
Degenerate faces in CDT mesh after refinement

### ISSUE THREAD

**Issue by arnsong** [CGAL/cgal#2924]
I'm getting unexpected behavior when using the Delaunay mesher with a Constrained Delaunay Triangulation.  To try and debug the code, I have been running single refinement steps with the mesher.  During the refinement step, the mesher will generate a degenerate face whose vertices lie along a constraint edge.  This face isn't caught by a subsequent routine, or at least not one that I am seeing. This problem cascades into our voronoi generation scheme because the face of area zero or very near zero cause an assertion to be thrown.

System and install info:
- Ubuntu 16.04 (Xenial) in a docker container
- CGAL 4.11.1

Here is the gist: https://gist.github.com/arnsong/9f94188478b3ca9aa6af48c0cfd624a9 #

**Comment by arnsong** [comment]
When the `Refine_edges` mesh level generates a `star_hole` it "squashes" one of the faces, but does not remove this face from the triangulation.  I have attached a sketch of what I observe to be the output of the `star_hole` function in `Refine_edges.h`.
[Face squashing.pdf](https://github.com/CGAL/cgal/files/1807830/Face.squashing.pdf)

**Comment by MaelRL** [comment]
Hello,

This is not what happens:
- The first refinement step does not add that `(0,0)` point, you can see in the log it says:
```
(3.83476e-17 0) rejected (temporarily)
``` 
This means that the refinement point is not inserted because we must first refine an edge to preserve some properties. After this step, there are still 4 points and 2 faces.
- On the second step of the refinement, this edge is refined by inserting its mid point, but since your coordinates are somewhat "dirty":
```
Point 1: (1, 0)
Point 2: (6.123233995736766e-17, 1)
Point 3: (-1, 1.2246467991473532e-16)
Point 4: (-1.8369701987210297e-16, -1)
```
and since you are using a kernel with inexact constructions, this new point `(0.49999999999999989 -0.5)` does not fall exactly on the edge. The insertion of the point in the triangulation is not on the edge, but in the face. It thus creates this near-degenerate face. It however is still a valid face (if you call the orientation predicates, you will see that its orientation is positive) and a valid triangulation.

Two ways to obtain the result you expect are:
- use an exact construction kernel (here you need square roots, so for example `CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt`). This will ensure the midpoint is exactly on the edge.
- clean the input coordinates

@lrineau might know something more.

Also, as @janetournois  pointed out, you can look into [this class](https://github.com/CGAL/cgal/blob/master/Mesh_2/include/CGAL/Constrained_voronoi_diagram_2.h) to generate Voronoi diagrams from constrained triangulations.

**Comment by lrineau** [comment]
That is not a bug. The almost degenerate face is still a valid face of the triangulation, and it is outside of the meshing domain. That is completely normal and expected as soon as you use inexact construction. And that should not be an issue, because that face is outside of the domain. Just filter out the faces that are outside.

**Comment by arnsong** [comment]
Ah... makes sense.  Thank you for taking a look at this.  

However, the near degenerate faces with the inexact constructions still are problematic for the Voronoi diagram generated from Constrained_Delaunay_Triangulation.  Even though the faces are valid in the triangulation, when we we try to construct an edge from the triangle circumcenters, `Constrained_voronoi_diagram_2` fails because it can't pass the assertion that the points are not collinear in `circumcenter_translateC2`.  We don't want to move to exact constructions, because these simple geometries are just test cases and using exact constructions will be much too expensive for the refinement and complex geometries in our applications.
