### ISSUE TITLE
Assertion fail in CGAL::intersection using Epick but not Epeck

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#304]
The following small example

```cpp
#include <iostream>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

int main(int argc, char * argv[])
{
  using namespace std;
  typedef CGAL::Epick Kernel;
  typedef CGAL::Triangle_3<Kernel> Triangle_3; 
  typedef CGAL::Point_3<Kernel> Point_3; 
  double V[4][3];
  istringstream(
R"(0x1.326b2f23033a4p-2 0x1.9359791819d24p-5 0x1.3a96e58a32f45p+1
0x1.1f1476af89c5ep-1 0x1.3e28ed5f138bdp-2 0x1.5c0e9d51b4fe8p+1
0x1.5db402d16b97cp-2 0x1.76d00b45ae5f2p-4             0x1.4p+1
0x1.3ba25a2acac4cp-2 0x1.dd12d15656264p-5             0x1.4p+1)")>>
      hexfloat>>
      V[0][0]>> V[0][1]>> V[0][2]>>
      V[1][0]>> V[1][1]>> V[1][2]>>
      V[2][0]>> V[2][1]>> V[2][2]>>
      V[3][0]>> V[3][1]>> V[3][2];
  Triangle_3 A(
    Point_3(V[2][0],V[2][1],V[2][2]),
    Point_3(V[3][0],V[3][1],V[3][2]),
    Point_3(V[0][0],V[0][1],V[0][2]));
  Triangle_3 B(
    Point_3(V[2][0],V[2][1],V[2][2]),
    Point_3(V[1][0],V[1][1],V[1][2]),
    Point_3(V[3][0],V[3][1],V[3][2]));
  CGAL::Object result = CGAL::intersection(B,A);
}
```

 fires an assertion inside `CGAL::intersection` when using the `CGAL::Epick` kernel

```
Assertion failed: (this->is_initialized()), function get, file /usr/local/include/boost/optional/optional.hpp, line 1004.
```

This is avoided if using the `CGAL::Epeck` Kernel.

I'm using version 4.6 (from brew), compiling with clang Apple LLVM version 6.1.0 on a mac os X machine.

**Comment by sloriot** [comment]
Even if I agree that it is unfortunate, it is not a bug. The intersection function for two triangles first checks the intersection type of the triangle supporting planes. This is an intermediate construction a kernel with inexact constructions is not able to handle correctly.
In order to keep using a kernel with inexact constructions, I usually advice to first call the `do_intersect` predicate and then call the intersection function using EPECK on primitives converted on the fly using `CGAL::Cartesian_converter`. You'll have to convert the output using another `CGAL::Cartesian_converter`. The call to `do_intersect` is not mandatory, it usually depends on your setting.

**Comment by alecjacobson** [comment]
Thanks. So, why expose `CGAL::intersection` to the Epick kernel if it's not supported?

**Comment by afabri** [comment]
It does as good as it can.

andreas

**Comment by lrineau** [comment]
`CGAL::intersection` is a generic function. Its implementation is the same for all CGAL kernels. There are cases it will work, even with the Epick kernel. But in general it is not safe to use it with a kernel that does not have exact constructions.

**Comment by alecjacobson** [comment]
Thanks for the instructions. This is helpful indeed.

Perhaps a useful function would be to "return false" or throw a catchable
exception if construction is not possible. Or maybe a
`is_intersection_construction_possible` function that can be called first.
Anything is better than segfault or mysterious boost assertion.

**Comment by sloriot** [comment]
Absolutely, but with the current implementation I'm not sure it would be possible in all the cases.
I submitted some time ago a proposal to get the intersection always computable with EPICK but due to lack of time it was never implemented. I even proposed a GSoC internship this year related to that.
