### ISSUE TITLE
Enhance Google research results look

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#313]
If you look for any CGAL class or package in google (say [`polygon_set_2`](https://www.google.com/search?q=polygon_set_2&ie=utf-8&oe=utf-8)), you'll see as title for the CGAL entry `Polygon_set_2 - CGAL on`.

Looks like using Rich Snippets might help fixing that (that is the extra `on`).

**Comment by lrineau** [comment]
Are you talking about https://developers.google.com/structured-data/?

Have you found any explanation of that "CGAL on"? Do we have a tag in the HTML that Google interprets as structured data?

**Comment by sgiraudot** [comment]
It seems to me this bug is half-solved. When searching `polygon_set_2` on Google, the first two results are:
- [Polygon_set_2 - CGAL 4.8.1 - Manual](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiMl-mIu7bOAhXFuhoKHVNYBGwQFggcMAA&url=http%3A%2F%2Fdoc.cgal.org%2Flatest%2FBoolean_set_operations_2%2FclassCGAL_1_1Polygon__set__2.html&usg=AFQjCNEzH7OGroWsE3b7WdoS4WyXcM2G7w&sig2=PissZjE_U-IN1chiYiuGvw&bvm=bv.129389765,d.d2s) that links to the `latest` manual
- [Polygon_set_2.h - CGAL on](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiMl-mIu7bOAhXFuhoKHVNYBGwQFggkMAE&url=http%3A%2F%2Fdoc.cgal.org%2F4.2%2FCGAL.CGAL.2D-Regularized-Boolean-Set-Operations%2Fhtml%2FPolygon__set__2_8h.html&usg=AFQjCNEJvQ81l1VnV5TVJ_O38kDPyCl_Cw&sig2=tyxjcpDPYdP0RDDaF1h3Vw&bvm=bv.129389765,d.d2s) that links to `4.2` manual

I have do idea why the `4.2` manual is still so high on the results, but it seems to me that the "CGAL on" problem is solved in the current version. Do we close the issue?

**Comment by lrineau** [comment]
The 4.2 manual is the only version that does not have [`rel="canonical"` links][*].

[*]: https://support.google.com/webmasters/answer/139066?hl=en#2

**Comment by sgiraudot** [comment]
Okay, so I guess we can close this issue now.

**Comment by lrineau** [comment]
I have blocked http://doc.cgal.org/4.2/ from being indexed by bots, in a `robots.txt` file. That will solve the issue completely as far as I know.
