### ISSUE TITLE
operator+= not implemented for Weighted_Point_3

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3167]
## Issue Details
If I understand [the documentation](https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Weighted__point__3.html#aff371a7ec70357bca92293889184c290) correctly, than the class Weighted_point_3 should have the operator += implemented, however, that doesn't seem to be the case. Am I doing something wrong?

> weighted_point.cpp:13:5: error: no match for ‘operator+=’ (operand types are ‘CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>::Weighted_point_3 {aka CGAL::Weighted_point_3<CGAL::Epick>}’ and ‘CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>::Vector_3 {aka CGAL::Vector_3<CGAL::Epick>}’)
  wp += v;

## Source Code

``` c++

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

int main()
{
	K::Point_3 p(0,0,0);
	K::FT w(1);
	K::Weighted_point_3 wp(p,w);
	K::Vector_3 v(1,1,1);
	
	p += v;
	wp += v;
}
```

## Environment

* Operating system: Ubuntu 18.04
* Compiler: g++
* CGAL version: 4.12

**Comment by MaelRL** [comment]
Sorry, that's a problem with the doc; there is no such operator for weighted points.

More precisely, the operator `+=` is just a call to the kernel's implementation of the concept [ConstructTranslatedPoint__3](https://doc.cgal.org/latest/Kernel_23/classKernel_1_1ConstructTranslatedPoint__3.html) and it only works with (bare) points, there is no overload for weighted points.

**Comment by afabri** [comment]
@MaelRL do you see any technical/philisophical problem adding it?

**Comment by MaelRL** [comment]
Technical none. Philosophical, well... The construction is called `ConstructTranslatePoint_3`, it's not meant to translate weighted points so it shouldn't receive an overload. 

The "workaround" `wp = WP_3(wp.point + v, wp.point())` could be written in the class directly, but there is so such thing for other kernel objects (e.g. in `Sphere_3`, which is basically a weighted point).

I think this issue is part of a larger problem: there are a couple of constructions/predicates that are not acting on weighted points but that still might ought to (for example `ComputeX_3`, or `LessX_3`). That makes weighted points a bit tedious to manipulate because you have to grab the bare point inside. 

However, when implicit conversions between P3 and WP3 were removed, it was decided not to create overloads of these predicates/constructions with weighted points because if you start providing overloads for weighted points, where do you stop, `LessX_3`? What about `Less_XYZ_3`, that's already more dangerous. And then come `Collinear_3`, `Angle_3`, `Orientation_3`... We could go over all the predicates and constructions and add these overloads where deemed safe, but I see pros and cons so I stayed on the fence on this since #2102.
