### ISSUE TITLE
Classification - Planimetric_grid: Index out bounds error

### ISSUE THREAD

**Issue by ahuarte47** [CGAL/cgal#3176]
## Issue Details

I get an `index out bounds` runtime error when I am calculating features ([`Feature_set_generator`](https://github.com/CGAL/cgal/blob/master/Classification/include/CGAL/Classification/Point_set_feature_generator.h)) of a LAS file for 5 scales. I think there is an bug when `Planimetric_grid` is calculating if a cell is [empty](https://github.com/CGAL/cgal/blob/master/Classification/include/CGAL/Classification/Planimetric_grid.h#L232). 

Should `has_points` method check the X and Y indexes when it is processing child scales?

## Source Code

 ```
 /*!
    \brief Returns `false` if the cell at position `(x,y)` is empty, `true` otherwise.
  */
  bool has_points(std::size_t x, std::size_t y) const
  {
    if (m_current_scale == 0)
    {
      if (x >= m_grid.width() || y >= m_grid.height())
        return false;
      return (!(m_grid(x,y).empty()));
    }
    else
    {
      if (x >= m_width || y >= m_height) //<-- THIS fixes the issue
        return false;                    //<-- THIS fixes the issue
      return m_has_points[x * m_height + y];
    }
  }
```

## Environment

* Operating system: Windows 10 64 bits
* Compiler: Visual Studio 2017
* Release or debug mode: all
* CGAL version: 4.12
* Boost version: 1.67

**Comment by sgiraudot** [comment]
Can you please share some source code to show of how you are using the classes?

The function `has_points()` is not supposed to be called with `x,y` outside of the range (the case with `m_current_scale==0` is handled because of a specific internal usage of the function), so if there is indeed an error in the generator, I would prefer fixing it than adding a test without knowing where the error comes from.

Also, could you run again your code after adding `#define CGAL_CLASSIFICATION_VERBOSE` before including the Classification file? That way you will see more information and that might help understanding what is going on. Thanks!

**Comment by ahuarte47** [comment]
Hi Simon, I simply use `Feature_generator` class without any echo, color and normal map information.

```
Feature_set features;
Point_set points;
size_t n_scales = 5;
float voxel_size = -1.f;

// Fill points...
for (int i = 0, icount = ....; i < icount; ++i)
{
     double x = ...
     double y = ...
     double z = ...
     points.insert(Point(x, y, z));
}

auto pmap = points.point_map();

Feature_generator*
generator = new Feature_generator(
   features, 
   points, pmap, 
   n_scales, CGAL::Default(), CGAL::Default(), CGAL::Default(), voxel_size);

```

This works for other files, but some ones throw this error.

I attach a file (LAS version: 1.4 PointFormat: 7):
[597_4659_piscina.zip](https://github.com/CGAL/cgal/files/2110251/597_4659_piscina.zip)

For this file, The `Planimetric_grid` constructor calculates the values `m_width`=101, and `m_height`=94, it crashes when `child_scale`=2 is being created.

**Comment by sgiraudot** [comment]
Okay, it turns out there was indeed a bug. It happened with the file you provided but as you pointed, I also managed to reproduce it using other files. I'm quite surprised we did not get any error before…

I just submitted a bugfix (that actually does some clean up of the code - which was not really well done): https://github.com/CGAL/cgal/pull/3177

Thanks for the report! The fix should be integrated to the next bugfix release, in the mean, you can either get the fix from my PR or use the fix that you suggested that is also a valid way to fix it.

**Comment by ahuarte47** [comment]
Thanks a lot @sgiraudot !!!! I am waiting your Classification 2.0 new version. Thank you very much for your work!

**Comment by ahuarte47** [comment]
https://github.com/CGAL/cgal/pull/3177 was merged, I works great. Should I close this issue? or must it be done by the PR owner?

**Comment by lrineau** [comment]
I should have done it yesterday. Thanks.
