### ISSUE TITLE
Regular_triangulation_3: how to determine whether point is in conflict with other vertices

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3188]
The [documentation for insert](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Regular__triangulation__3.html#a1f9d427d62b0bf666216471597210b86) gives four possibilities when a point is added:
  1. Added normally, 
  2. coincides with another vertex and has a higher power, 
  3. is identical to a vertex already present in the tessellation, or 
  4. coincides and has lower power.  

I'd like to be able to tell, for any point, which of these would occur, preferrably without inserting the vertex. 

If I understand correctly, determining which vertices should be hidden/deleted is done within the algorithm, when the regularity of the faces is checked. I want to therefore ask if it's possible to determine this before insertion. If not, then my question is how can one extract the information on which vertices were deleted in case 2 after insertion. I'd like to do this with the `Discard_hidden_points` option [turned on](https://github.com/CGAL/cgal/issues/3186#issuecomment-399432897)
Thank you.

**Comment by MaelRL** [comment]
You can check whether your new point falls on an existing vertex by using the [locate function](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Triangulation__3.html#a280891e681597215a86d63399ae7464c). Distinguishing between the three cases is just a matter of comparing the weights of the weighted points.

If you are not falling on a vertex, you can then use the [find_conflicts function](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Regular__triangulation__3.html#ab039831ea2f961ba9de1cb35ed03f44d) to compute the conflict zone of the point (the set of cells/faces in conflict with the point). If it's empty, the point will be hidden upon insertion.

This is roughly what happens when you call `insert()`.

On a more meta note, for questions about general usage of CGAL rather than doubts about possible bug or unclear doc (like your other issues, which are fine here), you can also use the public mailing lists -- see https://github.com/CGAL/cgal/wiki/Mailing-Lists#public-lists and in particular cgal-discuss. That means more people can benefit from these questions, but also more people can reply to you, whereas here you are likely to only encounter devs.

**Comment by DahnJ** [comment]
@MaelRL thank you, I will direct my questions to the mailing list from now on. To close this issue, can I ask you to clarify how would you go about which vertex (or vertices?) will get deleted in case 2, when the to-be-inserted point forces existing vertices to be deleted? Thank you

**Comment by MaelRL** [comment]
If you look at the iterative insertion algorithm of Bowyer-Watson, the star of the new point is obtained by removing all the cells that are in conflict with a point (which is a contiguous zone) and starring the hole with the new point.

Thus, an existing vertex is going to be hidden if it is strictly within the conflict zone (and not on the border or outside of the zone). So you can check for vertices whose incident cells are all in conflict, using (for example) the function `find_conflict` mentioned above, which computes the cells in conflict for a given weighted point.

**Comment by DahnJ** [comment]
@MaelRL  ha! This actually made it finally click in my mind. It always amazes how fairly complicated geometric properties are naturally encoded in the Delaunay/Regular triangulation structure. 
I implemented it using simply the output `find_conflicts` - conflicting cells and boundary faces and did a set difference on their vertices. Does that approach make sense? I'll close this question now, but I'll definitely be grateful if you confirm. Thanks for your help.

**Comment by MaelRL** [comment]
Yes, that should be equivalent.
