### ISSUE TITLE
AABB_traits does not respect the AABBTraits Concept

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3233]
## Issue Details
- [x] The AABB_traits class uses a class Sort_primitives instead of implementing the three functors 
Split_primitives_along_(x/y/z)_axis. 

- [x] It is also missing the type Intersect, which is called Intersection in the class.
- [x] All functors should be const but it is not documented.

**Comment by lrineau** [comment]
I found the commit 075911ec75eaf66d18e1781842cd45340eb42393, wrote during the review, that says:
> | Author: Camille Wormser <cwormser@inf.ethz.ch>
 >| Date:   Wed May 13 22:35:39 2009 +0000
> | 
> |     Laurent's remark: add the bounding box stuffs

and in the concept `AABBTraits`, the functor `Sort_primitives` was named to the three different functors `Split_primitives_along_x_axis`,  but the change was not done in the code.

One month before, there was that commit, that changed the code:
> * commit 7a340e9d8de4d55bb3ca468657814b6c13051594
> | Author: Laurent Rineau <Laurent.Rineau__CGAL@normalesup.org>
> | Date:   Thu Apr 9 19:50:51 2009 +0000
> | 
> |     Improve the construction time of an AABB_tree for free (by using
> |     std::nth_element, instead of std::sort).

It justifies that the functor cannot be named "sort-primitives" because it does not sort them. So probably that was me asking for the renaming of the functor, but it was only done in the documentation, and not in the code.

My recommendation would be:
- in the doc, use the name `Split_primitives`, that does both the computation of the longest axis, and the splitting,
- and in the code, rename `Sort_primitives` to `Split_primitives`.

**Comment by maxGimeno** [comment]
There is no PR yet, it is in the branch [about transformed aabb traits](https://github.com/maxGimeno/cgal/tree/AABB_tree-AABB_transformed_traits-GF)
