### ISSUE TITLE
Problematic CMake find modules in CGAL installation (e.g., FindGLEW.cmake)

### ISSUE THREAD

**Issue by tadeu** [CGAL/cgal#3317]
## Issue Details

Since CGAL 4.12, after building it with CMake it is installing a lot of extra CMake modules that are not needed, and these are messing the CMake system.

These files are now located in `<install prefix>/lib/cmake/CGAL`, note that the `lib/cmake` directory is shared with CMake, it's where CMake will look for "find" and "config" modules. I think that there's no problem for `CGALConfig.cmake` (and other needed packages) to be there, but there's a bunch of bundled `Find*.cmake` modules that conflict with CMake's own "find" modules.

One example is `FindGLEW.cmake`. CMake already comes with a standard one that will define the `Glew::Glew` target when found. CGAL is installing a `lib/cmake/CGAL/FindGLEW.cmake` file that seems to be an older, non-standard version, and does not define this target. For some reason, CMake seems to sometimes prefer the version from the CGAL subdirectory, and this breaks compilations that rely on the standard find module.

My proposal is to either not install these files, or to install them somewhere else, such as `lib/CGAL/cmake-extra`. In this way, their inclusion would be optional, if they are really needed, the user would add them with a `set(CMAKE_MODULE_PATH ...)` command.

These are all other "Find" modules installed by CGAL:

* FindESBTL.cmake
* FindCORE.cmake
* FindLASLIB.cmake
* FindF2C.cmake
* FindGMPXX.cmake
* FindOpenMesh.cmake
* FindIPE.cmake
* FindRS.cmake
* FindMPFR.cmake
* FindGMP.cmake
* FindMPFI.cmake
* FindRS3.cmake
* FindGLEW.cmake
* FindQGLViewer.cmake
* FindNTL.cmake
* FindEigen3.cmake
* FindLEDA.cmake
* FindTAUCS.cmake
* FindMETIS.cmake
* FindMKL.cmake
* FindLAPACK.cmake
* FindBLAS.cmake
* FindTBB.cmake
* FindSuiteSparse.cmake

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows and Linux
* Release or debug mode: Release
* CGAL version: 4.12
* Boost version: 1.67
* Other libraries versions if used (Eigen, TBB, etc.): CMake 3.11.0

**Comment by lrineau** [comment]
I disagree. Those modules are in a sub-directory of `lib/cmake/`. If `find_package` finds `lib/cmake/CGAL/FindGLEW.cmake`, that means that the CMake script has already appended `lib/cmake/CGAL/` to `CMAKE_MODULES_PATH`, maybe with `include(${CGAL_USE_FILE})`.

@tadeu Please tell us more about the context of the error. A self-contained CMake example would help.

By the way, if your concern is only about `FindGLEW.cmake`, an easy solution would be to remove it from CGAL, because CGAL no longer uses GLEW.

**Comment by tadeu** [comment]
@lrineau, thanks for the quick answer :)

It actually broke the build of an internal codebase that includes a lot of packages, and I didn't take time to create a self-contained example yet, but what I know is that, somehow, CMake is using `FindGLEW.cmake` from the CGAL package instead of the standard one.

Do you think that the following commands in sequence would make CMake use `FindGLEW.cmake` from CGAL?

```
find_package(CGAL REQUIRED)
find_package(GLEW REQUIRED)
```

**Comment by lrineau** [comment]
Actually you are right. If you use the "CGAL header-only" version of `CGALConfig.cmake`, then the `lib/cmake/CGAL/` path is added to `CMAKE_MODULE_PATH` by `CGALConfig.cmake` itself.

Would the removal of `FindGLEW.cmake` from CGAL be sufficient for you?

**Comment by tadeu** [comment]
> Would the removal of FindGLEW.cmake from CGAL be sufficient for you?

Yes, thanks!
Perhaps you'd like to review `FindLAPACK` and `FindBLAS` also, since they are included in CMake.

**Comment by lrineau** [comment]
As far as I know, Blas, Lapack, and TAUCS are no longer supported by CGAL. We could also remove them.
@sloriot @sgiraudot Can you confirm?

**Comment by sloriot** [comment]
I don't think we use them anymore.

**Comment by sgiraudot** [comment]
As far as I know, we still have structures for Lapack (see the [SVD](https://doc.cgal.org/latest/Solver_interface/classCGAL_1_1Lapack__svd.html) model for example), but I don't think they are tested anymore (which is a bad thing). I don't know about the other libraries.

**Comment by lrineau** [comment]
So, what do we do? We will remove our support for GLEW. Do we want also to remove all about BLAS, LAPACK, and TAUCS?

@afabri Do you know any user of one of them, instead of Eigen?

**Comment by afabri** [comment]
We can go ahead.

**Comment by lrineau** [comment]
As for `FindGLEW.cmake`, I have pushed the removal of it in `master`, in f8a37e59ef6b9b9a8ee097a0e924a89b22de0303. For the other module (Blas, Lapack, Taucs), we have to test, first, that they are not used.

**Comment by jdumas** [comment]
Is there a reason `CGALConfig.cmake` is adding anything to the user's `CMAKE_MODULE_PATH`? The content of this variable should be reset to what it was before when returning from a subdirectory, so I'm not sure why there is a pollution of the user's `CMAKE_MODULE_PATH` happening.

**Comment by lrineau** [comment]
[**@jdumas**](https://github.com/jdumas) commented on [Sep 20, 2018, 4:19 AM GMT+2](https://github.com/CGAL/cgal/issues/3317#issuecomment-423017852 "2018-09-20T02:19:06Z - Replied by Github Reply Comments"):
> Is there a reason `CGALConfig.cmake` is adding anything to the user's `CMAKE_MODULE_PATH`? The content of this variable should be reset to what it was before when returning from a subdirectory, so I'm not sure why there is a pollution of the user's `CMAKE_MODULE_PATH` happening.

I am not completely sure it is justified. But it has always been so that, after
```cmake
find_pachage(CGAL)
include(${CGAL_USE_FILE})
```
then you can call, for example, 
```cmake
find_package(ESBTL)
```
and thus call the module `FindEBSTL.cmake` found in the CGAL modules directory. When I create the `CGALConfig.cmake` of CGAL-header-only, I wondered if I had to preserve that. Otherwise the calling script would have to modify the `CMAKE_MODULE_PATH`  on his own, with:
```cmake
list(APPEND CMAKE_MODULE_PATH ${CGAL_MODULES_DIR})
```

Maybe for a future release we should pull back and let the user deal with the `CMAKE_MODULE_PATH`.

**Comment by jdumas** [comment]
Yeah but see, this `include(${CGAL_USE_FILE})` was always polluting the user's CMake script, and this is exactly the kind of side-effect I was happy to avoid with the new CMake script in v4.12. You should be able to pull all the required dependencies through target-based properties. So e.g. if CGAL depends on GLEW, then instead of having the user call `find_package(GLEW)`, he should only `target_link_libraries(mylib PUBLIC CGAL)`. I mean I think this is more or less already the case with GMP, MPFR and Boost right?
If there are other components you need to ship with specific versions (I don't know what is ESBTL), then I'd express them using the `COMPONENTS` in the `find_package(CGAL)` (kind of what you do for `CGAL::Core`). So e.g. if the user wants the ESBTL bundled with CGAL, maybe he can call:
```cmake
find_package(CGAL COMPONENTS ESBTL)
target_link_libraries(mylib CGAL::ESBTL)
```

Or something like this.

Btw can we use CGAL via `add_subdirectory()` now? Maybe it's worth discussing in a different thread, but while the header-only mode is a nice addition, it may be slower to compile and for certain project you'd want to build it alongside your main lib, but compiling what can be compiled in a static/shared lib  beforehand.

**Comment by lrineau** [comment]
I consider this bug as closed, because `FindGLEW.cmake` was removed.

The question of BLAS/LAPACK/TAUCS will be in #3739.
