### ISSUE TITLE
Polyhedron demo, plugins load error: cannot load library

### ISSUE THREAD

**Issue by liang-god** [CGAL/cgal#3333]
![image](https://user-images.githubusercontent.com/29827175/45534017-35791680-b82c-11e8-943e-3e245ebe7371.png)

so weird !  because i'm sure these paths are no problem!   

and these library are generate at the same time!

some success ,some fail......

**Comment by lrineau** [comment]
The failure is because the `.dll` depend at runtime on other DLLs, like the DLLs of CGAL, Boost... and those dependencies are not in the list of directories pointed by the environment variable `PATH`.

There is a tool, named `depends.exe`, in the Visual Studio. It can help you find out what is missing.

**Comment by liang-god** [comment]
thank you very much! 
I forgot changing the path of environment variables,
