### ISSUE TITLE
Feature Proposition: loading a "scene" in Polyhedron demo

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#3340]
## Issue Details

I thought about a feature that would be useful for me and maybe for other people: being able to write/load full "scenes" in the Polyhedron demo. By "scene", I mean a set of items (of potentially different types) with some additional informations (color, rendering mode, etc.).

What I have in mind is a text file that just refers to other files, similarly to a M3U playlist that refers to existing music files. One example could be:

```
~/data/my_mesh.off surface_mesh_io_plugin "Mesh Faces" #FF0000 Flat Visible
~/data/aux/edges.polylines.txt "Meta-Edges" polylines_io_plugin #000000 FlatPlusEdges Visible
../debug/something.ply ply_plugin "Debug Points" #00FF00 ShadedPoints Hidden
```

_(Maybe using a standard file format such as XML or Json could make sense.)_

In that case, I assume that each line contains the path to the file, the plugin to use to open it, the name of the item, the color of the item, the rendering mode and the view mode (but it's just an example, it could be different). When I load this file, it automatically loads all the files listed and sets up the property as defined (if the file doesn't exist or the IO plugin to use is not available, an error should be displayed - again, similarly to a M3U file that would refer a non-existent MP3 file).

Being able to load something like that would allow to easily recover an exact same scene (instead of loading items one by one and resetting the properties the way we want). To save such a file, one option would be to make a special IO plugin that is triggered when hitting "Save" when several items are selected: the problem in that case is that it might get complicated afterwards (= does the user need to select each IO plugin for each item and assign a name to them? Or is it done automatically using the default IO plugin for each type?).

That might be an overly complicated feature for a small added value, so this is not exactly a feature _request_, just something I thought about and that I wanted to write down in order not to forget it. Feel free to comment and tell me what you think about it.

**Comment by lrineau** [comment]
Indeed, I think a Javascript file could does all that:
  - loading file,
  - change names, colors, and rending modes of items.

The only thing I am not sure of is the item groups, everything works with Qt slots, and the only API accessible with Qt Scripts are the slots.

Here is an example of such a script, quite complicated: https://gist.github.com/ca06ff7396b257237f2cfd8426f6f1ea

It used to work. I am not sure the functionality has survived all the refactoring.

One of the worst thing is slot functions that pop dialogs, instead of doing the job without asking questions.

**Comment by lrineau** [comment]
This one is funny: it register a connection, so that a function is called as soon as an item is added to the scene: https://gist.github.com/ec66d09b0e3e87127d650d69dfeb1e2f

And I also used to have [an `autostart.js`](https://gist.github.com/4afe122c6459f5f64f92d08bfd31588f), that created three menus items:
  - pass all items to flat mode,
  - pass all items to wireframe mode,
  - and a "save all" action, that saved all the items of the scene to `/tmp/`.
