### ISSUE TITLE
Issue with Straight Skeleton due to two extremely close points

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3382]
Originally reported on cgal-discuss

[ss.zip](https://github.com/CGAL/cgal/files/2454897/ss.zip)

**Comment by sloriot** [comment]
With `EPECK_with_sqrt` it terminates but it is slow.

**Comment by afabri** [comment]
@sloriot can you please give a link to the original post.

**Comment by sloriot** [comment]
https://sympa.inria.fr/sympa/arc/cgal-discuss/2013-07/msg00001.html

**Comment by afabri** [comment]
ERROR (arc) - Authorization rejected. Maybe you forgot to log in?

**Comment by sloriot** [comment]
log into sympa

**Comment by lrineau** [comment]
You have to log in to see the Sympa archives.

The message is also on Nabble: http://cgal-discuss.949826.n4.nabble.com/Straight-Skeleton-Crash-td4657737.html

**Comment by MaelRL** [comment]
Can't reproduce the crash using the branch from #4905. Results are surprising and counter-intuitive, but valid:

The result with `EPECK_with_SQRT` is:

![faux_2](https://user-images.githubusercontent.com/5074170/91965126-5a643e00-ed10-11ea-9881-b3a6d5826a90.png)

At first it looked wrong: I expected a horizontal bisector to be spawned by the vertex event (i.e. the collapse in a single point of two reflex vertices). However, this is not actually a vertex event, because the two reflex vertices do not meet:

Zoom on the red square:
![zoom](https://user-images.githubusercontent.com/5074170/91964970-1e30dd80-ed10-11ea-94d8-96e11f9d1ac8.png)

Zoom on the green square:
![zoom2](https://user-images.githubusercontent.com/5074170/91964976-20933780-ed10-11ea-889e-0c618f212a74.png)

Even more surprising, when using `Simple_cartesian<Gmpq>` instead of `EPECK_with_sqrt`, one gets a different result, with the other reflex vertex passing first (one collinear vertex has been removed, but it's irrelevant):

![funk](https://user-images.githubusercontent.com/5074170/91965277-8b447300-ed10-11ea-87de-01d7dd1804b5.png)

But this is normal because square roots are computed differently. Therefore, we get another valid skeleton structure, despite not being the true result.

Finally, all of these used exact inputs and exact number types. If you embed the result back into a `double`-based world, the structure becomes degenerate. If you convert the input to double, you get another type of weird (but valid) result:

![faux_epick](https://user-images.githubusercontent.com/5074170/91965642-10c82300-ed11-11ea-8340-6807d84c8bd7.jpg)

(Once again, zooming will show a very degenerate face and not a valence 2 vertex.)
