### ISSUE TITLE
Incorrect HTML output

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3456]
## Issue Details

In the own defined html header for the documentation lines the `link` tag for the project logo is not closed (at the moment no directly a problem as HTML is quite tolerant, but future default standards (like xhmtl) might / will give errors. The problem has been observed with the current master version.

The following lines give problems:

```
./Documentation/doc/resources/1.8.13/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
./Documentation/doc/resources/1.8.13/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
./Documentation/doc/resources/1.8.14/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
./Documentation/doc/resources/1.8.14/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
./Documentation/doc/resources/1.8.4/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
./Documentation/doc/resources/1.8.4/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png">
```

They should read:

```
./Documentation/doc/resources/1.8.13/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
./Documentation/doc/resources/1.8.13/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
./Documentation/doc/resources/1.8.14/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
./Documentation/doc/resources/1.8.14/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
./Documentation/doc/resources/1.8.4/header.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
./Documentation/doc/resources/1.8.4/header_package.html:<link rel="icon" type="image/png" href="$relpath$../Manual/g-196x196-doc.png"/>
```

So with a `/` before the closing `>`

**Comment by lrineau** [comment]
I agree. I have surprised because I do not see the issue in our precompiled documentation, for [4.13 on the web site](https://doc.cgal.org/4.13/) or [`master`](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/index.html). They both have a correctly closed tag:
```html
<link rel="icon" type="image/png" href="../Manual/g-196x196-doc.png" />
```

I agree that the `header.html` files in our resources is incorrect, but I do not understand why it got fixed in the way during the documentation generation.

Our documentation is processed by the script `Documentation/doc/scripts/html_output_post_processing.py`, that uses `PyQuery`, and probably that tool "fixes" the produced HTML.

@sloriot, what do you think? Let's just add the closing ` />` (the space before is important, if I remember well).
