### ISSUE TITLE
Illegal use of std::setprecision

### ISSUE THREAD

**Issue by ysyrov** [CGAL/cgal#3606]
https://github.com/CGAL/cgal/blob/daa1493e984a61e0d221b54a4dd97fec6db0a3d9/CGAL_Core/include/CGAL/CORE/CoreDefs.h#L325

in STL it's iomanip and not a global function, therefore return value cannot be ignored and must be used in stream. I don't know where and how it worked as intended, but it goes against standard

**Comment by lrineau** [comment]
The bug was introduced 14 years ago, by 3a57cc0bc33. Before that, the code was:
https://github.com/CGAL/cgal/blob/3a57cc0bc33e582882479a4f4d36557f74e5ad43/Packages/Core/include/CORE/CoreDefs.h#L236-L240

But, actually, I wonder if that is a good practice to modify the settings of `std::cout` globally, and behind the back of users. Should not I/O functions of CGAL_Core modify that setting on the fly, and then restore the previous value?

**Comment by afabri** [comment]
As @ysyrov pointed out the `std::setprecision()` function has no effect an any stream, so we can simply remove the line.  In order to have an effect the object returned by the function must be inserted in a stream with `operator<<()`.
