### ISSUE TITLE
Mesh_3 plugin: mesh the cube.off without the sharp features crashes

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3638]
## Issue Details

Polyhedron demo, from master (1ca9dbc514a4de9b214d2a6270a4b3294381948f), with the mesh_3_plug. Open the cube.off, then "Create a tetrahedral mesh", and **uncheck the sharp features protection**.
![screenshot_20190129_115544](https://user-images.githubusercontent.com/5746675/51903580-d243e700-23bc-11e9-9458-f7eb4d5e03a0.png)

The plugin crashes as soon as the progress dialog pops up.

If you can  find the solution and fix it before 4pm, that would be a plus for me.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Ubuntu 18.09
* Compiler: g++
* Release or debug mode: both

**Comment by MaelRL** [comment]
For the record, since I have communicated it to @lrineau already: the issue is in the initialization (or rather, the lack of initialization) of a property map, `face_patch_ids`, when `detect_features()` is not called.

Can be reproduced in `mesh_polyhedral_domain_with_features.cpp`, using a `Surface_mesh` and commenting the call to `detect_features()`.

**Comment by lrineau** [comment]
Fixed by #3647.
