### ISSUE TITLE
CMake more than one file usage

### ISSUE THREAD

**Issue by shmel1k** [CGAL/cgal#3672]
## Issue Details

CGAL does not compile if I use more than one file(for class definition for example)
I know, that the problem is in the `create_single_source_cgal_program`, but is there any function like that that allowes to build large projects with CGAL support?
## Source Code
```cmake
project( hexagon_union )

cmake_minimum_required(VERSION 2.8.10)

find_package(CGAL QUIET COMPONENTS Core )

set(EXECUTABLE_OUTPUT_PATH "bin")

add_executable(hexagon_union
    src/union/unioner/unioner.cpp
    src/union/main.cpp
)

target_include_directories(hexagon_union
    PRIVATE
        ${PROJECT_SOURCE_DIR}/src/union)

if ( CGAL_FOUND )

  include( ${CGAL_USE_FILE} )

  include( CGAL_CreateSingleSourceCGALProgram )

  create_single_source_cgal_program("src/union/main.cpp")
else()
    message(STATUS "This program requires the CGAL library, and will not be compiled.")
endif()
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bits
* Compiler: gcc 5.3
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: -

**Comment by lrineau** [comment]
Try the following:
```cmake
project( hexagon_union )

cmake_minimum_required(VERSION 3.1)

find_package(CGAL REQUIRED)

set(EXECUTABLE_OUTPUT_PATH "bin")

add_executable(hexagon_union
    src/union/unioner/unioner.cpp
    src/union/main.cpp
)

target_include_directories(hexagon_union
    PRIVATE
        ${PROJECT_SOURCE_DIR}/src/union)

target_link_libraries(hexagon_union CGAL::CGAL)
```

I have changed:
  - the `cmake_minimum_required` version, because now CGAL requires CMake>=3.1
  - `find_package(CGAL REQUIRED)`: without `CGAL_Core`, because I doubt you need it.
  - I have used `REQUIRED` in `find_package` to have an explicit error, instead of a soft failure.
  - I have used `target_link_libraries` with the imported target `CGAL::CGAL`, instead of the old use of `include( ${CGAL_USE_FILE} )`.

There exists a prototype documentation about how to use modern CMake syntax, with CGAL: https://github.com/CGAL/cgal/wiki/How-to-use-CGAL-with-CMake-or-your-own-build-system

**Comment by shmel1k** [comment]
thanks a lot, that helped :)
