### ISSUE TITLE
(X)HTML warning after documentation post processing (details)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3754]
## Issue Details

During the post processing phase of `make doc_with_postprocessing`  (X)HTML anchors of the form `<a name="details" id="details"></a>` are added to the documentation of a `class*.html` or `struct*.html` file if the file contains the string `<p>Inherits\s*(.*)</p>`.  This is done in the file `Documentation/doc/scripts/html_output_post_processing.py`
This can lead to warning messages like:
```
 element a: validity error : ID details already defined
<a name="details" id="details"></a><h2 class="groupheader">Definition</h2>
                              ^
ID details already defined
```

Suggestion, replace the code:
```
    for fn in class_and_struct_files:
        re_replace_first_in_file(r'<p>Inherits\s*(.*)</p>', r'<a name="details" id="details"></a><h2 class="groupheader">Inherits from</h2><p>\1</p>', fn)
```
in `Documentation/doc/scripts/html_output_post_processing.py` by, in pseudo code:
```
    for fn in class_and_struct_files:
        if in the file fn the string r'<a name="details" id="details"></a>' exists:
          re_replace_first_in_file(r'<a name="details" id="details"></a>','',fn) # only first is necessary as an id can only occur once.
        re_replace_first_in_file(r'<p>Inherits\s*(.*)</p>', r'<a name="details" id="details"></a><h2 class="groupheader">Inherits from</h2><p>\1</p>', fn)
```

**Comment by sloriot** [comment]
Do you think that's something we could push upstream in doxygen directly to avoid that postprocessing?

**Comment by albert-github** [comment]
I don't get the question.

CGAL inserts the tag with the ids as indicated, but as far as I can see they don't have any effect and can be taken out of the CGAL postprocessing.
The doxygen generation is already completed and the messages come from a (X)HTML testing tool (xmllint).

**Comment by sloriot** [comment]
I wanted to ask if we should propose a patch to doxygen to have
this behavior:
![Screenshot from 2019-03-15 09-40-41](https://user-images.githubusercontent.com/1224632/54418983-a8dde100-4706-11e9-9bd5-324d765eb6c5.png)
instead of:
![Screenshot from 2019-03-15 09-40-53](https://user-images.githubusercontent.com/1224632/54418984-a8dde100-4706-11e9-8193-b4d881c9d2b4.png)
but I realized that we should also do it for inherited.

**Comment by albert-github** [comment]
You can make an enhancement issue for doxygen so Dimitri can decide about it.
I think when then the "Inherits From" sould still read "Inherits"

**Comment by lrineau** [comment]
As @albert-github found, this bug is due to these lines in CGAL:
https://github.com/CGAL/cgal/blob/9d3b16edf4446f9ed2903a559064242bcb919837/Documentation/doc/scripts/html_output_post_processing.py#L365-L366

For each class, Doxygen already sets a link with the name and id `details`, and that is a link pointing to the `Definition` header. That is an error to add another link with the same name and id. The simplest patch is:
```patch
index 1fd9d444db3..1e984b769bc 100755
--- a/Documentation/doc/scripts/html_output_post_processing.py
+++ b/Documentation/doc/scripts/html_output_post_processing.py
@@ -363,7 +363,7 @@ removes some unneeded files, and performs minor repair on some glitches.''')
     class_and_struct_files=list(package_glob('./*/class*.html'))
     class_and_struct_files.extend(package_glob('./*/struct*.html'))
     for fn in class_and_struct_files:
-        re_replace_first_in_file(r'<p>Inherits\s*(.*)</p>', r'<a name="details" id="details"></a><h2 class="groupheader">Inherits from</h2><p>\1</p>', fn)
+        re_replace_first_in_file(r'<p>Inherits\s*(.*)</p>', r'<h2 class="groupheader">Inherits from</h2><p>\1</p>', fn)
 
     # remove class name in Definition section if there is no default template
     # parameter documented
```
