### ISSUE TITLE
Add clean polygon soup in the demo

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3839]
even the non-documented internal intermediate functions would be useful to have (maybe a submenu)

**Comment by MaelRL** [comment]
Would be useful to have polygon soup statistics too, please.

**Comment by maxGimeno** [comment]
Can yo ugive me a list of information you want in the statistics ?

**Comment by afabri** [comment]
> 
> 
> Can yo ugive me a list of information you want in the statistics ?

I guess everything like for a mesh that also makes sense for a triangle soup:  edge length, angle, degenerate ......

**Comment by afabri** [comment]
@maxGimeno is there a mixup?  The title and the discussion seem not to be related.

**Comment by maxGimeno** [comment]
No. The issue was initially about adding a new action to the demo, which has been done in the multi viewer branch, and then I was asked to add statistics to the soup_item in the same issue, which I only did after the multi viewer was integrated, so I made a branch. The said branch addresses the second part of the issue, therefore I flagged it as fixing it.

**Comment by lrineau** [comment]
I reopen the issue, because #3872 has only added the statistics, and not the cleanup functions.

**Comment by maxGimeno** [comment]
The clean-up functions are already in master.
