### ISSUE TITLE
Cannot compute even a simple ray/segment intersection

### ISSUE THREAD

**Issue by wucm1994** [CGAL/cgal#3926]
_Please use the following template to help us solving your issue._

## Issue Details

Hey! I am using CGAL to conduct some research works. I'm trying to compute the intersection between a Ray_2 and a Segment_2, but it cannot produce correct results.

## Source Code

```
Point_2 st(6.012429289, 199.3673653);
auto r = Ray_2(st, Vector_2(0.7071067812, 0.7071067812));
auto s = Segment_2(Point_2(7.6, 508), Point_2(7.6, 0));
auto k = CGAL::intersection(r,s);
if (k)
{

	if (const Point_2 * ipoint = boost::get<Point_2>(&*k))
	{
		std::cerr << *ipoint << std::endl;
	}
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Win 10 64 bit
* Compiler: VS 2019
* Release or debug mode: Both
* Specific flags used (if any): No
* CGAL version: 4.14
* Boost version: 1.67
* Other libraries versions if used (Eigen, TBB, etc.): No

**Comment by wucm1994** [comment]
When I normalize the `dir`, it works.

**Comment by MaelRL** [comment]
Which kernel are you using?

**Comment by wucm1994** [comment]
I'm using `CGAL::typedef CGAL::Exact_predicates_inexact_constructions_kernel` kernel to to this work.

**Comment by wucm1994** [comment]
Actually, normalizing `dir` doesn't work well when I integrated it into my project. But it works in a standalone project.

**Comment by MaelRL** [comment]
You are using an inexact construction kernel and thus your construction is... well, inexact. Internally, the code checks if the construction makes sense: it checks if the intersection is on the segment and on the ray (using exact predicates). If this is not the case, it returns nothing, which is what you get. This is thus expected behavior.

What you can do is to switch to an exact construction kernel when the inexact construction kernel fails. It would look roughly like:

```
If CGAL::do_intersect(r,s))
  Try to build the inexact intersection
  If the inexact intersection construction failed
    Convert r,s to an exact construction kernel
    Construct the exact intersection
    Convert back the exactly-computed intersection back to your first kernel
  Endif
  Return the inexact intersection
Endif
```

You can see an example of such code in [this file](https://github.com/CGAL/cgal/blob/master/Triangulation_3/include/CGAL/Robust_weighted_circumcenter_filtered_traits_3.h#L230): we try to compute a circumcenter with an inexact kernel, and if the construction fails or does not make sense, an exact construction is used.
