### ISSUE TITLE
clean/improve https://doc.cgal.org/latest/Manual/installation.html and related pages.

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4015]
Could be a good time to clean/improve https://doc.cgal.org/latest/Manual/installation.html and related pages.

Maybe the changelog could point to a small news entry on the website that explains clearly the two different modes and why the new default one is better?

_Originally posted by @MaelRL in https://github.com/CGAL/cgal/pull/3900#issuecomment-499025212_

**Comment by lrineau** [comment]
@MaelRL @MoniqueTeillaud @afabri

I want to discuss about the installation manual.

Here is its current state: https://doc.cgal.org/4.14/Manual/installation.html

My first proposal is to remove that big [section 15 *Summary of CGAL's Configuration Variables*][s15], as well as the smaller sections:
  -  [14.4 *Custom Flags in the Programs Using CGAL*][s14.4],
  - [16 *Compiler Workarounds*][s16], and
  - [17 *Compiler Optimizations*][s17].

[s14.4]: https://doc.cgal.org/latest/Manual/installation.html#title46
[s15]: https://doc.cgal.org/4.14/Manual/installation.html#title47
[s16]: https://doc.cgal.org/4.14/Manual/installation.html#title64
[s17]: https://doc.cgal.org/4.14/Manual/installation.html#title65

And then reorganize the whole manual.

-----

The first idea I want to convey is that CGAL is a header-only library, with two binary dependencies: GMP and MPFR.

And then introduce:
  - our use of CMake to configure programs using CMake,
  - the optional dependencies for some of the examples and demos shipped with CGAL,
  - explain that CGAL one can configure CGAL with all shipped examples, and demos at once, with `cmake -DWITH_examples=ON -DWITH_demos=ON`,
  - explain that one can even "install" CGAL.

Comments?

**Comment by lrineau** [comment]
> The first idea I want to convey is that CGAL is a header-only library, with two binary dependencies: GMP and MPFR.

The important subtext of that idea is that there is no need to "install" CGAL.

**Comment by MaelRL** [comment]
Here are some things I had in mind; it's more or less what you are saying, I suppose.

- The page is called "Installation", which is not optimal if you want to convey there's no need to install.
- Rename that page "Usage" (or something like that), and split this endless abyss into multiple pages:
  - Start with the prerequisite note (Sec 2) which points to a new "Downloading CGAL" page (which regroups Section 3-4-5, package managers download, download, supported compilers)
  - Now the simplest "Usage" (Sec 1) comes.
  - Section 6 and 7 afterwards, although they seem a bit technical and probably would need to be improved.
  - Say something about the possibility of Installation --> everything about Installation is in an 'Installation' page
  - Third party libraries gets its own page (prob. leave some stuff about the most important ones on the main page)
  - New page for CGAL configuration variables (if it's not just dropped)
  - Drop the last two sections

**Comment by MoniqueTeillaud** [comment]
Hi 
I am travelling right now, I am sorry I cannot work on this. I'll be happy to give comments later in July. 
Best, 
-- 
Monique Teillaud 
https://members.loria.fr/Monique.Teillaud/ 
INRIA Nancy - Grand Est, LORIA 
Institut National de Recherche en Informatique et Automatique

**Comment by MaelRL** [comment]
I have done a rough re-organization (still WIP) and hosted it at https://cgal.geometryfactory.com/~mrouxell/Manual-5.0/Manual/general_intro.html, if you have any comment.

**Comment by MoniqueTeillaud** [comment]
Thank you for this new version. I fully support the intent to introduce the 'header-only mode' as the most standard way to use CGAL.

Disclaimer: I suspect that I have grossly missed something, so, I stopped reading when I felt too lost. I hope that, reading my comments, you can guess what I missed and why I got lost at some point. 

Organization. 
Showing "Installation" on the main menu (left column, down), i.e. in such a prominent place, is misleading. Users might just directly click there and miss the header-only section.
Wouldn't it make sense to structure the chapter as folows?
(btw, I don't quite understand what a section named "usage" is supposed to be about...)
1 Quick Start
2 Prerequisites
3 Downloading CGAL
4 Header-only Usage
   4.1 Configuring and Building Programs Using CGAL
   4.2 (? I don't uderstand that section at all, see below) Configuring CGAL with CMake
   4.3 (here?) Multiple Variants of Makefiles (out-of-source build)
5 Installing CGAL
   first clearly say that this section is meant only for users who have a good reason not to use the header-only mode 
   then this section would include the whole text that is currently here:
   https://cgal.geometryfactory.com/~mrouxell/Manual-5.0/Manual/installation.html
6 Organization of the Manual
7 Preliminaries
8 Essential and Optional Third Party

Section 1
good teaser!
- demos are mentioned already in "Quick start". Is it really the first thing to mention? I would suggest to mention the basic viewer instead (which should have a dedicated chapter in the manual in "Support library", but that's another story...)

Section 2 links to dependencies. Qt5 is listed as an _Essential_ third party library, whereas it is necessary for demos only. It looks like an overkill to 'force' users to install qt if they don't need demos. 

Section 3:
- (in table) "auxiliary | precompiled Gmp and Mpfr for Windows" is confusing --> write "auxiliary (Windows only) | precompiled Gmp and Mpfr"
- "config | configuration files for install script" --> which installation is this about? only the header-only version has been mentioned so far 
- on all the download webpages in https://www.cgal.org/download.html the link "download an installer or tarball " should lead to the latest public relase instead of the most recent bugfix release of an older release

Section 4.1
"Gmp and Mpfr, for example, are not header-only." --> tell the user what she can do. 

Section 5
- I would move the paragraph about CGAL_DIR up to Section 4, where it is introduced.
- typo "several CMake variable" missing S
- "If you have installed CGAL" etc (2 sentences) --> all this is about header-only, right? so I don't understand. 
- It is a bit strange to have a subsection 5.1 but no 5.2. 
5.1
- "non-shipped program" --> refer to shipping with CGAL
- "Bourne-shell script" does it add anything to mention Bourne? isn't it the common kind?
- typo "for compiling CGAL applications" missing dot at the end of the sentence

Section 6
- starts with "Before building anything using CGAL"
Now, I don't understand the whole organization of the chapter. Section 5 was precisely about buidling someting using CGAL. It would be good if users could just do things in order, while reading these guidelines.  If a user has failed building an example when reading section 5, because they have (of course) not read section 6, they will give up and won't even go further. 
- section 6.1 "Configuring CGAL". Again I am lost. It was explained earlier (sec 4) that we don't need to configure CGAL...
- typo "what shall gets generated"

Random 
https://cgal.geometryfactory.com/~mrouxell/Manual-5.0/Manual/preliminaries.html#Preliminaries_cc0x
soon outdated as 5.0 switches to C++14

**Comment by MaelRL** [comment]
Also to change:
- https://github.com/CGAL/cgal/blob/master/INSTALL.md
- cgal.org pages (FAQ, Download)

**Comment by MaelRL** [comment]
[Here](https://cgal.geometryfactory.com/~mrouxell/Manual-5.0-v2/Manual/index.html) is a large update over the previous upload (takes into account remarks from @MoniqueTeillaud, a few things discussed at the meeting, and more changes).

Also modified / trimmed (too much?) the markdown files:
- https://github.com/MaelRL/cgal/blob/CGAL-Header_only_doc_rewrite-GF/README.md (shown on github's front page)
- https://github.com/MaelRL/cgal/blob/CGAL-Header_only_doc_rewrite-GF/INSTALL.md (installation for git-based cgal)
- https://github.com/MaelRL/cgal/blob/CGAL-Header_only_doc_rewrite-GF/Installation/INSTALL.md (installation for tarball cgal)

There are a few more red boxes to solve, Windows is a bit ignored, and there are some more TODOs (see above), but I would like to get feedback, please.

**Comment by MaelRL** [comment]
> Here is a large update over the previous upload (takes into account remarks from @MoniqueTeillaud, a few things discussed at the meeting, and more changes).
> 
> Also modified / trimmed (too much?) the markdown files:
> 
>     MaelRL/cgal:README.md@CGAL-Header_only_doc_rewrite-GF 
> 
> (shown on github's front page)
> MaelRL/cgal:INSTALL.md@CGAL-Header_only_doc_rewrite-GF
> (installation for git-based cgal)
> MaelRL/cgal:Installation/INSTALL.md@CGAL-Header_only_doc_rewrite-GF
> 
>     (installation for tarball cgal)
> 
> There are a few more red boxes to solve, Windows is a bit ignored, and there are some more TODOs (see above), but I would like to get feedback, please.

bump

**Comment by sloriot** [comment]
Together with @afabri, we checked and updated @MaelRL 's branch.

**Comment by MaelRL** [comment]
Latest version cgal.geometryfactory.com/~mrouxell/Manual-5.0-v3/Manual/index.html

**Comment by MaelRL** [comment]
With the last update (3f62323), I updated the main page so that it is consistent with package managers being the recommended way of obtaining CGAL.

Rather than creating various packages for examples (which might not even be possible, e.g. for VCPKG), I assume that users will download an example tarball somewhere.
