### ISSUE TITLE
Improving CHANGES.md user friendliness

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4031]
I feel like the `CHANGES.md` log is not as user-friendly as it could be.
- The entries could point to the pull request that introduced them, as to add more context. This could be restricted to small pull requests, with larger features pointing to whichever news entry are associated to them directly.
- There could be more links to the documentation: it's tedious to have to go to the documentation to then search the name of the new function to see what's being added. Here it is a little bit tricky because the documentation is not yet up to date when the PR is merged, so this could simply be done post-release, or limited to the website.

Any thoughts?

(@CGAL/geometryfactory)

**Comment by lrineau** [comment]
I certainly agree with those suggestions. I wonder how we can enforce that.

**Comment by MaelRL** [comment]
I could do it by hand for this release, once things are relatively stable? This would serve as a proof of concept.

**Comment by MaelRL** [comment]
I tried different ways in https://github.com/MaelRL/cgal/blob/master/Installation/CHANGES.md. Links use "doc/master" but it'd be "doc/release.x.y/"

Feedback appreciated!

**Comment by danston** [comment]
I completely support these changes. I think, the new readme looks much more appealing. A few comments:

* Title link (e.g. 2D Triangulations): what about having it to the Reference manual instead of the position in the list of the  packages? What was the reason behind this decision?
* Regarding the style of PR links: I prefer [{Pull Request #3950}](url) or [{PR #3950}](url). I think it well separates PRs from the main text and easy to understand.
* I also like that there is a link in the functions like [CGAL::read_ply()](url). It is much more convenient.
* What about adding a link to the corresponding version in the release page: https://github.com/CGAL/cgal/releases under or near Release 5.0?
* The readme description btw is slightly different from the one in the Releases page. E.g. there is no (new package) tag in the readme version. Should we maybe unify them?

**Comment by MaelRL** [comment]
Pushed some updates (still on my [master branch](https://github.com/MaelRL/cgal/blob/master/Installation/CHANGES.md)) where I have cleaned, re-ordered, and added links to the current `CHANGES.md`.

**Comment by MaelRL** [comment]
Changes integrated in 92e5b71e4d250a12c315be36833bdebd2b8a22d8.

Nothing automatic planed (not worth the time to invest, just do it manually every time). Removing superfluous markdown can be done with https://pandoc.org/.
