### ISSUE TITLE
Shape_detection: assigned indices are the shuffled indices?

### ISSUE THREAD

**Issue by waschbaer00** [CGAL/cgal#4115]
![spreadout](https://user-images.githubusercontent.com/20991349/61945022-4a235080-af9f-11e9-9c9f-8cbd9f59f762.jpg)

## Issue Details

I retrieve the indices assigned to each shape, turns out that the indices for each shape is actually spread out the whole points set, from this point I guess the retrieved indices are actually reordered due to the shuffled points. 

My points sets is a clean data, consists only primitive shapes, no noise at all. So such spreading should really not happens.

## Source Code

```

    Efficient_ransac ransac;
    ransac.set_input(points);
    ransac.add_shape_factory<Plane>();
    ransac.add_shape_factory<Sphere>();
    ransac.add_shape_factory<Cylinder>();
    ransac.add_shape_factory<Cone>();
    ransac.preprocess();
 
  Efficient_ransac::Parameters parameters;
  parameters.epsilon = 0.05;
  parameters.normal_threshold = std::cos(10. * M_PI / 180.);

  Efficient_ransac::Shape_range shapes = ransac.shapes();
  FT best_coverage = 0;
  for (size_t i = 0; i < 3; i++) {
    ransac.detect(parameters);
    FT coverage = FT(points.size() - ransac.number_of_unassigned_points()) / FT(points.size());

    // Choose result with highest coverage.
    if (coverage > best_coverage) {
      best_coverage = coverage;
      shapes = ransac.shapes();
    }
  }
  std::vector<size_t> indices;

  for (Efficient_ransac::Shape_range::iterator it = shapes.begin(); it != shapes.end(); it++) {
    if (Cylinder* cyl = dynamic_cast<Cylinder*>(it->get()))
    {
      indices = cyl->indices_of_assigned_points();
    }
    else
    {
      std::cout << (*it)->info() << std::endl;
    }
  }

```
## Environment

* Linux
* Release 
* CGAL version: 4.14

**Comment by danston** [comment]
Hi @waschbaer00 When you get your indices for a cylinder in the example above, do they actually form a cylindric shape? If they do, what is the problem? If they do not, it is probably due to the chosen parameters, the algorithm simply fails to detect a cylinder for the given set of parameters. Could you please clarify? Thanks.

**Comment by waschbaer00** [comment]
> Hi @waschbaer00 When you get your indices for a cylinder in the example above, do they actually form a cylindric shape? If they do, what is the problem? If they do not, it is probably due to the chosen parameters, the algorithm simply fails to detect a cylinder for the given set of parameters. Could you please clarify? Thanks.

We just use the default parameters, as the authors did in Supervised Fitting of Geometric Primitives to 3D Point Clouds.

> We compare the performance of SPFN with Efficient RANSAC and also hybrid versions where we bring in predictions from neural networks as RANSAC input. We use the CGAL implementation of Efficient RANSAC with its default adaptive algorithm parameters.

**Comment by danston** [comment]
A few remarks:

* I am not familiar with the cited paper, so I do not know the details on what exactly the authors are doing there, but the first question that arises is do you have the same data sets as they do? If they are the same, then you should get the same results as the authors if you call the algorithm the same way as they do. If this is the case, maybe the authors have been fully fine with spreading indices or did not pay any special attention to this fact. If your data sets are different, then as I wrote before, the default adaptive parameters may be a bad choice for your data set. They could be a good choice for the authors data, but not for yours.

* In general, RANSAC method is the method that does depend on 5 parameters, 4 of which are actually very important for the correct shape detection. The default parameters are provided only as a starting point for the user and in most cases they should be adjusted. However, indeed, sometimes, it is not necessary, because these initial values are already good enough. See [here](https://doc.cgal.org/latest/Point_set_shape_detection_3/structCGAL_1_1Shape__detection__3_1_1Efficient__RANSAC_1_1Parameters.html) on how they are actually computed.

* What does it mean the shape tells you? If you just visualize points for the given vector of indices, do you see a cylinder? In the picture above, there are multiple colors and it is not even clear if this is one point cloud or multiple point clouds, what do the color mean, etc.

**Comment by waschbaer00** [comment]
> A few remarks:
> 
> * I am not familiar with the cited paper, so I do not know the details on what exactly the authors are doing there, but the first question that arises is do you have the same data sets as they do? If they are the same, then you should get the same results as the authors if you call the algorithm the same way as they do. If this is the case, maybe the authors have been fully fine with spreading indices or did not pay any special attention to this fact. If your data sets are different, then as I wrote before, the default adaptive parameters may be a bad choice for your data set. They could be a good choice for the authors data, but not for yours.
> * In general, RANSAC method is the method that does depend on 5 parameters, 4 of which are actually very important for the correct shape detection. The default parameters are provided only as a starting point for the user and in most cases they should be adjusted. However, indeed, sometimes, it is not necessary, because these initial values are already good enough. See [here](https://doc.cgal.org/latest/Point_set_shape_detection_3/structCGAL_1_1Shape__detection__3_1_1Efficient__RANSAC_1_1Parameters.html) on how they are actually computed.
> * What does it mean the shape tells you? If you just visualize points for the given vector of indices, do you see a cylinder? In the picture above, there are multiple colors and it is not even clear if this is one point cloud or multiple point clouds, what do the color mean, etc.

I am sorry I made my issue not understandble. 

1. It is the same dataset. Therefore I use the same default params.
2. In total there are 4 cylinders and 2 cones are detected on the shape, but if I visualize each cluster with the assigned indices, they all spread out on the whole shape. Therefore, I ask is that possible the assigned indices is shuffled during preprocessing? Because even the detection is not proper due to wrong parameters, the assigned incides should not be so uniformly spread out everywhere right? You can see how "uniform" they are spread out from these two images.

![cyl1](https://user-images.githubusercontent.com/20991349/62290262-383f2300-b461-11e9-998f-d42e4b31957a.png)
![cyl2](https://user-images.githubusercontent.com/20991349/62290264-383f2300-b461-11e9-8ae7-9eb0e52b7ec1.png)

**Comment by danston** [comment]
Ok, great. Now it is clear. You do have the same data sets and the results have cylindric shapes. 

Now back to the original question. I am not an author of the original package so I do not know all implementation details, but if you read the paper on Efficient RANSAC, the idea is to choose a random subset of points from the whole input and try to fit a shape to this subset. If the fitting is good, assign these points to a shape, otherwise no. 

The whole thing means that points, however they are chosen, can be picked from various parts of the point cloud **in a random fashion**. Then, if the user parameters fit to this choice, the points are assigned to the shape in exactly the same random order.  So the shuffling (if I understood correctly what you mean) is the case by the nature of the algorithm. 

And since you have two cylindric shapes while it is supposed to be only one, it means that parameters are bad. Try to adjust the epsilon parameter by making it bigger. I expect these two shapes to be merged at some point.

**Comment by danston** [comment]
Hi @waschbaer00 Did I answer your question? If yes, we should close the issue.

**Comment by sgiraudot** [comment]
The input range is reordered by the algorithm (see [the documentation of `set_input()`](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#aafda3c8eaae3d1cf6466d62138a9ac9f)), so the indices you get from the algorithm are not with respect to your original point cloud, it's with respect to the reordered point cloud.

If you want to be able to recover the original order, one way to do it is to use a set of indices as input (instead of a set of points) with dedicated property maps to read the points and normals in a separated container (that will be kept unaltered, as only the set of indices will be reordered). This is more or less the principle behind `CGAL::Point_set_3`, which you can use with RANSAC, see [the example in the doc](https://doc.cgal.org/latest/Point_set_3/index.html#title4).

**Comment by waschbaer00** [comment]
Yes, thank you that is the problem. I didn’t carefully read the document:)

**Comment by waschbaer00** [comment]
Yes, thank you that is the problem. I didn’t carefully read the document:)
