### ISSUE TITLE
'basis-inverse check: failed': QP solver crashes on this specific 2D problem 

### ISSUE THREAD

**Issue by sciencectn** [CGAL/cgal#4131]
## Issue Details

The QP solver crashes with this specific problem:
```
minimize (1/2) x^T D x + c^T x
subj to 
A x <= b
||x||_inf <= 10 
```
with matrices (using Matlab syntax):
```
D=eye(2);
c=[-0.0017921232005258584;0.00098903927697657876];
A=[0.76661607684871724 0.2015603854685275];
b=0.0012600203131879761;
```

 I know the optimal solution should be `x = -c` which is right on the constraint boundary. It gives this error:
```
basis-inverse check: failed ( row=0 | col=0 )
basis-inverse check: failed ( row=1 | col=0 )
basis-inverse check: failed ( row=0 | col=0 )
basis-inverse check: failed ( row=1 | col=0 )
basis-inverse check: failed ( row=1 | col=1 )
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: check_basis_inverse()
File: include/CGAL/QP_solver/QP_solver_impl.h
Line: 1167
Aborted (core dumped)
```

## Source Code

```
#include <iostream>
using std::cout;
using std::endl;

#include <CGAL/QP_models.h>
#include <CGAL/QP_functions.h>
#include <CGAL/exceptions.h>

typedef CGAL::Quadratic_program<double> Problem;
typedef CGAL::Quadratic_program_solution<double> Solution;

int main(){
    Problem qp(CGAL::SMALLER, true, -10, true, 10);

    qp.set_d(0,0,1);
    qp.set_d(1,1,1);

    qp.set_c(0,-0.0017921232005258584);
    qp.set_c(1,0.00098903927697657876);

    qp.set_a(0,0,0.76661607684871724);
    qp.set_a(1,0,0.2015603854685275);

    qp.set_b(0, 0.0012600203131879761);

    Solution s = CGAL::solve_quadratic_program(qp, 0.0);
    cout << s << endl;
}
```
[Here's the full CMakeLists.txt that I used to compile this. ](https://gist.github.com/sciencectn/dd85b7ab1c567d64ec4ed97cd0854abc)

## Environment

* Operating system: Tested on both Ubuntu 18.04.2 LTS and MacOS 10.14.16
* Compiler: Tried both gcc 7.4.0 and clang-1001.0.46.4
* Release or debug mode: **Debug**. It seems to work in Release mode. 
* Specific flags used (if any):
* CGAL version: Tried 4.11 on linux and the latest from master on mac & linux 
* Boost version: 1.70 on mac, 1.65 on Linux. 
* Other libraries versions if used (Eigen, TBB, etc.): MPFR 4.0.1, GMP 6.1.2

**Comment by MaelRL** [comment]
I do not the theoretical formulation of your problem, but do note that in `set_d(i, j, val)`, `val` is the i-th line and j-th colomn entry of **`2*D`**, and not `D`. Changing the `set_d()` values to `2`, it gives some output. Is it just that? Could you please give the formulation that you're trying to solve?

**Comment by sciencectn** [comment]
I'm pretty sure the objective function is correct. I edited my original issue with the full QP problem. 

If I put it in Matlab I get the right answer:
```
D=eye(2);
c=[-0.0017921232005258584;0.00098903927697657876];
A=[0.76661607684871724 0.2015603854685275];
b=0.0012600203131879761;
lb = [-10;-10];
ub = [10;10];
x = quadprog(D,c,A,b,[],[],lb,ub);
vpa(x)

ans = 
   0.001773160205
 -0.00099402506
```

**Comment by MaelRL** [comment]
I didn't say your objective function is wrong, but rather that its implementation in CGAL terms might have had an issue, which it does indeed: since you're solving `1/2 x^T D x`, with `D = eye(2)`, you have in CGAL terms `D=I_2` and thus you must write `set_d(.,.,**2**)` since the function expects the value for `2*D`, not `D`.

Once that is fixed, the QP solver does give out a result I was mentioning above. However, it is different from yours:
```
status:          OPTIMAL
objective value: -1.04748e-06
variable values:
  0: 0.000896062
  1: -0.00049452
```
This solution fits your constraints and has a lower objective value (`-1.04748e-06` vs `-2.86684e-08` for your values; it looks the opposite since values are negative, but it can be made clearer by just putting `c0` at `+1` instead of `0` in the objective function). Moreover, this is also the solution found by a few other tools like [wolfram alpha](https://www.wolframalpha.com/input/?i=minimize+x*x%2By*y+%2B+-0.0017921232005258584*x+%2B+0.00098903927697657876*y+with++0.76661607684871724*x+%2B+0.2015603854685275*y+%3C%3D+0.0012600203131879761) or http://apmonitor.com/online/view_pass.php?f=qp2.apm

I'm then a little bit confused by the result given by Matlab, then. Could Matlab expect a positive objective function value? What happens if you add a non-null `c0`? There could also be the same error in all my implementations, but it seems unlikely, as in the end it just simplifies to:
```
minimize x^2+y^2 + cx*x + cy*y
with ax*x + ay*y <= b
```
which doesn't leave too much room for error.

**Comment by sciencectn** [comment]
So whatever you put in for D, CGAL just divides it by 2, correct? I believe is equivalent to 
saying `1/2 x^T D x` where D is exactly what you entered via the `set_d` function. 

Is there some reason we don't just put a (1/2) in front of quadratic term in [the objective function in the docs](https://doc.cgal.org/latest/QP_solver/index.html)? 

It also gives the correct answer which agrees with Matlab if I compile in Release mode, so I'm quite sure the formulation is correct:
```
status:          OPTIMAL
objective value: -4.1899e-06/2
variable values:
  0: 0.00179212/1
  1: -0.000989039/1
```
Debug mode is where I have problems. 

If you loosen the constraint a little bit by increasing b, it works. This is the lowest value of b I could find where it still works:
```
// qp.set_b(0, 0.0012600203131879761);
qp.set_b(0, 0.0013738704572183735);
```

**Comment by MaelRL** [comment]
Yes, set_d requires entries of 2*D. I don't know what was the reasoning for that. In the end, you get the same formulation as 1/2 x^t D x, but with set_d requiring simply entries of D. Obviously whatever help having 2*D brings is not worth the user friendliness cost.

And, once again, I'm not questioning the theoretical formulation of your objective function, but the way you translated it into CGAL code: you apparently want your theoretical objective function to be `x^2+y^2+...` since you used `D=eye(2)` in a formulation based on `1/2 x^t D x`, that means D is `I_2` in CGAL code (x^t D x, no "half"). This means `set_d` should have value `2`. Whatever you are getting in release mode is with a `set_d` with value 1. This is the solution of another problem, namely `1/2(x^2+y^2)+...`.

**Comment by sciencectn** [comment]
Sorry for the late response. I do in fact want the theoretical objective function to be `(1/2)(x^2+y^2) + ...`. The divide-by-2 that CGAL does is expected and it matches the behavior of quadprog in Matlab and most other QP solvers. 

But in either case, is it really an issue? `D` and `D/2` are both positive definite symmetric and the constraints are feasible so it shouldn't crash right?

**Comment by MaelRL** [comment]
You are right, and I got confused by the `eye(2)`.

The problem in your program is actually not from the `set_d`, but the fact that your solution type is templated by an inexact number type (`double`). As the [documentation](https://doc.cgal.org/latest/QP_solver/classCGAL_1_1Quadratic__program__solution.html) says, you must use an exact number type. It is not guaranteed to work if you put `double`. Note that it might still work, as we have seen from what happens when you use `2` in `set_d`, but here you have a minimum on a constraint boundary, which is probably why `double` is not strong enough.

Here is how the program should look: https://gist.github.com/MaelRL/a4b3a8886c48795ef2415ad348938692.

**Comment by sciencectn** [comment]
Thanks for the provided code, using `MP_Float` as the solution type did the trick!
