### ISSUE TITLE
urgent need

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4166]
hi~
I want to use "Microsoft Visual Studio" to use cgal. But I can't get the current master installer.
Can you provide it?
urgent need
Thank you very much

**Comment by maxGimeno** [comment]
There is no "master installer". We only provide installers for releases.

**Comment by simonasdmd** [comment]
hi~
@maxGimeno 
The installation documentation describes the installer installation. Building "master" requires GMP and other things. I hope to update a detailed master build description.
The INSTALL.md description is too rough. There is no way to build a cgal smoothly as described.

**Comment by sgiraudot** [comment]
It is hard to help you if you don't follow the advice that people give, like [stick to the public release and locally patch the two files](https://github.com/CGAL/cgal/pull/4122#issuecomment-522910477) (I imagine you're only asking the question of a "master installer" because of the recent patch that interests you).

"Building master" does not really mean anything: you build examples/tests or whatever programs you are using CGAL with. If you have errors, then you should read them and try to understand them. If you can't, then you should fill the issue template instead of deleting it like you did.

There is nothing rough there as long as you are comfortable with using CMake and installing third party libraries. If you aren't comfortable with that, I'm sorry but this is out of scope for us.

**Comment by simonasdmd** [comment]
Which two files should I modify? Is there a tutorial?
I just want to build the latest cgal. But I can't do this according to the instructions in the install.md file. A lot of libraries are missing. I have installed cgal before, can I use it?

**Comment by sgiraudot** [comment]
- Did you even click on the link I gave you? It says "stick to the public release and locally patch the two files you can find in the Files Changed tab"
- We do not provide tutorials for modifying files
- Again, you don't build CGAL, you build programs that are using CGAL
- A lot of libraries are missing -> then install them
- If you've installed a public release CGAL before and are _only_ interested by the recent patch, then again, __yes do use it and just modify the two files of the patch__
