### ISSUE TITLE
Wrong result of squared_distance of two Segment_2 objects

### ISSUE THREAD

**Issue by aboudev** [CGAL/cgal#4189]
Wrong result of squared_distance of two Segment_2 objects.

## Issue Details

Using `CGAL::squared_distance` to compute the closest distance between two **almost collinear** segments may produce wrong results in some cases. e.g.
```
# Wavefront
v -4.0380854964382 -1.9947196614192 0.0
v 10.43442091460618 -0.5886833953492263 0.0
v -11.5138934277993 -2.721011070186227 0.0
v -8.822747585009402 -2.459560251317805 0.0
l 1 2
l 3 4
```
The computed result is 0, which is not right if we visualize the .obj file.

![snapshot00](https://user-images.githubusercontent.com/13584496/63759942-f8008280-c8f0-11e9-9126-25e45d0529b9.png)

## Source Code

```cpp
#include <iostream>

#include <CGAL/Simple_cartesian.h>
#include <CGAL/squared_distance_2.h>

typedef CGAL::Simple_cartesian<double> Kernel;
typedef Kernel::Segment_2 Segment_2;

int main() {
  const Segment_2 segi = {
    { -4.0380854964382, -1.9947196614192 },
    { 10.43442091460618, -0.5886833953492263 } };
  const Segment_2 segj = {
    { -11.5138934277993, -2.721011070186227 },
    { -8.822747585009402, -2.459560251317805 } };

  const auto dist = CGAL::squared_distance(segi, segj);
  std::cout << "#dist: " << dist << std::endl;

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows and Linux, 64 bits
* Compiler: VC 2015, gcc 5.5.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: 1.65
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
The distance code was not written with floating point numbers in mind, but to  be without overhead when used with exact number types.  We might make an effort to improve robustness when using the `CGAL::Exact_predicates_inexact_constructions_kernel`, because currently it will even give a wrong result for this  one.

**Comment by aboudev** [comment]
Thank you for your explanation. I didn't expect any kernel restriction from this function.

**Comment by mglisse** [comment]
> I didn't expect any kernel restriction from this function.

You should expect such issues in Epick for all *constructions* (returns an object like a point) and *computations* (returns a number), as opposed to *predicates* (returns combinatorial information, with a small enum or bool). Some functions are tweaked to be less brittle, but the whole design of this kernel is not meant for safe constructions.
Rewriting the operation so that all combinatorial choices are delegated to (filtered) predicates, as in the proposed patch (?), is one way to make the function less brittle, although you cannot expect any guarantee from such a kernel.
