### ISSUE TITLE
Feature request: Surface mesh simplification with weights

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4246]
## Issue Details

I think it will be great if `CGAL::Surface_mesh_simplification::edge_collapse` can support some sort of weighting. Meaning simplify less on region of interest (e.g. human face), and simplify more on non-region of interest instead of simplifying uniformly. The per-vertex weight can be supplied by the downstream user maybe in the form of `Property_map`.

**Comment by sloriot** [comment]
There is already a [`GetCost`](https://doc.cgal.org/latest/Surface_mesh_simplification/classGetCost.html) concept so that user can design their custom tailored cost function to select which edges should be collapsed first.
If you have a property map filled with weights on vertices, you can design your own cost looking at the weights stored in an edge endpoint.
