### ISSUE TITLE
Number types in box_limits.h

### ISSUE THREAD

**Issue by aothms** [CGAL/cgal#4274]
I'm trying to use `CGAL::box_self_intersection_d()` on the number type of the `CGAL::Exact_predicates_exact_constructions_kernel`. This fails (compilation error) because there is no template specialization for those types in https://github.com/CGAL/cgal/blob/master/Box_intersection_d/include/CGAL/Box_intersection_d/box_limits.h. Only (unsigned) int, float, double.

Wouldn't it make sense to have some defaults in the non-specialized definition? For example I got my code to run by adding the following, but perhaps in general all definitions could be folded into two cases based on `std::is_integral`?

~~~
template<class T>
struct box_limits {
	static T inf() { return -sup(); }
	static T sup() { return (std::numeric_limits<T>::max)(); }
};
~~~

Or is it nonsensical as boxes are in general likely approximations of the underlying geometry and there is little to gain from robust number types?

**Comment by sloriot** [comment]
It indeed does not really make sense to use bbox with rational coordinates. When you construct a bbox out of an object from the EPEC Kernel the bbox is using double coordinates and are such that the bbox is containing the object exactly (but not tightly in general).
In dD Box intersection package, the bboxes are used to filter intersections, which can be done exactly using bboxes with double coordinates.
Using a rational number type for the bboxes will only slow down the intersection test and except some specific tests will not reduce the number of bbox overlaps (due to bbox being tight).

Note that the [doc](https://doc.cgal.org/latest/Box_intersection_d/index.html#secboxintersdef) even says:
"The number type of the interval boundaries must be one of the built-in types int, unsigned int, double or float."

Feel free to reopen the issue if you think I did not answer your question.

**Comment by lrineau** [comment]
> Feel free to reopen the issue if you think I did not answer your question.

Actually, non-privileged users cannot re-open their own bug-reports, if they were closed by CGAL developers. But Thomas @aothms, you can continue to discuss on this page, and eventually ask for a reopening.

**Comment by aothms** [comment]
Thanks @lrineau and @sloriot I agree. It's documented and reasonable behaviour.
