### ISSUE TITLE
Our Release test platforms are actually debug

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4297]
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-158.shtml#Surface_mesh_shortest_path

All the platforms with a red cell in the line `Surface_mesh_shortest_path` are using Debug flags. But about half of them should be Release!

**Comment by lrineau** [comment]
That is certainly related to header-only. @maxGimeno I thought you had already fixed that. Maybe you have to add `CMAKE_BUILD_TYPE` in the `init.cmake` files.

**Comment by maxGimeno** [comment]
I fixed that for the platforms we decided should use init.cmake, and they were few (basically all the platforms that are not red). Should I set this system up for all the remaining release platforms now ?

**Comment by lrineau** [comment]
I think there should be `init.cmake` files for all platforms:
  - for release platforms, to set the `CMAKE_BUILD_TYPE` and the flags (replace `-DNDEBUG` by `-DCGAL_NDEBUG`),
  - for debug platforms, to make sure the `-g` or `/Zi` flags are never used.

**Comment by maxGimeno** [comment]
related PR : [#101](https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/101)

**Comment by MaelRL** [comment]
This was fixed by https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/101.

@lrineau @maxGimeno What do you think of an additional column on the platform list at the top of https://cgal.geometryfactory.com/CGAL/testsuite/ for build type? The name doesn't always reflect it, e.g. `Fedora-with-LEDA` is `Release`, and `Fedora` is `Debug`; the flags give it away, but it's not immediate.

**Comment by maxGimeno** [comment]
I think it would be a good idea. After having to find out which platforms were supposed to be Released, I agree with you that it could be clearer.
