### ISSUE TITLE
Cleaning Named Parameter Documentation

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4300]
[The named parameter page](https://doc.cgal.org/latest/Polygon_mesh_processing/group__pmp__namedparameters.html) (and similarly for PSP and other packages) contains the documentation of parameters that are used by only one function. There is no need to documented them on that page and the relevant information should be moved to the function.

Adding the documentation of one parameter on that page should be motivated by a good enough reason. For example for `vertex_point_map` we document that the default is the internal vertex point map of the mesh. For `geom_traits` we can says that the default is deduced from the vertex point map and that the value type of the vertex point map should be the nested `Point_3` type of the class.

Opinions?

**Comment by shixianli158** [comment]
hi

**Comment by shixianli158** [comment]
very good

**Comment by sloriot** [comment]
Since we know have our np class we can document this type and probably avoid the np page + use the type in function signature for a direct link.

**Comment by MaelRL** [comment]
Below are two mock-ups of how things could maybe be improved. Some remarks:
- It makes the NP not a section with the same level as parameters (see actual: https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gad3d03890515ae8103bd32a30a3486412 for example)
- Named parameters are each collapsible (and collapsed by default)
- Because the NPs are (independently) collapsible, a lot more information can be put without being immediately overwhelmed by 50 lines of documentation. Information such as the default being always present, which is currently not the case and problematic : for `PMP::sample_mesh`, you better look at the code to know the default values.
- The page regrouping all named parameters (https://doc.cgal.org/latest/Polygon_mesh_processing/group__pmp__namedparameters.html for PMP) would be redundant as each function is self-sufficient. The page can thus be removed.
- Probably some work to be done on the page https://doc.cgal.org/latest/BGL/index.html#BGLNamedParameters.

Cons:
- Maybe a bit annoying to have to decollapse each NP individually?
- There would be a lot of shared content (but it's kinda the case already).

Feedback and ideas welcome
@CGAL/geometryfactory 

Collapsed
--------------------------------------------------------------------------------------------------------------
![test_4](https://user-images.githubusercontent.com/5074170/75564844-2f411f00-5a4d-11ea-9bad-3bee36ce9e56.png)

Expanded
--------------------------------------------------------------------------------------------------------------

![test_3](https://user-images.githubusercontent.com/5074170/75564838-2cdec500-5a4d-11ea-94f8-6bcd2f383e82.png)

**Comment by maxGimeno** [comment]
Maybe a short description always visible and the details in the collapsable section if needed, to avoid "having to de-collapse each NP individually" ?

**Comment by janetournois** [comment]
- I agree with @maxGimeno. A non-collapsible short description (like 1-2 lines) for each NP would be good.
- There are some parameters like `geom_traits` and `vertex_point_map` that always have the same description. I think we should have some templates (doxygen macros?) to avoid having n different versions of the same thing in the different functions that use these parameters.

- Is it possible to create and use a doxygen macro like 
```\CGAL_np{np_name}{np_short_description}{np_type}{np_default}{np_extra}```
that would be used as follows :
-- if `np_name` is known (like `geom_traits`), its description is used, and the writer can simply write `\CGAL_np{geom_traits}`. The description would be automatically added (and consistent with other functions)
-- otherwise, all the parameters are needed (but `np_extra` which is optional). The writer needs to write a short description, a type, and a default. This would force everybody to follow the documentation rules? Then it would look like : `\CGAL_np{my_new_np}{"my short description"}{double}{1.1}{"this is optional extra information"}`

**Comment by MaelRL** [comment]
I propose to move the discussion to the PR so actual code can be used: https://github.com/CGAL/cgal/pull/4591#issuecomment-602045437.
