### ISSUE TITLE
How to simplify texture while simplifying mesh

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4359]
_Please use the following template to help us solving your issue._

## Issue Details

How to simplify texture while simplifying mesh

## Source Code

This is a reasonable need. Why not simplify the texture when simplifying the mesh?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows 64
* Compiler:vs2017
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: 1.70
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
There is no direct texture handling in CGAL but the visitor of the simplification package can help tracking what operations are being done during the simplification. If you give more details about what you would like to achieve precisely,  we might be able to help you do what you need.

**Comment by simonasdmd** [comment]
hi~
@sloriot 
Now CGAL only simplifies the geometric mesh. But it doesn't simplify the mapping. Texture coordinates. For example, obj file. The original obj file has vertex normals and texture coordinates. But CGAL only reads the vertex when it reads obj. Then there is no processing of the texture coordinates. After that, the obj file is exported with only vertices. This should be a big place to be ignored. We hope to provide a method to simplify texture coordinates synchronously.

**Comment by sloriot** [comment]
My point was that you can follow what is done in [this example](https://doc.cgal.org/latest/Surface_mesh_simplification/Surface_mesh_simplification_2edge_collapse_visitor_surface_mesh_8cpp-example.html) to get information before and after an edge is collapsed so that you can update your texture. This has to be done on the user side as  CGAL does not know what a texture is.
Also note that the OBJ writer from CGAL does not handle any extra attribute AFAIK, so you might need to extend the existing one to export any additional attribute.

**Comment by simonasdmd** [comment]
I think CGAL should update the processing of "VT" texture coordinates. Not just the vertices. Texture coordinates are very necessary for 3D data. But after CGAL reprocessing. The texture is gone.
I think this can be a function request.

**Comment by simonasdmd** [comment]
hi~
Will this question be completed？

**Comment by sloriot** [comment]
Do you have a minimal code example showing what you want to achieve?
