### ISSUE TITLE
demos don't show the 3D effect

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#437]
with Qt5, 3D demos (ex 3D triangulations and periodic) show only the wireframe mode, with which we cannot see anything :(

**Comment by lrineau** [comment]
On MacOS X ? Any message on the console?

cc @maxGimeno

**Comment by MoniqueTeillaud** [comment]
yes, on MacOS (sorry, I should have mentioned it)

there is a message when I launch the demo
2015-10-28 14:44:32.192 T3_demo[36713:507] invalid drawable

but no message when I toggle the 3D effect on/off

**Comment by lrineau** [comment]
Which version of Qt5 was used?
There had been bugs of Qt5 on MacOS. There is [one][1] related to `QGLWidget` and "invalid drawable", fixed in Qt-5.3.

[1]: https://bugreports.qt.io/browse/QTBUG-35342

**Comment by MoniqueTeillaud** [comment]
5.5.1

**Comment by odevil** [comment]
Mac OSX 10.9.5
AppleClang 5.0.0.5000279
Qt 5.5.0

I compiled Polyhedron demo in debug mode and cannot execute:
./Polyhedron_3 
2015-12-16 16:07:00.662 Polyhedron_3[19607:507] invalid drawable
Segmentation fault: 11

I compiled T3 demo and run it, when 3d effects are on there is nothing visible
when 3d effects are off, there is a correct wireframe drawing
./T3_demo 
2015-12-16 16:16:01.851 T3_demo[19843:507] invalid drawable

I compiled Periodic2 demo and run it,
Delaunay is not visible because shading of triangles seems incorect
(everything is gray), (no message "invalid drawable")
./Periodic_2_Delaunay_triangulation_2

**Comment by sloriot** [comment]
We have issues making Qt 5.5.1 working on our Mac. How did you install it? using the `.dmg` provided online or did you compile it yourself? @MoniqueTeillaud @odevil

**Comment by maxGimeno** [comment]
There is a branch in cgal-dev that fixed the issue. There is a PR for it, but you could test the branch (cgal-dev/FixForMac-GF) and confirm that the problems are solved.

**Comment by lrineau** [comment]
See PR #654.
