### ISSUE TITLE
Delaunay triangulation goes outside border

### ISSUE THREAD

**Issue by benlaurie** [CGAL/cgal#4464]
## Issue Details

If I try to fill the holes in the object in the gist, then I end up with a shape that includes triangles that are outside the border of the object.

Disabling Delaunay triangulation fixes the problem.

## Source Code

Source and object are at https://gist.github.com/benlaurie/1ed073fa9777a53993967de5fd77b7f7

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): FreeBSD 64 bit
* Compiler: clang
* Release or debug mode: release
* Specific flags used (if any): none
* CGAL version: 5.0
* Boost version: 1.72.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by benlaurie** [comment]
By the way, the code that produces this also produces many shapes that Delauney triangulation fails on, causing a fallback to general triangulation. Would those be of interest?

**Comment by sloriot** [comment]
It might simply be that the code that extract the candidate triangles fails because the triangulation is 2D and that special case was forgotten. I'll have a look later today.

**Comment by sloriot** [comment]
If you have some data that make the triangulation fails (using a kernel with exact predicates) please fill an issue.

**Comment by sloriot** [comment]
![Screenshot from 2020-01-16 15-04-20](https://user-images.githubusercontent.com/1224632/72531341-8c07c200-3871-11ea-9c9c-cb8a78649d80.png)
It is not a bug but the result the method is expected to return. On the picture above, the red edges show the Delaunay triangulation of input vertices. The hole filling algorithm when Delaunay is used is working as follow:
* initialize the search space of possible triangles using triangles of the triangulation incident to a boundary edge
* if an edge of the boundary does not have any incident triangle, augment the search space with all possible triangles incident to that edge
* use the search space to find the best triangle filling the hole

As you can see, there are some boundary edges having incident triangles that goes outside of the domain. Since those triangles exists in the Delaunay triangulation, it prevents the other possible triangles to be found and the algorithm has to pick them.

I think in such cases, the function should be able to decide to use the 2D constrained triangulation to generate the filling triangles. I think it might be sufficient to use the PCA package, check that no boundary edge is reversed when projected on the fitting plane, and then use the general projection traits. It is equivalent to add a new face for the boundary cycle (`add_face()`+`set_face()` for all halfedges in the cycle) and call `PMP::triangulate_face()`. @maxGimeno Do you think you could implement that?

**Comment by sloriot** [comment]
#4483

**Comment by danston** [comment]
#4749
