### ISSUE TITLE
Infinite loop in CGAL::Surface_mesh_simplification::edge_collapse. 

### ISSUE THREAD

**Issue by pherman** [CGAL/cgal#4479]
## Issue Details

There is an infinite loop in CGAL::Surface_mesh_simplification::edge_collapse.  Example input and source code are given in the gist below.  If I increase the resolution to 20,000, edge_collapse finishes without error.

## Source Code

[https://gist.github.com/pherman/548011949cf86264f74c51d04ad7ec5c](https://gist.github.com/pherman/548011949cf86264f74c51d04ad7ec5c)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04.3 LTS 64-bit, kernel 4.15.0-74-generic
* Compiler: gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.04.1)
* Release or debug mode: Release
* Specific flags used (if any): none
* CGAL version: CGAL_VERSION 4.14-I-900, CGAL_VERSION_NR 1041400900, CGAL_RELEASE_DATE 20191001
* Boost version: 1.65.1
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by MaelRL** [comment]
The input file seems to be truncated: it ends with
```
3 9063 9084 8453
3 9090 9091 845
```
after only about 17k faces instead of the ~44k announced in the header, and I thus cannot open it.

**Comment by pherman** [comment]
Don't know what happened there.  Sorry for the trouble.  Hopefully this works:  [mesh.txt](https://github.com/CGAL/cgal/files/4099500/mesh.txt) (I had to change the extension from off to txt so that Github accepts the upload.)

**Comment by MaelRL** [comment]
The part below the left arm of your model has non-manifold vertices (the mesh is pinched), which violates a precondition of the algorithm. You can use the function [PMP::duplicate_non_manifold_vertices()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga71b69817fe09aa9b6d366a67e1c635ce) to dissociate the non-manifold vertex into two vertices having the same position. This creates some self-intersections (see image below, with self-intersections being black faces), but this is not a problem for the algorithm (and you already had self-intersections at another problem).

The algorithm runs fine with this change. I have uploaded an updated version of your code [here](https://gist.github.com/MaelRL/1fed0ef09e0a20aa93b280d6dca1ed1f). Note that I updated the vertex constraint map so that you it avoids searching a whole range every time, which is very costly since the constraint check is performed very often.

![nm-arm](https://user-images.githubusercontent.com/5074170/72992493-1ad98900-3df4-11ea-8ce5-5e746b8b99ac.png)

**Comment by pherman** [comment]
Thank you very much for the hint.

**Comment by sloriot** [comment]
@MaelRL shall we add a precondition in the function?

**Comment by MaelRL** [comment]
The algorithm already checks that the input is a valid polygon mesh, in debug mode. The precondition does fail if you have non-manifold vertices like it was the case here.
