### ISSUE TITLE
Launchpad.net: CGAL user group needed and ownership of your project

### ISSUE THREAD

**Issue by thopiekar** [CGAL/cgal#4510]
Hello everyone,

at the moment I'm about to get CGAL imported to launchpad.net. However, the problem is still open that the first (and initial) import of the repository fails due to a timeout.
https://answers.launchpad.net/launchpad/+question/688628

The code import is needed to run so-called recipes, which allow building nightly Debian packages for Ubuntu releases daily.

At the moment, the CGAL project and the imported code is owned by me. Right now, my concept of having a PPA with nightly builds of CGAL is still not working, but I can understand if you want to be mentioned as the owners and maintainers of your project at any time.
Therefore, I'm informing you here already.

https://launchpad.net/cgal
https://code.launchpad.net/cgal/+git

Hope you don't mind. If there are further questions, just let me know.
- Thomas

**Comment by lrineau** [comment]
I think we should get advice from @joachim-reichel. He is the maintainer for Debian packages of CGAL. And maybe also for Ubuntu's.

**Comment by joachim-reichel** [comment]
The Debian packages I create are also imported into Ubuntu. Typically, the Ubuntu ones are identical with the exception of occasional tiny technical changes.

For reference, the existing packages can be reached via https://packages.ubuntu.com/search?keywords=cgal

@Thomas: thanks for the information! I'm a bit unsure what you exactly mean with the issue title ...

Below are some random thoughts that came to my mind.

What is the main goal of this? Do you want to provide access to cutting-edge CGAL code as deb packages? Wouldn't users requiring this rather work directly on the repository instead? (In particular, since CGAL is now header-only.)

Or do you want to extent testing? Keep in mind that creating the binary packages only builds the ipelets, whereas building/running demos/examples/tests would be much better suited for testing purposes (but takes quite some time).

You are probably aware that the git repository layout is different from the tarball layout. You would need to run that script that generates tarball out of the repository as first step. Or create a different deb source package that works directly on the repository layout.

**Comment by thopiekar** [comment]
@joachim-reichel Nice to meet you here!

Yes, I can automatically build (triggered by changes made on the repo) packages daily. The current daily builds of CGAL in my PPA are based on your packaging files. You might noticed from the links above.
Together with the CGAL packages I would like to provide bindings by the SWIG project here, too. However, with these I have some trouble still. https://github.com/CGAL/cgal-swig-bindings/issues/150

The tarball is created by launchpad.net as the code is received from Git. I guess due to the differences between the tarball and the repo layout, I had to make some changes. However, everything works as far as I can say.

However, the reason why I'm writing you here is that I'm official marked as the maintainer of CGAL on the pages on launchpad and if there is any interest from your side, we could move the maintainer-ownership to a "CGAL" group (team of project members).

Once my CGAL and SWIG packages build fine, we can also move the packages there.
Apart from daily builds, builds based on stable (e.g. on a stable tag) are also possible.

**Comment by afabri** [comment]
Dear Thomas,
we discussed it internally and came to the conclusion that we cannot spend any effort in supporting CGAL@Lauchpad.    We are wondering how to make that very clear on Launchpad,net, but maybe the fact that you and not somebody from cgal.org is the maintainer is good enough. 
Best regards,
Andreas Fabri
Member of the CGAL Editorial Boar
