### ISSUE TITLE
Warnings while installing CGAL using vpckg

### ISSUE THREAD

**Issue by cgarmstr** [CGAL/cgal#4544]
_Please use the following template to help us solving your issue._

## Issue Details
I have been attempting to install CGAL with vcpkg, https://doc.cgal.org/latest/Manual/windows.htmlhttps://doc.cgal.org/latest/Manual/windows.html

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._
After running cmake-gui.exe the output is:
Targetting Visual Studio 16 2019
Target build enviroment supports auto-linking
Using VC toolset 141.
Generator uses intermediate configuration directory: $(Configuration)
Boost version: 1.72.0
Boost include dirs: C:/Users/cecil/vcpkg/installed/x86-windows/include
Boost libraries:    
NOTICE: The example draw_triangulation_2 requires Qt and will not be compiled.
Configuring done
WARNING: Target "constrained_plus" requests linking to directory "C:\Users\cecil\vcpkg\installed\x86-windows\share\mpfr".  Targets may link only to libraries.  CMake is dropping the item.

plus many other similar errors.

Note also that Boost_DIR is not found. What am I looking for?

![image](https://user-images.githubusercontent.com/7409913/75260776-0406c780-57e2-11ea-86e3-095dc37f5077.png)
![image](https://user-images.githubusercontent.com/7409913/75261330-c0f92400-57e2-11ea-99d1-5475d3973f29.png)

## Source Code
 /CGAL-5.0.1/examples/Triangulation_2

## Environment

* Operating system (Windows 10, 32bits):
* Compiler: Visual Studio 16 2019
* Debug mode:
* Specific flags used (if any):
* CGAL version: CGAL-5.0.1
* Boost version: Whatever came with CGAL-5.0.1
* Other libraries versions if used (Eigen, TBB, etc.): None

**Comment by maxGimeno** [comment]
- There is currently a bug that will be vey soon fixed by CGAL-5.0.2 that prevents from building the whole exmaple directory if CGAL-Qt5 is missing, when it shouldn't. After that fix, there will only be a NOTICE: in cmake and that's all. 
 - If you actually want to try the graphical triangulation examples, you need to install cgal[qt] instead of just cgal in vcpkg, as explained a little further in the manual.

**Comment by cgarmstr** [comment]
Tried .\vcpkg install cgal[qt]. Build failed with a different error, see attached.
[error-msg.txt](https://github.com/CGAL/cgal/files/4252297/error-msg.txt)

**Comment by maxGimeno** [comment]
Looks like a cache problem. You can try to clear your build directory and try again

**Comment by cgarmstr** [comment]
I cleared the vcpkg\downloads directory and tried again. There is no file 
https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip 

Sorry to be a pain!

PS C:\Users\cecil\vcpkg> .\vcpkg install cgal[qt]
Computing installation plan...
The following packages will be built and installed:
    cgal[core,qt]:x86-windows
  * eigen3[core]:x86-windows
  * freeglut[core]:x86-windows
  * jasper[core]:x86-windows
  * libpq[core,openssl,zlib]:x86-windows
  * libwebp[core,nearlossless,simd,unicode]:x86-windows
  * opengl[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * pcre2[core]:x86-windows
  * qt5-3d[core]:x86-windows
  * qt5-activeqt[core]:x86-windows
  * qt5-base[core]:x86-windows
  * qt5-declarative[core]:x86-windows
  * qt5-gamepad[core]:x86-windows
  * qt5-imageformats[core]:x86-windows
  * qt5-script[core]:x86-windows
  * qt5-svg[core]:x86-windows
  * qt5-tools[core]:x86-windows
  * qt5-xmlpatterns[core]:x86-windows
  * sqlite3[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/21: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\cecil\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
WinHttpQueryDataAvailable() failed: 12175

**Comment by maxGimeno** [comment]
This time it looks like a bug in other packages than CGAL. You could try the x64 versions instead of the x86, just in case. 
You can try  `vcpkg.exe install cgal[qt]:x64-windows`

**Comment by lrineau** [comment]
> There is no file
> [PowerShell/PowerShell@`v6.2.1` PowerShell-6.2.1-win-x86.zip (download)](https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip)

That links works for me. Try to install Powershell on your machine before you run vcpkg.

**Comment by Frank-Dz** [comment]
I learned that if I want to install CGAL with qt5, I can use the command `.\vcpkg.exe install cgal[qt]:x64-windows`
But if I want to install Ceres for smoothing method. what should  I do? Should I firstly install the Ceres then install the CGAL? Further, if I want to install ALL the necessary packages for the lastest CGAL via vcpkg, is there some guidance I can follow? I have read the tutorial: https://doc.cgal.org/latest/Manual/windows.html But I still didn't find the corresponding commands for vcpkg.

Best,
Frank

**Comment by Frank-Dz** [comment]
> I cleared the vcpkg\downloads directory and tried again. There is no file
> https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip
> 
> Sorry to be a pain!
> 
> PS C:\Users\cecil\vcpkg> .\vcpkg install cgal[qt]
> Computing installation plan...
> The following packages will be built and installed:
> cgal[core,qt]:x86-windows
> 
> * eigen3[core]:x86-windows
> * freeglut[core]:x86-windows
> * jasper[core]:x86-windows
> * libpq[core,openssl,zlib]:x86-windows
> * libwebp[core,nearlossless,simd,unicode]:x86-windows
> * opengl[core]:x86-windows
> * openssl[core]:x86-windows
> * openssl-windows[core]:x86-windows
> * pcre2[core]:x86-windows
> * qt5-3d[core]:x86-windows
> * qt5-activeqt[core]:x86-windows
> * qt5-base[core]:x86-windows
> * qt5-declarative[core]:x86-windows
> * qt5-gamepad[core]:x86-windows
> * qt5-imageformats[core]:x86-windows
> * qt5-script[core]:x86-windows
> * qt5-svg[core]:x86-windows
> * qt5-tools[core]:x86-windows
> * qt5-xmlpatterns[core]:x86-windows
> * sqlite3[core]:x86-windows
>   Additional packages (*) will be modified to complete this operation.
>   Starting package 1/21: openssl-windows:x86-windows
>   Building package openssl-windows[core]:x86-windows...
>   A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
>   Downloading powershell-core...
>   https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\cecil\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
>   WinHttpQueryDataAvailable() failed: 12175

Since you deleted all the packages in download fold. Some necessary pkgs for vcpkg are also removed. https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip is usually associated with running VCPKG through Powershell, and you should not delete it.

**Comment by maxGimeno** [comment]
@Frank-Dz must be right, I misread your last response. When I said to clear your build directory I meant the directory in which you were tryng to build the examples, not the `download` directory. You might have to re-install vcpkg now :/

For Ceres, you should be able to get from [here](http://ceres-solver.org/installation.html). Once installed, you will probably have to fill in the Ceres related variables in the configuration step of your CGAL program. I think the variable you are looking for is `Ceres_DIR`, that must be the directory containing the CMake-config.txt or something like that.

**Comment by Frank-Dz** [comment]
> @Frank-Dz must be right, I misread your last response. When I said to clear your build directory I meant the directory in which you were tryng to build the examples, not the `download` directory. You might have to re-install vcpkg now :/
> 
> For Ceres, you should be able to get from [here](http://ceres-solver.org/installation.html). Once installed, you will probably have to fill in the Ceres related variables in the configuration step of your CGAL program. I think the variable you are looking for is `Ceres_DIR`, that must be the directory containing the CMake-config.txt or something like that.

OK. That means if I directly install the cgal[qt] via VCPKG, I still can not use Ceres, right? 
But actually, I have successfully installed Ceres and tried to specify the Ceres_DIR: [See my post in cgal-discussion](http://cgal-discuss.949826.n4.nabble.com/mesh-smoothing-method-with-Ceres-td4664844.html) There are always some errors. I will try it again, and report something if there are still some problems.


Thanks!
Best,
Frank

**Comment by maxGimeno** [comment]
I just checked, Ceres is available on vcpkg. Just `vcpkg.exe install ceres:x64-windows` and that's all. As long as you don't forget to use the toolchain in cmake you shouldn't have to worry about anything.

**Comment by Frank-Dz** [comment]
OK! Thanks again! 
I have successfully installed Ceres (via VCPKG). 
Currently I am dealing with another problem with VCPKG. The download speed is very very slow while installing cgal.
I think I'd better back to cmake rather than using VCPKG. (I have set the proxy according my VPN setting)


 .\vcpkg.exe install cgal[qt]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-any[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-heap[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-logic[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * boost-xpressive[core]:x64-windows
    cgal[core,qt]:x64-windows
  * freeglut[core]:x64-windows
  * icu[core]:x64-windows
  * jasper[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpq[core,openssl,zlib]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * opengl[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * pcre2[core]:x64-windows
  * qt5-3d[core]:x64-windows
  * qt5-activeqt[core]:x64-windows
  * qt5-base[core]:x64-windows
  * qt5-declarative[core]:x64-windows
  * qt5-gamepad[core]:x64-windows
  * qt5-imageformats[core]:x64-windows
  * qt5-script[core]:x64-windows
  * qt5-svg[core]:x64-windows
  * qt5-tools[core]:x64-windows
  * qt5-xmlpatterns[core]:x64-windows
  * tiff[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/88: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/local/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/local/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS2...
-- Downloadinghttp://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...


Anyway, Thanks again!


Best,
Frank
On 2/27/2020 16:42，Maxime GIMENO<notifications@github.com> wrote：

I just checked, Ceres is available on vcpkg. Just vcpkg.exe install ceres:x64-windows and that's all. As long as you don't forget to use the toolchain in cmake you shouldn't have to worry about anything.

**Comment by cgarmstr** [comment]
I gave up on using vcpkg and used the CGAL installer instead with success. As https://github.com/Frank-Dz commented above, it looks like vcpkg is timing out.
PS What is a good source of more simple examples? It's a very long time since I did any C++ programming - how do you walk through a triangulation outputting the indices (or similar) of the faces, vertices etc?

**Comment by Frank-Dz** [comment]
> I gave up on using vcpkg and used the CGAL installer instead with success. As https://github.com/Frank-Dz commented above, it looks like vcpkg is timing out.
> PS What is a good source of more simple examples? It's a very long time since I did any C++ programming - how do you walk through a triangulation outputting the indices (or similar) of the faces, vertices etc?

Hi@cgarmstr, currently, I successfully installed CGAL with QT5.
There are many many many problems while installing. I wrote down the process in Chinese. I am not sure if it is helpful.
https://blog.csdn.net/OOFFrankDura/article/details/104530955
Timeout problem is easy to solve. Set your proxy or download them manually.
If you wanna install QT there will be a big problem since msys2 seems not very easy to install.

Best,
Frank

**Comment by cgarmstr** [comment]
Hi Frank

I followed a YouTube video (can’t find which one) on installing Qt and the CGAL routines like draw_triangulation worked fine afterwards. I was installing on Windows 10 and using Visual Studio 19 at the generator, so I didn’t need msys2.

What I really want to do now  is use the Python interface to CGAL …

Cecil

**Comment by maxGimeno** [comment]
@cgarmstr for python you should wait a little if possible, I'm currently working on a pip package.
If you can't wait, you should check [this](https://github.com/CGAL/cgal-swig-bindings/wiki/Installation) out.

**Comment by Frank-Dz** [comment]
> @cgarmstr for python you should wait a little if possible, I'm currently working on a pip package.
> If you can't wait, you should check [this](https://github.com/CGAL/cgal-swig-bindings/wiki/Installation) out.

That's great! Looking forward to your great job!

**Comment by cgarmstr** [comment]
> @cgarmstr for python you should wait a little if possible, I'm currently working on a pip package.
> If you can't wait, you should check this out.

Any timescale on the Python pip package? Thanks.

**Comment by maxGimeno** [comment]
> > @cgarmstr for python you should wait a little if possible, I'm currently working on a pip package.
> > If you can't wait, you should check this out.
> 
> Any timescale on the Python pip package? Thanks.

Not really, I'm kind of stuck with some dependencies that I can't get to work on windows.
