### ISSUE TITLE
Shape detection: Attempt to detesselate mesh // Unclear points in the manual

### ISSUE THREAD

**Issue by thopiekar** [CGAL/cgal#4564]
## Issue Details

I'm trying to use efficient_RANSAC with Python bindings to detesselate a mesh. Right now, I'm focussing to do this on a simple cube (10x10x10):
![image](https://user-images.githubusercontent.com/1847437/76150216-33ea8080-60a8-11ea-9e39-dd590c63c976.png)
So the expected output of the efficient_RANSAC algorithm would be 6 planes.

From what I see in the docs, the algorithm expects surface points (location and normal) as you would get from a laser tracker or 3D scanner. Therefore, I implemented an algorithm which randomly and equally fills a triangle with surface points. Their normal is the same as the one from the triangle. Currently, efficient_RANSAC can't find any surfaces, which is surprising since my point cloud seems to be fine:
![Screenshot_20200307_174833](https://user-images.githubusercontent.com/1847437/76150409-7ad97580-60aa-11ea-9a92-61fee05c29ca.png)

So something I can understand is, that the parameters I use are not optimal for this use case. 
Therefore, I took a look into the documentation and I have trouble to understand what the efficient_RANSAC function expects as parameters.
![Screenshot_20200307_183503](https://user-images.githubusercontent.com/1847437/76150470-3a2e2c00-60ab-11ea-8e8c-0f25f8be94a1.png)

When working with any kind of functions, I expect something like units mentioned. For example, "normal_threshold" is 0.9 by default which shall be around 25deg, but what is 0.9 then? 25deg as  radians? AFAIK, the radians of 25deg is ~0.44, so the threshold is twice the radians?
Same for cluster epsilon: According to the docs it is "1% of bounding box diagonal". So is the input done on percent? In decimal values? Or the absolute maximum distance as described?

I have to admit that I'm a bit confused at this point and it would be great, if you could take a look onto my code and/or give me some help here. Because right now, I can't be sure how the detection is influenced by changing the values.

Thanks! :wink: 

## Source Code

https://github.com/tetonsim/is-cura-ui/blob/r20.0-tp-selection_using_cgal/SmartSlicePlugin/shape_detection/ShapeDetectedNode.py#L88

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux (doesn't matter I think)
* Compiler: Clang
* Release or debug mode: Release
* Specific flags used (if any): <Nope>
* CGAL version: 5.0.1
* Boost version: Whatever comes with Ubuntu Focal at the moment

## Files
[Generated points](https://github.com/CGAL/cgal/files/4302343/points.csv.log)
[Used mesh (STL)](https://github.com/CGAL/cgal/files/4302344/test.10.stl.log)

-------------------------------

PS: Something I can imagine is, that my points are "too optimal" in my case epsilon is often zero, if the plane is not slightly curved. However, that is only a wild guess.

**Comment by sgiraudot** [comment]
* The normal threshold is a threshold on the dot product between the estimated plane normal and the point's normal, that is to say the cosine of the angle (`cos(25°)=0.9`). I do agree this is not well documented (it's pretty much only specified in the [related example](https://doc.cgal.org/latest/Shape_detection/index.html#title6) which is not enough). I'll fix that
* The cluster epsilon is documented as a distance and _is_ therefore a distance. The _default value_ uses 1% of the bounding box diagonal in order to adapt to the point cloud's dimension, but it is never implied that the user-specified parameter should be a percentage.

**Comment by thopiekar** [comment]
Hello @sgiraudot !

Many thanks for your quick reply and your explanation!

Regarding the practical problems I have, do you have any explanation why the algorithm can't find any shapes on such an optimal point cloud? In case of the cube mentioned above, I should have optimal data to fit planes onto, right?

Thanks again!
- Thomas

**Comment by sgiraudot** [comment]
I guess it's a problem of parameters? If I load your points and do this:
```python
shapes = efficient_RANSAC(points, shape_map, epsilon=0.5, cluster_epsilon=1.0, planes=True)
print(len(shapes), "shapes(s) detected are:")
for s in shapes:
    print(" *", s)
```
Then I get the 6 faces correctly:
```
6 shapes(s) detected are:
 * Type: plane (0, 1, 0)x - -5= 0 #Pts: 400
 * Type: plane (-1, 0, 0)x - 5= 0 #Pts: 400
 * Type: plane (-1, 0, -0)x - -5= 0 #Pts: 400
 * Type: plane (0, 0, 1)x - 5= 0 #Pts: 400
 * Type: plane (0, 0, 1)x - -5= 0 #Pts: 400
 * Type: plane (-0, -1, 0)x - -5= 0 #Pts: 400
```

**Comment by sgiraudot** [comment]
To be clearer: documentation defines the cluster epsilon parameter as ["the spacing between two cells of the regular grid, so that two points separated by a distance of at most 22–√ cluster_epsilon are considered adjacent"](https://doc.cgal.org/latest/Shape_detection/index.html#title2), so using a multiple (2x or 3x for example) of the average spacing of the point cloud (see `CGAL::compute_average_spacing()`) for it is usually a good start.

**Comment by danston** [comment]
The updated docs are here #4574.
