### ISSUE TITLE
Protect CGAL code against min/max macros defined in `<windows.h>`

### ISSUE THREAD

**Issue by acgetchell** [CGAL/cgal#4665]
_Please use the following template to help us solving your issue._

## Issue Details

CGAL 5.0.2-1 appears to introduce a compilation bug on Windows, detected in AppVeyor:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h(245,47): note: expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from ..\tests\Ergodic_moves_3_test.cpp:11:
In file included from ..\include\Ergodic_moves_3.hpp:14:
In file included from ..\include/Manifold.hpp:14:
In file included from ..\include/Geometry.hpp:19:
In file included from ..\include/Foliated_triangulation.hpp:26:
In file included from C:\Tools\vcpkg\installed\x64-windows\include\CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from C:\Tools\vcpkg\installed\x64-windows\include\CGAL/Simple_cartesian.h:20:
In file included from C:\Tools\vcpkg\installed\x64-windows\include\CGAL/Cartesian/Cartesian_base.h:22:
In file included from C:\Tools\vcpkg\installed\x64-windows\include\CGAL/Kernel/global_functions.h:25:
C:\Tools\vcpkg\installed\x64-windows\include\CGAL/Kernel/hash_functions.h(60,53): error: too few arguments provided to function-like macro invocation
  std::size_t result = hash_value(iso_rectangle.min());
 
https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L3520

During a recent build:

https://github.com/acgetchell/CDT-plusplus/commit/1a8e0ad29df8b5d6831bb39c558f5fe9440562a1

Note the previous build did not have this problem:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/31998819
                                                  ^
## Source Code

I have a minimal project here:

https://github.com/acgetchell/CDT-test/

And the AppVeyor build shows the same error here:

https://ci.appveyor.com/project/acgetchell/cdt-test#L4260

## Environment

* Operating system (Windows, 64 bits):
* Compiler: Visual Studio 2017
* Release or debug mode: Release
* Specific flags used (if any): https://github.com/acgetchell/CDT-test/blob/master/cmake/StandardProjectSettings.cmake
* CGAL version: 5.0.2 (5.0.2-1 in `vcpkg`)
* Boost version: 1.72.0 and 1.72.0-1
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7-4, TBB 2020_U1-1

**Comment by acgetchell** [comment]
The breaking change is `vcpkg` updating the package from 5.0.2 to 5.0.2-1 on 2020-04-17:

https://github.com/microsoft/vcpkg/pull/10879

Which is a fix for https://github.com/microsoft/vcpkg/issues/10861 when CGAL added a dependency to Boost Interval.

**Comment by lrineau** [comment]
Hi Adam,

The issue is not due to the vcpkg package cgal, but probably to another dependency of CDT-plusplus that suddenly includes `<windows.h>` on Windows. That header from Windows SDK, defines `min` and `max` as macros, unless the macro `NOMINMAX` is defined.

CGAL used to take care of that issue using [protections against macros](https://stackoverflow.com/q/23022349/1728537), but recent changes in our test platforms have removed the checks for that issue. @maxGimeno can you please add `-DCGAL_INCLUDE_WINDOWS_DOT_H` to the compilation flags of one Windows test platform, and then fix the compilation issues in all branches? There are two methods, documented [in the CGAL developers manual at the section "min and max"](https://doc.cgal.org/latest/Manual/devman_portability.html#secvarious_problems).

In CGAL-5.0-branch, I see at least three headers with issues:
```
Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Sphere_3_do_intersect.h
78:                //        if(center[i] < (FT)bbox.min(i))
80:                //                d = (FT)bbox.min(i) - center[i];
83:                //        else if(center[i] > (FT)bbox.max(i))
85:                //                d = center[i] - (FT)bbox.max(i);

Kernel_23/include/CGAL/Kernel/hash_functions.h
60:  std::size_t result = hash_value(iso_rectangle.min());
61:  boost::hash_combine(result, hash_value(iso_rectangle.max()));
129:  std::size_t result = hash_value(iso_cuboid.min());
130:  boost::hash_combine(result, hash_value(iso_cuboid.max()));

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/AABB_traversal_traits_with_transformation.h
55:    AK::FT xtrm[6] = { c2f(bbox.min(0)), c2f(bbox.max(0)),
56:                       c2f(bbox.min(1)), c2f(bbox.max(1)),
57:                       c2f(bbox.min(2)), c2f(bbox.max(2)) };
87:    AK::FT xtrm[6] = { c2f(bbox.min(0)), c2f(bbox.max(0)),
88:                       c2f(bbox.min(1)), c2f(bbox.max(1)),
89:                       c2f(bbox.min(2)), c2f(bbox.max(2)) };
```
There are probably also issues in examples/demos/tests.

@acgetchell Until the patch is written and distributed, there is a workaround: your build system or you code can define the macro `NOMINMAX`, to that `<windows.h>` does not define `min` and `max` as macros.

**Comment by acgetchell** [comment]
Thanks @lrineau for the workaround suggestion!

It's passing now: https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/32289426
