### ISSUE TITLE
Header uses deprecated code

### ISSUE THREAD

**Issue by benlaurie** [CGAL/cgal#4707]
## Issue Details

`In file included from //home/ben/local/include/CGAL/linear_least_squares_fitting_3.h:27:
//home/ben/local/include/CGAL/Default_diagonalize_traits.h:65:18: error: 
      'diagonalize_selfadjoint_covariance_matrix' is deprecated:
      CGAL::Diagonalize_traits is a deprecated class that can lead to precision
      issues, please use CGAL::Eigen_diagonalize_traits
      [-Werror,-Wdeprecated-declarations]
    return Base::diagonalize_selfadjoint_covariance_matrix(cov, eigenval...`

This is with -Werror, of course.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
As announced in the release notes of CGAL 4.13, `CGAL::Diagonalize_traits` is now deprecated and `CGAL::Eigen_diagonalize_traits` should be used instead. Since Eigen is a third party library, some extra cmake sugar should be added so that it is automatically detected and used by default in CGAL.

With current releases, your `CMakeLists.txt` should look like something like:
```
find_package(CGAL QUIET)

if ( CGAL_FOUND )

  # Find Eigen3 (requires 3.1.0 or greater)
  find_package(Eigen3 3.1.0)
  if (EIGEN3_FOUND)
    include( ${EIGEN3_USE_FILE} )
  endif()

```

The usage of Eigen as default is triggered by the definition of the macro `CGAL_EIGEN3_ENABLED` which is done automatically once including the Eigen3 use file.
