### ISSUE TITLE
Debian package libcgal-qt5-dev required when using libcgal-dev with cmake

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#471]
Original bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804539

Background information:
The Debian packages for CGAL enable the additional CGAL componts Qt5, ImageIO, and Core (the latter two are not relevant here). The headers and libraries are put into packages libcgal11v5/libcgal-dev, with the exception of all Qt stuff which goes into its own pair of packages libcgal-qt5-11/libcgal-qt5-dev. This split was done to avoid that all reverse dependencies of CGAL need to depend on the Qt stack, even if they do not need it at all.

Using libcgal11v5/libcgal-dev without having libcgal-qt5-11/libcgal-qt5-dev installed does no longer work in 4.7. It definitely worked in 4.5, and according to the bug submitter also in 4.6.

Note: The examples are a better repro case than the demos since there it is clear that they actually do not need Qt.

Is there a way to support this use case again?

**Comment by lrineau** [comment]
Cc @bo0ts 

Its seems that each CGAL library should have its own export file. And CGALConfig.cmake would include only the needed export files.

**Comment by bo0ts** [comment]
That sounds like it should not happen, because there should not be an imported target if the library has been disabled during build.

Could it be that debian does something funny to install the different CGAL libraries? e.g. build all of them and then use `install(1)` to install all the specific files?

**Comment by lrineau** [comment]
The `CGAL_Qt5` target was not disabled during build. All full build of CGAL is done. But the CGAL installation is then split into several Debian packages, to avoid that the installation of the CGAL package needs to pull the Qt5 packages by default.

The problem here is to find a way such that the one can use `CGALConfig.cmake` without having `libCGAL_Qt5.so` on the machine, even if the build was done using Qt5. Could we have a `CGAL_Qt5Config.cmake`, for example, that `CGALConfig.cmake` would look for if required? That would require to split `CGALConfig.cmake` into parts, and also split `CGALExports.cmake`.

**Comment by lrineau** [comment]
If we find a solution, I think that will be a good reason to publish a bug-fix CGAL-4.7.1. Because packaging issues are an important matter.

My fault is that the CGAL package on Fedora is not modular. That is a known bug.

**Comment by lrineau** [comment]
@sloriot: I think Philipp should spend time (probably a few hours, let's say 2 hours) on that issue. That is an important packaging issue, that is worth a bug-fix CGAL-4.7.1.

**Comment by lrineau** [comment]
@joachim-reichel: as far as I can see CGAL-4.7 is already in Debian testing. Once we have a patch, would it be OK for you to ship the patch in the Debian package, without requiring that I publish CGAL-4.7.1? So far that would be the sole patch to CGAL-4.7. That is rather small for a bug-fix release. The bug only impacts packagers.

**Comment by joachim-reichel** [comment]
@lrineau: Yes, I can include a patch. No need for a 4.7.1 release from my point of view.
