### ISSUE TITLE
Unhandled exception when calling PMP::clip() in special case

### ISSUE THREAD

**Issue by dainamyki** [CGAL/cgal#4713]
## Issue Details

I am trying to clip a mesh, the clipper mesh is constructed from the points that lie on the mesh to be clipped(the points are interpolated on the edge of the mesh). In other words, the boundary of the clipper mesh is a contour curve of the mesh to be clipped. The cube is the simplest example(fig 1). But there is an unhandled exception(Unhandled exception at 0x77024192: Microsoft C++ exception: CGAL::Assertion_exception at memory location 0x003FCA50.) However, if I expand the clipper mesh a bit(fig 2), it works fine. 

Why is there an unhandled exception? Is the clip function not supposed to deal with the former case?
![Capture](https://user-images.githubusercontent.com/43584030/81425884-5c354080-9126-11ea-8a73-8523b749c679.PNG)
![Capture1](https://user-images.githubusercontent.com/43584030/81425889-5d666d80-9126-11ea-92b4-d57b46185cd0.PNG)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* CGAL version: 4.14

**Comment by MaelRL** [comment]
As indicated in the [documentation of the function](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99), the clipper must bound a volume, which is not the case here.

Note that there is an overload with a 3D plane ([here](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga5bf228a516a46f6d1c80937067a17f7e) if your four points are coplanar.

**Comment by dainamyki** [comment]
Thanks for your reply. I 've noticed the requirement of the clipper, but I don't understand how is that the first case does not bound a volume and the second case does. I would really appreciate it if you could elaborate.

**Comment by sloriot** [comment]
Your clipper is a square it does not define a volume, it is simply a polygon is space. If you give a plane instead it define a half-space. Even if undocumented, the clipping code is able to handle open clipper if there is no ambiguity locally to the intersection. In the first case, I guess the square does not intersect the cube entirely.

**Comment by dainamyki** [comment]
Thanks for the reply. My intension is to cut a closed mesh with a contour curve that is on the surface of the mesh

- The points of the contour are interpolated on the edge of the mesh to be clipped.

-  I have triangulated the curve to construct a clipper mesh. 

- The clipper mesh is not on a plane, it's curved.  


There is the unhandled exception as well. That's why I test it with the cube example.  

Any suggestions about how to make this work? The contour points are on the mesh, so the clipper mesh should intersect the mesh entirely.

If it is the case that clipper mesh does not intersect the cube entirely, how should I fix it?
I have attached the meshes. 
[meshes.zip](https://github.com/CGAL/cgal/files/4613348/meshes.zip)

**Comment by sloriot** [comment]
Since it seems that you have all the intersection points of your surface with the mesh you want to split, I would use Euler functions [`split_edge`](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga8a7629a2a0659ca059081eae8cedca3d) and [`split_face`](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gac0e8aebb3072d5dd67487ce40205f318) to refine the mesh and insert insertion edge with your surface. Keep track of those edge and put them in a constrained edge property map to split the refined mesh either by using the function [`split()`](https://cgal.geometryfactory.com/CGAL/doc/master/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gaa491feee9e41f725332bea0ea1215578) available in master and upcoming 5.1 release or use the function [`connected_components`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__keep__connected__components__grp.html#gabe2052b2281e1e628e68d8fea94be2d9) together with [`Face_filtered_graph`](https://doc.cgal.org/latest/BGL/structCGAL_1_1Face__filtered__graph.html) to do the same thing.
