### ISSUE TITLE
CGAL Malware Security Concerns

### ISSUE THREAD

**Issue by BobThome** [CGAL/cgal#472]
Due to malware detected on CGAL.org, I am unable to use the website / library at the workplace. The website is blocked and prohibited from use due to this apparent malware detection. 

This can be verified by using various malware website scanners (i.e. quttera.com) 
Can this be resolved?

**Comment by afabri** [comment]
The reason is a link to
raw.githubusercontent.com

that is on quttera's list of referenced blacklisted domains/hosts: 1

so I guess this is a false positive.

andreas


On 10/11/2015 03:33, BobThome wrote:
> Due to malware detected on CGAL.org, I am unable to use the website /
> library at the workplace. The website is blocked and prohibited from use
> due to this apparent malware detection.
>
> This can be verified by using various malware website scanners (i.e.
> quttera.com)
> Can this be resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/issues/472>.
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by sloriot** [comment]
@BobThome are you OK to close this issue?
