### ISSUE TITLE
segmentation fault in classification

### ISSUE THREAD

**Issue by Ciaran1981** [CGAL/cgal#4816]
## Issue Details
Hello,

When dealing with a point cloud of typical size 100ks - 1 million points+, the classification plugin seg-faults during the training stage of the algorithm. I have experienced this with multiple datasets. I lthought this may have been due to the python binding which I used first, but this also occurs using the C++ API. These examples only appear to work on very small clouds (like the demo dataset which is only 30k points).  

As an additional note, it would also be good for the ply header data types required to be made specific for this somewhere (apologies if I have missed this from the docs of course).

## Source Code

The only change is the input data.ply which has the same header and fields as the test dataset, hence I have not repeated the source code here.

example_ethz_random_forest.cpp 

example_generation_and_training.cpp

## Environment

* Operating system (Linux, 64 bits):
* Compiler: g++
* Release or debug mode: 
* Specific flags used (if any):
* CGAL version: 5
* Boost version: 1.7

Thanks

**Comment by sgiraudot** [comment]
Classification should work fine on large data sets (the only limitation will be the memory available, but it's been tested fine on up to several dozens of millions of points on a laptop with 16GB of RAM), so the bug definitely comes from somewhere else.

I've downloaded the data set you provided [on Stack Overflow](https://stackoverflow.com/questions/62512676/point-cloud-classification-cgal). First, I notice that the training data is stored on a float property named "scalar_training", so I will assume you replaced:
```c++
  boost::tie (label_map, lm_found) = pts.property_map<int> ("label");
```
with
```c++
  boost::tie (label_map, lm_found) = pts.property_map<float> ("scalar_training");
```
and changed the type accordingly (using a float property map), otherwise you should get an error that says that the label map was not found.

If I do that, I have indeed a segfault.

If I display the content of your scalar_training property, I see that some points are given the value 4. Considering you have only 3 labels defined, the only acceptable values should be 0, 1 and 2 (and -1 for unclassified points, see [the documentation of the `train()` function](https://doc.cgal.org/latest/Classification/classCGAL_1_1Classification_1_1ETHZ_1_1Random__forest__classifier.html#a7c0b299cb5829f598f395bcc16df72fa)). Using higher values will undoubtfully lead to segfaults as there is no label at index 4.

To fix this:
- either your input has more than 3 labels, and in that case you should create labels accordingly (line 86 in the ETHZ example)
- or the indices contained in your input file do not match the expected format (= they should be contiguous and match the index of the label in the label set), and in that case you should map your input indices to indices in the label map

**Comment by sloriot** [comment]
@sgiraudot is it easy to add a precondition checking that at the beginning of the run?

**Comment by afabri** [comment]
Can these codes run in debug mode, or do we need such a precondition step even in release mode?

**Comment by sgiraudot** [comment]
Yes, I can definitely add a precondition (the random forest fills a matrix at the start of the `train()` function, I can check index overflow there). I don't think it's a good idea to add it in release mode though (= I don't want to run 3M tests if I know my 3M point cloud has the correct indices).

**Comment by sloriot** [comment]
Note that you can have a function that is doing the test and return true/false that is called in a precondition and also allows the user to call it to make sure everything is fine.

**Comment by sgiraudot** [comment]
That's a good idea. I added this mechanism to [my pending Small Feature on Classification](https://github.com/CGAL/cgal/pull/4626) as it modifies the documentation.

**Comment by Ciaran1981** [comment]
Hello,

Apologies - I uploaded the wrong point cloud (had many with similar names). I had indeed changed the datatypes, fields and no. of classes but I hadn't ordered them correctly (-1,0,1,2,3) and now that I have it works!

Thanks for your help and time
