### ISSUE TITLE
libRS/MPFI on magritte are wrong

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4880]
### Issue Details

Until recently, commit 5ae732d2419e, MPFI was actually not correctly tested in CGAL. Now we see errors on magritte:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-204/Algebraic_kernel_d/TestReport_magritte_x86_64-apple_highsierra_clang1000-release-64bits.gz
```
/usr/local/Cellar/librs/3.1.0/include/mpfi.h:47:9: error: unknown type name '__gmp_const'
typedef __gmp_const __mpfi_struct *mpfi_srcptr;
        ^
```

`__gmp_const` is no longer defined in recent GMP version. @danston, where have you found that Homebrew tap for librs? Try to find if there is a newer version fixing that incompatibility with GMP.

**Comment by danston** [comment]
@lrineau I took the librs lib from [here](https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyRS3) and then created a formula for installing it via homebrew. The version that I use in that tap is 3.1.0. I will check if there is a newer version and/or if I can fix it.

**Comment by lrineau** [comment]
If you cannot find a newer version, then uninstall RS. That is not an important dependency of CGAL.

**Comment by danston** [comment]
I have updated the test-suits both for monet and magritte. I had to reinstall some libraries and/or update them to the newer versions. I have also removed the RS one since it bugs and I did not find a newer version. In fact, even the original website where I took the previous version is down (not sure if it is temporary or permanent). The monet test-suite should also run now whenever I leave the laptop in the office. I will wait for the next week's test-suit results and if something else is broken, I will try to fix it, too. 

cc @maxGimeno

**Comment by MaelRL** [comment]
@danston @lrineau Is this resolved?

**Comment by maxGimeno** [comment]
@maelRL Magritte is dead and burried, so I guess issues about its environment don't matter anymore.

**Comment by sloriot** [comment]
Shall I try to add it on `cezanne` ?

**Comment by danston** [comment]
@MaelRL Yes, Magritte is not working though I have fixed the same problem on Monet.

**Comment by danston** [comment]
Should we close this one? Old Magritte is dead and new one does not have these problems AFAIK.

**Comment by lrineau** [comment]
I agree.
