### ISSUE TITLE
Expr: normal_length > FT(0)

### ISSUE THREAD

**Issue by XGL96** [CGAL/cgal#4930]
## Issue Details

I tried to run the demo *region_growing_on_point_set_3.cpp*, but it caused an error that
```cpp
terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: normal_length > FT(0)
File: /usr/local/include/CGAL/Shape_detection/Region_growing/Region_growing_on_point_set/Least_squares_plane_fit_region.h
Line: 207
Aborted (core dumped)
```
It looks like this is the length of the normal vector in my file not reaching some preset value? But I'm not quite sure what that means, it seems to me that the normal vector should be three numbers between -1 and 1, and I was able to use my data to run *Shape_detection/efficient_RANSAC_basic.cpp* with no error. 

I also used
```cpp
std::cout << input_range.point_map()[14] << std::endl;
std::cout << input_range.normal_map()[14]  << std::endl;
```
to check if it read my data correctly, it worked.

The following is what my data looks like.
```tex
7408152
20.585397720336914 9.056777954101562 2.0815000534057617 -0.03264912590384483 -0.9233172535896301 -0.3826477527618408
20.485607147216797 9.067708015441895 2.0687999725341797 0.6905004978179932 -0.6010831594467163 -0.4023779630661011
20.54115867614746 9.074089050292969 1.607699990272522 -0.9521046280860901 -0.2930554449558258 -0.08726540207862854
20.572612762451172 9.069365501403809 1.144700050354004 -0.10202381759881973 -0.5273625254631042 0.8434926867485046
20.46369171142578 9.080107688903809 1.138200044631958 -0.20005744695663452 -0.8438513875007629 0.49788734316825867
20.520023345947266 9.087638854980469 0.6741999983787537 -0.015709752216935158 -0.9980928897857666 0.05969705805182457
26.468280792236328 10.963347434997559 -0.2996000051498413 0.25218355655670166 -0.9643803834915161 0.07983700931072235
...
```

## Source Code

The demo was Shape_detection/region_growing_on_point_set_3.cpp on https://doc.cgal.org/latest/Shape_detection/index.html#Chapter_Shape_Detection.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):    Linux
* Compiler:    g++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
* Release or debug mode:    debug?
* Specific flags used (if any):    -lgmp
* CGAL version:    5.0.3
* Boost version:    1.65
* Other libraries versions if used (Eigen, TBB, etc.):    Eigen 3.3.4

**Comment by danston** [comment]
Hi @XGL96. The error indicates that one of your normals has zero length. I will check your data and come back to you with more explanation a bit later.

**Comment by danston** [comment]
A few other remarks:
- Please provide the full file with all data. The piece you provided is not enough.
- Provide the exact parameters that you use to run the region growing example on your data. Or are they the same as in the `region_growing_on_point_set_3.cpp` example?
- While the RANSAC example could simply ignore normals with the zero length, it does not yet mean that it handled them correctly. In the region growing example, the length of the normal is controlled only against zero (it is not really a preset value), because otherwise, it could lead to the corrupted results.

**Comment by XGL96** [comment]
Thanks for the reply, my parameters are the default ones in the example.

The download link for the data I used is \
https://drive.google.com/file/d/1qsDy0qYl2Cro31_6nLKLatZ2iECH6sJL/view?usp=sharing



> A few other remarks:
> 
> * Please provide the full file with all data. The piece you provided is not enough.
> * Provide the exact parameters that you use to run the region growing example on your data. Or are they the same as in the `region_growing_on_point_set_3.cpp` example?
> * While the RANSAC example could simply ignore normals with the zero length, it does not yet mean that it handled them correctly. In the region growing example, the length of the normal is controlled only against zero (it is not really a preset value), because otherwise, it could lead to the corrupted results.

**Comment by XGL96** [comment]
You're right, I checked my data and there are 2436 points in which the length of NORMAL is 0.

Thanks again for your answer.

**Comment by danston** [comment]
Yep, I also checked your data and you have normals, which are fully zero:
![Screenshot 2020-08-18 at 10 34 56](https://user-images.githubusercontent.com/8123586/90490175-960edd80-e13e-11ea-82c3-e00a1e9e00bd.png)

**Comment by danston** [comment]
Try to fix these normals and then I hope you will be able to run the algorithm without any assertions. 

One more thing: you can still run these data in the release mode and see the results. Some regions will probably be corrupted or points with wrong normals won't be included in any region, but at least you get an output. 

Second thing: do not use the default parameters. It is quite unlikely that they will produce reasonable results on your data, which are quite complex. You should play around with the parameters in order to get the results you expect.
