### ISSUE TITLE
Finding PC2 axis using PCA Algorithm

### ISSUE THREAD

**Issue by dhirajsuvarna** [CGAL/cgal#4948]
## Issue Details

Principal Component Analysis API does not give the PC2 axis (component)

## Details

I am refereing this to do the PCA on my 3D Model - https://doc.cgal.org/latest/Principal_component_analysis/index.html
Using this it is clear that if I fit a line to the 3D data, it will give me the PC1 axis.
However, I am interested in both PC1 and PC2 axis and am strugling to figure out how can this be achieve. 

Please let me know if I am asking in the wrong place as I didn't find any other forum for asking conceptual doubts. 
Any help is greatly appreciated.

**Comment by sloriot** [comment]
You need to fit a plane, using [this function](https://doc.cgal.org/latest/Principal_component_analysis/group__PkgPrincipalComponentAnalysisDLLSF3.html#gad39edb9f84ea2c280317e6c6c6146911).

It is used in [this example](https://doc.cgal.org/latest/Principal_component_analysis/index.html#title6) (note in the example `dimension_tag<N>` has N = 2 because the triangle areas is used for the fitting and not only the points).

**Comment by dhirajsuvarna** [comment]
@sloriot So can a plane be fitted to the points?

**Comment by dhirajsuvarna** [comment]
@sloriot Out of curiosity, I tried to use `dimenstion_tag<N>` with `N=2` and `N=0` but both are giving same results. 
When should be one be used over other while fitting the plane?

**Comment by sloriot** [comment]
If your points are really on a plane the dimension will not change anything. When using dimension 2, the area of the triangles are somehow used as a weight for the fitting.
