### ISSUE TITLE
bool do_intersect(Plane_3, Plane_3,Plane_3)

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5013]
## Issue Details

This function is not documented, but it seems to be implemented.   It does not compile with VC++, not for  the `Exact_predicates_exact_constructions_kernel` and not even for `Simple_cartesian<double>`. 

The implementation calls the intersection function. That is it makes a construction.   My guess is that it could be 
made robust by using `Are_parallel_3`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 
* Compiler:  VC++
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: master
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by janetournois** [comment]
According to the documentation, `do_intersect(Plane_3, Plane_3, Plane_3)` exists for the Spherical kernel :
[doc](https://doc.cgal.org/latest/Kernel_23/group__do__intersect__spherical__grp.html#ga020f0d63c70182b733b1997b506f445d)

**Comment by lrineau** [comment]
You could have save me some time and point to the implementation:
Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h line 573:
https://github.com/CGAL/cgal/blob/aaf1e8cd38b05988fb72465402be373931cace4d/Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h#L1573-L1579

And the code for the construction is at:
https://github.com/CGAL/cgal/blob/aaf1e8cd38b05988fb72465402be373931cace4d/Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h#L185-L235

If any two of the three planes are equal (according to `Equal_3`), then the predicate is a `do_intersect` between two planes.

If any two of the three planes are non-equal but parallel, then the intersection is empty.

Otherwise, the intersection of the first two planes `pl1` and `pl2` is a line `l`, and the intersection is then the intersection between the plane `pl3` and that line `l`. You cannot make that predicate exact with just tests with `Are_parallel_3`. The real predicate must compute the rank of two matrices, and the intersection is non empty only if the two ranks are equal. See http://www.emathematics.net/posreltresplanos.php

I think that predicate is not documented because it can be exact only with an exact number type.

For the spherical kernel, the `do_intersect(Plane_3, Plane_3, Plane_3)` is documented but its implementation is the one of the linear kernel (and thus inexact with `CGAL::Epick`).

I suggest we close this issue.
