### ISSUE TITLE
Deleting triangles

### ISSUE THREAD

**Issue by krober10nd** [CGAL/cgal#5164]
Hello all, I see there's methods to remove vertices from a Delaunay triangulation but is there a way to remove a specific cell from a 2D triangulation object? 

My use case is trying to triangulate a non-convex object. I'd like to delete the triangles that are outside my polygonal region, which is not convex. 

Thanks for any help

**Comment by sloriot** [comment]
You cannot remove cells but you can mark cells as being outside of your domain like in it done in the [2D mesh generation package](https://doc.cgal.org/latest/Mesh_2), by using [https://doc.cgal.org/latest/Mesh_2/classCGAL_1_1Delaunay__mesh__face__base__2.html] face base type (see the doc of the [concept](https://doc.cgal.org/latest/Mesh_2/classDelaunayMeshFaceBase__2.html) for the methods). You can also simply add an [info](https://doc.cgal.org/latest/Triangulation_2/classCGAL_1_1Triangulation__face__base__with__info__2.html) to your face base. Otherwise, you will have to import your triangulation into another data structure like an [HDS](https://doc.cgal.org/latest/HalfedgeDS/classHalfedgeDS.html) or a [Surface_mesh](https://doc.cgal.org/latest/Surface_mesh/).

**Comment by krober10nd** [comment]
So then once these faces are marked then when I compute some connectivity, it will ignore them and only return for the in domain faces?

**Comment by sloriot** [comment]
With the triangulation data structure no, it is only a mark but I guess you can write some filter iterators if you want to skip them. If you export the triangulation into a HDS based structure then it will.

**Comment by krober10nd** [comment]
thanks!
