### ISSUE TITLE
Efficient_ransac fails to detect cylinder

### ISSUE THREAD

**Issue by carmaud** [CGAL/cgal#5250]
## Issue Details

Efficient_Ransac is unable to detect/fit a cylinder primitive in a test point cloud ([test_cloud.zip](https://github.com/CGAL/cgal/files/5651970/test_cloud.zip)). The point cloud is generated by sampling a cylinder mesh and adding small per-vertex displacement (max offset ~ 0.5 x epsilon parameter used in the detection). Note that there are basically no outliers in the point set.

## Source Code

I'm using the demo codeat [https://doc.cgal.org/latest/Shape_detection/Shape_detection_2efficient_RANSAC_with_parameters_8cpp-example.html](url). The parameters are slightly modified wrt original code, using probability = 0.001, cluster_epsilon = 0.1, epsilon = 0.01. With these parameters, the detection fails.
Increasing min_points from 200 to a value (e.g. 1000) **higher** than the number of points in the point cloud (i.e. 705) results in the detection of the cylinder; however, most points are still marked as unassigned.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): OSX 10.15.7
* Compiler: clang 12
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.1.1
* Boost version: 1.74.0
* Other libraries versions if used (Eigen, TBB, etc.):
gmp 6.1.2
mpfr 3.1.5

**Comment by sgiraudot** [comment]
The distance between 2 pairs of closest points is larger than the value you used for `cluster_epsilon`. If I set `cluster_epsilon=25` for example, then the cylinder is detected. Note that detection of cylinders works better since the integration of https://github.com/CGAL/cgal/pull/5234, so I would advise to use the `master` version of CGAL.

The fact that any shape is detected with `min_points` higher than the number of points is worrying, I'll have a look at it.

**Comment by sgiraudot** [comment]
Alright, so the second bug (`min_points>#points` returning shapes) is silly: the algorithm uses a dummy value `std::numeric_limits<std::size_z>::max()` to detect whether the minimum number of points was provided by the user or not, in which case it's computed as 10% of the input points. The problem is that it tests if `min_points` is higher than the number of points instead of testing that it is equal to this dummy value, which means that if you ask for `min_points` higher than the number of points, it will result in this value being replaced by 10% of the number of points… I'll make a fix.

**Comment by carmaud** [comment]
Thanks for addressing this and for your clarification. It looks like I misunderstood the role of the parameter cluster_epsilon. 
May I suggest to rephrase/extend the documentation, so that its effect becomes clearer to other users as well?
What I think is not clear from the doc is whether cluster_epsilon affects the randomized selection of shapes (e.g. by limiting the set of points that can be considered inliers) or is used in a connected component search after the main ransac procedure to only retain the largest connected component (with cluster_epsilon being the max distance for adjacency between points).
In the latter case, does min_points denote the size of the support before or after the detection of the largest component?

**Comment by sgiraudot** [comment]
In our framework, a shape _is_ a connected component (as shown [in this figure](https://doc.cgal.org/latest/Shape_detection/index.html#fig__Efficient_RANSAC_parameter_connectivity)). Indeed, the minimum number points is thus a limit on the connected component (not the global detected plane/infinite cylinder/etc.), so applied _after_ identifying connected components.

I'll see how we can improve doc on this point. Thanks for reporting this issue!
