### ISSUE TITLE
CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3> mesh

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5307]
Hi,

Can someone give an example how to create a mesh i.e. a cube for this mesh data-structure?
`CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3> mesh`

The reason for asking is that I only see examples by reading .off file but none of examples shows how to construct mesh from scratch.

**Comment by MaelRL** [comment]
The examples of `CGAL::Surface_mesh` do not show the lowest level mesh manipulations because these are rather complex operations as one has to maintain manually the data structure.

Higher-level mesh edition functions that automatically maintain the graph validity are provided instead in the package BGL: https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html.

You can find inspiration for the usage of these functions (as well as lower-level mesh manipulation functions) in this file: https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/generators.h.
