### ISSUE TITLE
Crash in Windows version of simple 3D Delaunay triangulation program

### ISSUE THREAD

**Issue by FlakPacket** [CGAL/cgal#5396]
I have the following simple program that creates a 3D Delaunay triangulation:

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Delaunay_triangulation_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Delaunay_triangulation_3<K, CGAL::Fast_location> Delaunay;
typedef Delaunay::Point Point;

Delaunay Triangulate()
{
  Delaunay tri;
  for (int i=0; i<10; i++)
        tri.insert(Point(i+1, i+2, i+3));

  return tri;
}

int main()
{
  std::cout << "About to triangulate..." << std::endl;
  const auto tri = Triangulate();
  std::cout << "Triangulated successfully!" << std::endl;
  return 0;
}
```

When I compile and run this program on Windows in the 64-bit Debug configuration, it crashes while executing the `return tri` line. The debugger shows a read access violation during the CGAL `~Triangulation_hierarchy_3()` deconstructor. I am using CGAL 5.1.1 with vcpkg, and building the application with Visual Studio 19.

The program behaves fine on Linux compiled with gcc. Any ideas what is causing the problem on Windows?

**Comment by mglisse** [comment]
If you replace `{` with `{{` and `}` with `}}` in Triangulate (to disable gcc's NRVO), it segfaults with gcc as well.

**Comment by MaelRL** [comment]
This seems to stem from:
```
  other.hierarchy[i] = nullptr;
```
in the call to `Triangulation_hierarchy_3(Triangulation_hierarchy_3&& other)`; context: https://github.com/CGAL/cgal/blob/master/Triangulation_3/include/CGAL/Triangulation_hierarchy_3.h#L119), added in PR https://github.com/CGAL/cgal/pull/4496. 

The `clear()` (and the destructor) of the triangulation hierarchies do not check if `hierarchy[i]` (`i` in `[0;maxlevel[`) actually holds a triangulation hence segfault while the local hierarchy gets destroyed after its value got moved to the variable `tri`.

This could be fixed by just checking if `hierarchy[i]` holds something in `clear()`, `~Triangulation_hierarchy_3`, etc. but I feel like the better fix would be to (re-)initialize it in the constructor, that is something like:
```
- other.hierarchy[i] = nullptr
+ other.hierarchy[i] = new Tr_Base(traits);
```
The destructor will take care of the delete.

**Comment by lrineau** [comment]
That would make a throwing constructor.

I am surprised, I thought about that (the issue with `clear()`) during the development of PR ##4496, but it seems I got it wrong

**Comment by lrineau** [comment]
> That would make a throwing constructor.

Non-throwing move constructors are really important for the efficiency, if you want to use the type in a `std::vector`.

**Comment by GilesBathgate** [comment]
Why not just use std::swap for the move:

```c++
riangulation_hierarchy_3 & operator=(Triangulation_hierarchy_3&& other)
    noexcept( noexcept(Triangulation_hierarchy_3(std::move(other))) )
  {
    static_cast<Tr_Base&>(*this) = std::move(other);
    hierarchy[0] = this;
    for(int i=1; i<maxlevel; ++i) {
      std::swap(hierarchy[i],other.hierarchy[i]);
    }
    return *this;
  }
  ```

**Comment by MaelRL** [comment]
`hierarchy[i]` is not initialized before the swap, so when `other` gets deleted, you will have issues as `other.hierarchy[i]->clear()` is a segfault, and `delete other.hierarchy[i]` is deletion of an uninitialized pointer.

**Comment by GilesBathgate** [comment]
@MaelRL Yeah you are right, I was thinking of the Move assignment operator. Probably the simplest ix would be as you say to check for null in `clear()`

```c++
template <class Tr>
void
Triangulation_hierarchy_3<Tr>::
clear()
{
  for(int i=0;i<maxlevel;++i)
    if(hierarchy[i])
      hierarchy[i]->clear();
}
```

**Comment by lrineau** [comment]
> @MaelRL Yeah you are right, I was probably thinking of the move assignment operator. Probably the simplest fix would be as you say to check for null in `clear()`
> 
> ```c++
> template <class Tr>
> void
> Triangulation_hierarchy_3<Tr>::
> clear()
> {
>   for(int i=0;i<maxlevel;++i)
>     if(hierarchy[i])
>       hierarchy[i]->clear();
> }
> ```

That is almost what I have implemented in my first commit https://github.com/CGAL/cgal/pull/5409/commits/ce75d010e93c6cc0ca0ed3997d925b89d7eb161b of PR https://github.com/CGAL/cgal/pull/5409. But that is unclean, and I would like to avoid the hierarchy to allocate the triangulations levels `1` to `maxlevel-1` on the heap. I have tried that in a second commit https://github.com/CGAL/cgal/pull/5409/commits/b4256accb94cbecef9413b894a87d25589696f98, but I have a segfault to debug.

**Comment by afabri** [comment]
What is the problem/disadvantage with a construction on the heap?

**Comment by lrineau** [comment]
> What is the problem/disadvantage with a construction on the heap?

With heap allocation for a default-constructed object, the move-constructor cannot be at the same time `nothrow` and fully-compliant with the norm.

**Comment by mglisse** [comment]
> With heap allocation for a default-constructed object, the move-constructor cannot be at the same time `nothrow` and fully compliant with the C++ norm.

I think it can, it will simply `terminate` in case of allocation failure (which might not be desirable, but it might also not matter much). Now the heap allocation is not free (pun!), I don't know how often people move triangulations...

**Comment by lrineau** [comment]
> > What is the problem/disadvantage with a construction on the heap?
> 
> With heap allocation for a default-constructed object, the move-constructor cannot be at the same time `nothrow` and fully compliant with the C++ norm.

Well... I found out what is wrong... A default-constructed CGAL triangulation is of dimension -1 (no vertex) but its construction allocates to create the infinite vertex. Since CGAL-5.1, a moved-from triangulation is of `dimension()==-2` with `number_of_vertices() == -1`. Such a triangulation is considered valid by `Triangulation_3::is_valid()`, but using it will fail. The only accepted action on it is its destruction. I do not know how we should document that. I am searching for a similar behavior from the STL.

**Comment by lrineau** [comment]
> I don't know how often people move triangulations...

**Comment by MaelRL** [comment]
The `Triangulation_3::is_valid` really should not be returning `true` though, since `this->infinite_vertex() != Vertex_handle()` is tested. That check might return `true` because the handle is not put to `nullptr` in the moved-from, but the test is pretty much intended to mean `!_tds.vertices().empty() && this->infinite_vertex() == tds.vertices().front()`, which is `false`.

"partially-formed" is used here: https://www.kdab.com/stepanov-regularity-partially-formed-objects-vs-c-value-types/ to qualify "only able to be initialized or destroyed", but that doesn't seem to me to be the case here: you can call member functions of the triangulation such as dimension(), etc., you can just not insert anything because the infinite_vertex() is broken. (The traits could also be broken if it had a state).

**Comment by lrineau** [comment]
> The `Triangulation_3::is_valid` really should not be returning `true` though, since `this->infinite_vertex() != Vertex_handle()` is tested. That check might return `true` because the handle is not put to `nullptr` in the moved-from, but the test is pretty much intended to mean `!_tds.vertices().empty() && this->infinite_vertex() == tds.vertices().front()`, which is `false`.

Do you think we should fix `is_valid()` that way? I wonder if it might break user code.

**Comment by lrineau** [comment]
> "partially-formed" is used here: [kdab.com/stepanov-regularity-partially-formed-objects-vs-c-value-types](https://www.kdab.com/stepanov-regularity-partially-formed-objects-vs-c-value-types/) to qualify "only able to be initialized or destroyed", but that doesn't seem to me to be the case here: you can call member functions of the triangulation such as dimension(), etc., you can just not insert anything because the infinite_vertex() is broken. (The traits could also be broken if it had a state).

It seems "partially-formed" was defined in the book [*Elements of Programming*](http://elementsofprogramming.com/) from 2009. Arthur O’Dwyer criticized it [in his blog in 2018](https://quuxplusone.github.io/blog/2018/05/10/regular-should-not-imply-default-constructible/), because the need it predates C++11. I tend to respect O’Dwyer's opinion. Marc Mutz from KDAB seems the only advocate of "partially-formed", nowadays.

**Comment by MaelRL** [comment]
> > The `Triangulation_3::is_valid` really should not be returning `true` though, since `this->infinite_vertex() != Vertex_handle()` is tested. That check might return `true` because the handle is not put to `nullptr` in the moved-from, but the test is pretty much intended to mean `!_tds.vertices().empty() && this->infinite_vertex() == tds.vertices().front()`, which is `false`.
> 
> Do you think we should fix `is_valid()` that way? I wonder if it might break user code.

I do not think it is very important, since anyway `Triangulation_3::is_valid()` cannot exhaustively test the validity of the triangulation: it cannot test the validity of the traits, for example.

My point was that `Triangulation_3::is_valid()` is just a triangulation function like `Triangulation_3::dimension()` and the validity preconditions for functions to be callable in a moved-from triangulations are not described by `Triangulation_3::is_valid()`. Therefore, it does not seem to me like the moved-from triangulation is in an unusual state (i.e., "valid but cannot be used") compared to another kind of moved-from class object.

**Comment by lrineau** [comment]
Fixed by the merge of PR https://github.com/CGAL/cgal/pull/5409.
