### ISSUE TITLE
How to set tolerance when comparing Kernels?

### ISSUE THREAD

**Issue by aroadktw** [CGAL/cgal#5512]
Hi.

I'm using CGAL version 5.2#1 installed via vcpkg in window 10.

What I'm trying to do is get vertices and indices by file and convert it to Nef-polyhedron.

And some polygons are not coplanar by 0.00000001 or lesser.

How to allow tolerance when comparing kernels?

**Comment by pentacular** [comment]
I don't think that kernel tolerance makes sense, but you might be able to repair the mesh before converting it to a nef-polyhedron.

Triangulation will ensure that your polygons do not go out of plane.

Maybe also take a look at https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPRepairing ?

**Comment by sloriot** [comment]
I agree with @pentacular.

You should try to triangulate your faces using [triangulate_faces()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga1e9c8778755b2d1741f47736ba6e4b45). Maybe you can also use corefinement based Boolean operations as described [here](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#title13) instead of Nef.

If you want to stick with Nef, the function [ OFF_to_nef_3()](https://doc.cgal.org/latest/Nef_3/group__PkgNef3IOFunctions.html#gaeb31b20d2824c500c4a12e284667dfce) should be used when the input is not clean.

**Comment by aroadktw** [comment]
Thanks for replying @pentacular @sloriot !

But I'm trying to use Nef-polyhedron because I don't want to triangulate them. I want to keep them in polygons, in same planes...

Well, if there is no way to set tolerance then i have to figure a way out.

Thanks!
