### ISSUE TITLE
triangulate_and_refine_hole fails 

### ISSUE THREAD

**Issue by sandboxgod** [CGAL/cgal#5681]
## Issue Details

So we are having a problem where we have been unable to fill the holes at the bottom of this arch. I was hoping I could get some tips on the best way to fill the holes at the bottom of this model.

Below is the errors I receive when I try to fill the holes:

```
CGAL error: assertion violation!
Expression : Q.empty() || (Q.front() == Q.back())
File       : /Users/richardosborne/homebrew/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
Line       : 776
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
Ignoring exception 
CGAL error: assertion violation!
Expression : Q.empty() || (Q.front() == Q.back())
File       : /Users/richardosborne/homebrew/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
Line       : 776
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
Ignoring exception 
CGAL warning: check violation!
Expression : false
File       : /Users/richardosborne/homebrew/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
Line       : 1102
Explanation: Returning no output using Delaunay triangulation.
```

## Source Code

I attached an example so that you can repro the issue (model has been attached as well):
[cannotFillHolesExample.zip](https://github.com/CGAL/cgal/files/6429516/cannotFillHolesExample.zip)

```
Below is the source 

#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/compute_normal.h>
#include <CGAL/Polygon_mesh_processing/connected_components.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Polygon_mesh_processing/measure.h>
#include <CGAL/Polygon_mesh_processing/remesh.h>
#include <CGAL/Polygon_mesh_processing/repair.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>
#include <iostream>
#include <fstream>

typedef CGAL::Simple_cartesian<double>                       Kernel;
typedef Kernel::Point_3                                      Point;
typedef CGAL::Surface_mesh<Point>                            Mesh;

namespace {

size_t patchBoundary(const Mesh::Halfedge_index halfedgeIndex, Mesh &mesh)
{
	std::vector<Mesh::Face_index> newFaces;
	std::vector<Mesh::Vertex_index> newVertices;

	try {
		CGAL::Polygon_mesh_processing::triangulate_and_refine_hole(
				mesh, halfedgeIndex,
				std::back_inserter(newFaces), std::back_inserter(newVertices),
				CGAL::Polygon_mesh_processing::parameters::use_delaunay_triangulation(true));
	} catch(CGAL::Failure_exception &err) {
		std::cout << "Ignoring exception " << std::endl;
	}

	return newFaces.size();
}
}

int main(int argc, char* argv[])
{
	Mesh sm1;
	std::ifstream in1((argc>1)? argv[1]: "../../patchBoundaryData/patchBottom.off");
	in1 >> sm1;

	const size_t numberOfFacesBefore = sm1.num_faces();
	std::cout << "numberOfFacesBefore " << numberOfFacesBefore << std::endl;
	bool allBoundariesPatched = true;
	size_t numberOfBoundariesPatched = 0;
	for(const Mesh::Halfedge_index halfedgeIndex : sm1.halfedges()) {
		if(sm1.is_border(halfedgeIndex)) {
			++numberOfBoundariesPatched;
			const size_t numberOfFacesAdded = patchBoundary(halfedgeIndex, sm1);
			allBoundariesPatched &= (numberOfFacesAdded != 0);
		}
	}

	std::cout << "allBoundariesPatched " << allBoundariesPatched << std::endl;
	std::ofstream oFileT("mesh.off",std::ios::out);
	// writing file output;
	oFileT << sm1;

	return EXIT_SUCCESS;
}
```

## Environment

* MacOS
* Compiler: clang
* Release 
* CGAL version: 5.2

**Comment by danston** [comment]
Hi @sandboxgod Could you please try to run your code with the master version of CGAL? This PR #4749 should fix your problem. If not, please let me know and I will investigate. You should also provide the named parameter: [use_2d_constrained_delaunay_triangulation](https://github.com/CGAL/cgal/pull/4749/files#diff-937f09ec7e605b8feb094fc669f95ea4537f90d02ebabf545b0c0d40e1855d08R89).

**Comment by sandboxgod** [comment]
@danston Thanks for your reply. I tried both of the suggestions (building cgal-master instead of 5.2 branch) but I still have the same issue unfortunately

**Comment by danston** [comment]
@sandboxgod Ok, thanks! Then it is something else. I will investigate in detail what is going wrong and let you know asap.

**Comment by sandboxgod** [comment]
Sounds good thank you for helping look into this

**Comment by afabri** [comment]
I had a quick look at your data. There are two holes with total edge length zero, that is formed by degenerated triangles. I marked one of them red (on the very right).
![image](https://user-images.githubusercontent.com/3263539/117357405-32d3ff80-aeb5-11eb-82e6-7f40019a5e80.png)

**Comment by sandboxgod** [comment]
Thanks for your reply @afabri. That is interesting because I told CGAL to remove degenerate geometry right before I exported the model from our software using the code below. Is there a better way? 

```
	std::map<std::pair<Geometry::SurfaceImplementation::CgalMesh::Vertex_index, Geometry::SurfaceImplementation::CgalMesh::Vertex_index>, double> costCache;
	std::map<Geometry::SurfaceImplementation::CgalMesh::Face_index, QVector3D> normalCache;
	const DegenerateTriangleCost cost(costCache, normalCache);
	const MelaxPlacement placement = MelaxPlacement(costCache, normalCache);
	CachedCostRemovalVisitor visitor(costCache, normalCache);

	CGAL::Surface_mesh_simplification::edge_collapse(_mesh, DegenerateTriangleStopCondition(), CGAL::parameters::get_cost(cost).get_placement(placement).visitor(visitor));

	std::vector<CgalMesh::Face_index> facesToRemove;
	const CgalMesh &mesh = _mesh;
	std::copy_if(_mesh.faces().begin(), _mesh.faces().end(), std::back_inserter(facesToRemove), [&mesh](const CgalMesh::Face_index &faceIndex) -> bool {
		return isDegenerate(mesh, faceIndex);
	});

	for(const CgalMesh::Face_index faceToRemove : facesToRemove) {
		CGAL::Euler::remove_face(_mesh.halfedge(faceToRemove), _mesh);
	}
```

Going to try somethings on my end such as check for a degenerate face first before we attempt to patch the hole. I mainly only need to patch the holes at the bottom of the surface.

**Comment by danston** [comment]
@sandboxgod I checked your data in more detail. You have 4 holes. Three holes are degenerated that is each has 3 vertices and all three vertices have the same position. One hole is the big hole to fill. The assertion that was triggered in your code is related to the small holes. 

The problem is that even if I detect all the holes before applying the hole filling and then disregard the degenerated ones, the big one still fails. It seems like the big hole is not a simple polygon (in order to use the constrained Delaunay triangulation option) and has some other issues as well (which prevent the more general hole filling), so filling this hole is not currently possible. 

Regarding degenerated cases, [here](https://gist.github.com/danston/16bc2313623f56517c02ba46aa40eebd), I have created a gist that shows how to detect holes and disregard the degenerated holes. This is one way. The other way is to repair such degenerated cases using [Euler operations](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html). You can also see several useful PMP functions [here](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PkgPolygonMeshProcessingRef.html), in particular, the `Combinatorial Repairing Functions` section. I did not yet check your code that removes degenerated geometry using Euler but since it did not remove the degenerated holes, it is most likely doing something else rather than removing these cases. Probably, what you need to do is to find the degenerated cases and then split/merge/join certain vertices/halfedges. 

Meanwhile, I will investigate what goes wrong on our side with the big hole and create a PR that fixes it if necessary.

**Comment by sandboxgod** [comment]
Thanks for the feedback I'll investigate other ways to see if we can avoid getting into this situation
