### ISSUE TITLE
edges(sm).size() takes linear time

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5720]
## Issue Details

Would it make sense to enrich the iterator range class with a data member for storing the size in case we know it?  This would avoid to traverse the range in order to count the elements.  This is for example necessary for a ` Surface_mesh` as soon as  it has garbage (simplices only marked as deleted).

**Comment by lrineau** [comment]
Can you please describe a use-case?

It seems to imply that the consumer of that "range" actually requires more than a range.

**Comment by MaelRL** [comment]
Use case is BGL API, calling `edges(graph).size()` to get the real number of edges in the mesh and not the capacity of the edge vector (which `num_edges(g)`) would give you.

That will run in linear time for `CGAL::Surface_mesh` since it has to skip garbage. (This is not an issue for direct, non BGL, `CGAL::Surface_mesh` usage since it stores the capacity and the number of removed edges.)

Thus, why the size could be cached. Or maybe the BGL API needs a new function like `real_num_edges(g)`.

**Comment by afabri** [comment]
I am not in favor of `real_num_edges()`, and the caching is easy to imlpement and not costly in memory or space.

**Comment by afabri** [comment]
Does the overload then also match classes derived from `Surface_mesh` ?

**Comment by MaelRL** [comment]
> Does the overload then also match classes derived from `Surface_mesh` ?

no, but you could sfinae the overload to check if the graph has a surface_mesh base.
