### ISSUE TITLE
TBB API changed in 2021 version

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5845]
## Issue Details

The `parallel_do` was removed in the 2021 version of TBB, and some files of CGAL don't build anymore.

IIUC the parallel_do API is replaced by the `task_group` API. 

Interresting discussion about how to replace parallel_do : 
https://github.com/oneapi-src/oneTBB/issues/352

## Source Code
Occurencies of parallel_do.h in CGAL (mostly in Mesh_3) : 
 - CGAL/Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
 - CGAL/Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
 - CGAL/Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
 - CGAL/STL_Extension/benchmark/compact_container_benchmark/cc_benchmark.cpp

**Comment by lrineau** [comment]
:disappointed: When I prepared the porting to oneAPI-TBB, in https://github.com/CGAL/cgal/pull/4892, I did that because `tbb::task` was deprecated. But `tbb::parallel_do` was never deprecated before its removal. In the document [TBB Revamp: Background, Changes, and Modernization](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html), they say that `tbb::parallel_for_each` can be used instead of `tbb::parallel_do`, and its was already in TBB versions 2018, 2019, and 2020.

**Comment by lrineau** [comment]
I think that, when I tried in the past, the compilation and the testsuite worked because `<tbb/parallel_do.h>` was found in `/usr/include` implicitly from the system installation of TBB-2020. I will try again from a container.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5850.
