### ISSUE TITLE
EPECK Construct Cartesian d Seg Fault

### ISSUE THREAD

**Issue by danston** [CGAL/cgal#5878]
## Issue Details

I bumped into an issue when using `construct_cartesian_const_iterator_d_object()` from `Search_traits_3` parameterized by EPECK.

When compiling an example below, I first get a warning:

```bash
cgal/Filtered_kernel/include/CGAL/Filtered_kernel/Cartesian_coordinate_iterator_3.h:119:12: warning: returning reference to local temporary object [-Wreturn-stack-address]
    return *(*this + i);
           ^~~~~~~~~~~~
main.cpp:18:19: note: in instantiation of member function 'CGAL::Cartesian_coordinate_iterator_3<CGAL::Epeck>::operator[]' requested here
  const auto d = p[0] - q[0];
```

and then when running the code, it triggers an error:

```bash
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000100014560 test_epeck`CGAL::Interval_nt<false>::operator-(this=0x00007ffeefbff078) const at Interval_nt.h:173:27
   170    IA operator-() const
   171    {
   172  #ifdef CGAL_USE_SSE2
-> 173      return IA (swap_m128d(val));
   174  #else
   175      return IA (-sup(), -inf());
   176  #endif
```

Is it correct that `operator[]()` returns a ref for EPECK?

## Source Code

I created a simple [minimal example](https://gist.github.com/danston/bf00bd7092d5943ebc2c189ae0465fa2) that illustrates the issue.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOS
* Compiler: clang 12.0.0
* Release or debug mode: both
* Specific flags used (if any): `-Wall -Wextra`
* CGAL version: master
* Boost version: 1.76.0
* Other libraries versions if used (Eigen, TBB, etc.): nope

**Comment by mglisse** [comment]
(I don't remember ever looking at this code)
It looks bogus (since the introduction of this file), `operator*` returns `const FT` and `operator[]` delegates to `operator*` but returns a reference... Probably nobody uses `operator[]` on those iterators.
I suggest `typedef value_type reference;` (and replace `const FT` with `reference` for `operator*`). That will make `iterator_category` slightly wrong, but only because of a well-known misfeature in the standard.
(we could also use `typedef value_type const reference;` to make it clearer that this is read-only, but it might cause an extra copy sometimes)
This "iterator" also seems to be missing `operator->`, so `pointer` should be `void` apparently?

**Comment by danston** [comment]
Thanks for the clarification! I will try to play around with the options you suggested and create a PR if it works.

**Comment by sloriot** [comment]
I does ring a bell. Isn't it because it's a one pass? I'm pretty sure I wrote something about that somewhere (cgal-develop, wiki) some time ago.

**Comment by sloriot** [comment]
Forget my previous comment it was another iterator type.

**Comment by mglisse** [comment]
Using `decltype(auto)` as return type could also make sense.
@sloriot I'm sure we've had similar issues in other places...
