### ISSUE TITLE
How to robustify to_interval(Quotient)

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5928]
## Issue Details

[Construction of an interval](https://github.com/CGAL/cgal/blob/master/Number_types/include/CGAL/Quotient.h#L686) from a quotient fails if the numerator or denominator is a large integer which does not fit into a `double`.       `Gmpq`  uses  `MPFR`  and we seek for a solution for `boost::multiprecision::cpp_int`.

Any idea is welcome.   I am wondering if a division with remainder as intermediate step can help.   This leaves us with remainder/denominator, that is there is no improvement if the denominator does not fit into a double.  At the same time  we know that this is between 0 and 1 which is a still a bound, even if not very tight.   We now can do a binary search. Can we get it tighter cheaply by looking at the number of limbs?

**Comment by mglisse** [comment]
A link to how boost handles conversion from cpp_rational to double: https://github.com/boostorg/multiprecision/blob/3094249d7c30026b39fef77344e187bf93f24c6c/include/boost/multiprecision/detail/generic_interconvert.hpp#L305

**Comment by afabri** [comment]
I just posted an [issue ](https://github.com/boostorg/multiprecision/issues/360)on a problem with conversion and rounding modes.

**Comment by afabri** [comment]
And we observed that issue in [`Lazy.h`](https://github.com/CGAL/cgal/blob/master/Filtered_kernel/include/CGAL/Lazy.h#L1969) in a `try/catch` with a `Protect_FPU_rounding` moved outside the `try` (due to a stack unwinding bug with some VC++) which makes that in the `catch` we still have the rounding up activated.

**Comment by mglisse** [comment]
Some options
1. Take inspiration from `Gmpzf::to_interval_exp`. For a positive cpp_int, get its `msb`. If more than 52, shift right so it becomes 52, we get an interval [n,n+1) and remember the shift amount. We do the same for the denominator, divide the intervals, and finally ldexp with the difference of the shifts and negate if needed. When we don't shift (msb≤52), we can pick just [n,n]. A drawback is that even for numbers exactly representable as `double`, we will seldom end up with an interval [d,d] (maybe we could try harder (`lsb`?) to detect if the shift only removes 0s, to detect more cases). The division of intervals also requires setting the rounding mode.
2. Take inspiration from boost's generic_convert_rational_to_float_imp. Shift left the numerator (or denominator) so that the difference of msb is 53 bits, compute the integer division, if it has 54 bits, shift by 1, and use [n,n+1) (or just [n,n] if the remainder was 0 both in the main division and in the shift-by-1) corrected by the shift amounts and sign. This may be a bit costly.
3. Similar to *2*, but without keeping the whole number, just divide something like 106 bits by 53 bits. This might require taking an interval (n-1,n+2).

**Comment by sloriot** [comment]
> And we observed that issue in [`Lazy.h`](https://github.com/CGAL/cgal/blob/master/Filtered_kernel/include/CGAL/Lazy.h#L1969) in a `try/catch` with a `Protect_FPU_rounding` moved outside the `try` (due to a stack unwinding bug with some VC++) which makes that in the `catch` we still have the rounding up activated.

I added in the testsuite the testfile to see if supported MSVC compilers are still affected by the bug and it seems that they are still affected. See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-36/Number_types/TestReport_Sosno_MSVC-2019-Community-Release.gz) for example.

**Comment by afabri** [comment]
@mglisse why do you write "take inspiration". Why not just calling `generic_convert_rational_to_float_imp()`?

**Comment by mglisse** [comment]
> I added in the testsuite the testfile to see if supported MSVC compilers are still affected by the bug and it seems that they are still affected. See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-36/Number_types/TestReport_Sosno_MSVC-2019-Community-Release.gz) for example.

Is there a corresponding bug report on developercommunity.visualstudio.com or elsewhere?

**Comment by mglisse** [comment]
> @mglisse why do you write "take inspiration". Why not just calling `generic_convert_rational_to_float_imp()`?

That's not a documented interface, even if you drop `_imp` at the end (we could probably define a dummy backend just to call that function through documented interfaces). And you still need to produce an interval from it afterwards. What I do in boost_mp.h (convert the `double` back to a rational and compare it to the input so I can extend the interval in the right direction or not at all) is not super efficient. But it is a possibility, yes.

**Comment by afabri** [comment]
> I just posted an [issue ](https://github.com/boostorg/multiprecision/issues/360)on a problem with conversion and rounding modes.

The issue I reported in the multiprecision project got fixed, but I have no idea what that implies for our issue here.
