### ISSUE TITLE
Deprecated VTK_USE_FILE in Polyhedron Demo

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5949]
When making the Polyhedron demo with CMake, I got the following error :

```
CMake Deprecation Warning at C:/dev/VTK-9.0.3/build/lib/cmake/vtk-9.0/vtk-use-file-deprecated.cmake:1 (message):
  The `VTK_USE_FILE` is no longer used starting with 8.90.
Call Stack (most recent call first):
  Plugins/IO/CMakeLists.txt:47 (include)
```
https://github.com/CGAL/cgal/blob/6f7fd79a1e714937c9a29fd3b4e3d6de225e1922/Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt#L55

and
```
CMake Deprecation Warning at C:/dev/VTK-9.0.3/build/lib/cmake/vtk-9.0/vtk-use-file-deprecated.cmake:1 (message):
  The `VTK_USE_FILE` is no longer used starting with 8.90.
Call Stack (most recent call first):
  Plugins/Mesh_3/CMakeLists.txt:34 (include)
```
https://github.com/CGAL/cgal/blob/6f7fd79a1e714937c9a29fd3b4e3d6de225e1922/Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt#L34

It seems to me that this problem makes no IO plugin work in my Polyhedron Demo.  

Would you know what to change to stop getting this message?

**Comment by maxGimeno** [comment]
I'm quite sure this is just a harmless warning and is absolutely not the reason why no IO plugin work in your Polyhedron Demo. Especially because only one plugin uses VTK. You can check, inside the demo, in the menu Edit->Preferences, the right panel lists all the plugins that were found, and the red ones are the ones that don't work. Select one and click on "details" to see the error, possibly.  Hopefully it won't just say that "there were a problem loading the dll"...
