### ISSUE TITLE
Use of unsafe functions

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5991]
## Issue Details

CGAL uses functions like `memset()` which should be replace with `memset_s`. 
Occurrences in files in `include/CGAL/`  _must_ be replace, while occurrences in examples demos or developer scripts _may_ be replaced. 

The fix must be done for the 5.3 branch.

Note that this also requires to be documented because the users must `#define`  a macro in order to activate the runtime check (see the [`memset()` manual page](https://en.cppreference.com/w/c/string/byte/memset) on cppreference).

**Comment by lrineau** [comment]
Actually, I disagree. If we except the header from ImageIO, then all our usage of `std::memset` are safe:
```
[lrineau@bonnard]~/Git/cgal-master% ack memset */include/CGAL/^ImageIO
Arrangement_on_surface_2/include/CGAL/Arr_counting_traits_2.h
969:  { memset(m_counters, 0, sizeof(m_counters)); }

Cone_spanners_2/include/CGAL/Cone_spanners_2/Plane_scan_tree_impl.h
138:        std::memset (values, 0, 2*sizeof(value_type*));
272:        std::memset (keys, 0, 2*sizeof(key_type*));
273:        std::memset (children, 0, 3*sizeof(_node_type*));
274:        std::memset (vMin, 0, 3*sizeof(mapped_type*));

Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Octree.h
178:            memset(child, 0, sizeof(Cell *) * 8);

STL_Extension/include/CGAL/Compact_container.h
429:    std::memset(&*x, 0, sizeof(T));

STL_Extension/include/CGAL/Concurrent_compact_container.h
400:    std::memset(&*x, 0, sizeof(T));
```

They are safe usage of [`memset`](https://en.cppreference.com/w/c/string/byte/memset), where the third parameter `count` is a compile-time constant, that cannot be controlled by any attacker.

As far as I can see, the usage of `std::memset` in ImageIO are with compile-time constant either, but they are safe. We can switch to `std::memset_s(dest, destsz, ch, count)`, but that will not bring any more safety: we will just pass the value of `count` to the parameter `destsz`, and that will be equivalent to the current situation, but with a less efficient code (because of the extra comparison).

**Comment by lrineau** [comment]
Note also that `std::memset` is a standard C++ function from the STL, but `memset_s` is not: it is only in C11, and not in C++.

**Comment by mglisse** [comment]
Even for C you can read a lot of bad things about annex K online. Some of the functions are not that much safer. It is optional and mostly only available on windows (and even there it doesn't quite match the standard). Etc.

**Comment by pentacular** [comment]
The real danger of memset is that setting the bytes of an object to zero won't necessarily produce the right value on every.

std::memset (values, 0, 2*sizeof(value_type*));

looks like it really wants to be

values[0] = nullptr;
values[1] = nullptr;

**Comment by GilesBathgate** [comment]
Wouldn't it be better to write idiomatic C++ instead? maybe Zero initialization, or std::fill?
