### ISSUE TITLE
Cross-compilation and TRY_RUN

### ISSUE THREAD

**Issue by plut** [CGAL/cgal#6101]
I am trying to use this in building some binaries across different platforms (by using the Julia packaging system), which involves compiling CGAL in cross-compiling mode.

However, this causes the `TRY_RUN`s to fail; [this happens on line 193 of this log](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=14312&view=logs&j=50d6965a-b53c-5980-33e2-bac7bad52d28&t=512154e9-2cf2-5516-ee3c-95bb8f48dbc5&l=193).
(here, the host and target platforms are identical, but that is accidental, and cross-compiling mode is set anyway).

The error message is not too clear: namely, where do I need to set this variable? to which value? (this seems related to `boost::thread`, which is guaranteed to exist on my platforms, so I'm happy with forcing its use in all cases) and how many more such variables will need to be set to get the darn thing compiling?

**Comment by plut** [comment]
Answer found (not by me), issue closed, thanks to anyone who read that

**Comment by lrineau** [comment]
libIGL hardcodes a download of CGAL-4.12, that is completely obsolete (it was released 25 April 2018), and unsupported.


Since CGAL version 5.0, CGAL is header-only, and no longer needs any `try_run` CMake command.


PS: *Bonjour ^, ça fait bizarre de se retrouver dans un contexte pro, tant d'années après ! Suite de la discussion par email ?*
