### ISSUE TITLE
Change parameters of edge_aware_upsampling()

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#653]
@cjamin and @palliez:

The function [`edge_aware_upsampling()`](http://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing.html#ga10b638ebebaea6e49e688466dd9c8376) has parameter <code>Kernel::FT</code>.   Wouldn't it make sense if this was just `double`, as the code even performs trigonometric computations? 

Also the parameter `const unsigned int number_of_output_points` should clearly be `std::size_t`.

**Comment by cjamin** [comment]
Sure, you are right.

**Comment by sgiraudot** [comment]
I'll take care of this.

**Comment by sgiraudot** [comment]
@afabri I can see 3 FT parameters in this function:
- `sharpness_angle`
- `edge_sensitivity`
- `neighbor_radius`

As far as I understand, your issue mainly refers to the first one which is anyway converted to a double in the code:

```c++
FT cos_sigma = static_cast<FT>(std::cos(CGAL::to_double(sharpness_angle) / 180.0 * CGAL_PI));
```

What about the other two? It seems to me that `edge_sensitivity` should be a double too. It's used there:
```c++
FT dot_produce = std::pow((FT(2.0) - vm * tm), edge_sensitivity);
```
And it seems to me that this `dot_produce` should be a double too.

The last one is more ambiguous to me. Here is how it is used:
```c++
  FT average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(
                   first, beyond,
                   point_pmap,
                   nb_neighbors);

  if (neighbor_radius < average_spacing)
    neighbor_radius = average_spacing * 3.0f;
```

Note also that there is a variant that uses doubles instead of FT and casts them before calling the main function:
```c++
// This variant deduces the kernel from the point property map.
template <typename Concurrency_tag,
	  typename OutputIterator,
          typename ForwardIterator,
          typename PointPMap,
          typename NormalPMap>
OutputIterator
edge_aware_upsample_point_set(
  ForwardIterator first,    ///< forward iterator to the first input point.
  ForwardIterator beyond,   ///< past-the-end iterator.
  OutputIterator output, ///< output iterator over points.
  PointPMap point_pmap, ///< property map: `ForwardIterator` -> Point_3.
  NormalPMap normal_pmap, ///< property map: `ForwardIterator` -> Vector_3.
  double sharpness_angle,  ///< control sharpness(0-90)
  double edge_sensitivity,  ///< edge sensitivity(0-5)
  double neighbor_radius, ///< initial size of neighbors.
  const std::size_t number_of_output_points///< number of iterations.   
  )
{
  typedef typename boost::property_traits<PointPMap>::value_type Point;
  typedef typename Kernel_traits<Point>::Kernel Kernel;
  typedef typename Kernel::FT FT;
  return edge_aware_upsample_point_set<Concurrency_tag>(
    first, beyond,
    output,
    point_pmap,
    normal_pmap,
    static_cast<FT>(sharpness_angle), 
    static_cast<FT>(edge_sensitivity),
    static_cast<FT>(neighbor_radius), 
    number_of_output_points,
    Kernel());
}
```
I am not sure what we should do with that. Change everything to double? Including the content of the function which uses FT everywhere?

Also, I am pretty sure there is the same behavior (using FT where they should be double) in many other Point Set Processing functions. Maybe we should do a small feature to correct these inconsistencies everywhere we find them in this package. What do you think?

**Comment by sgiraudot** [comment]
Fixed by https://github.com/CGAL/cgal/pull/2694.
