### ISSUE TITLE
Precompiled CGAL 3D demo for Windows

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6744]
It looks like  that the documentation of the 5.5-beta1 release points to the documentation of the master version, see the second link on the page: https://www.cgal.org/2022/06/06/cgal55-beta1/

Regarding the examples it looks like that the example files:
- https://www.cgal.org/demo/5.5/triangulation_on_sphere_2.zip
- https://github.com/CGAL/cgal/releases/download/v5.5/CGAL-5.5-examples.tar.xz
- https://github.com/CGAL/cgal/releases/download/v5.5/CGAL-5.5-examples.zip

aren't yet present

**Comment by lrineau** [comment]
For the URL https://doc.cgal.org/5.5/Manual/index.html, I have fixed that:
  - now https://doc.cgal.org/5.6/Manual/index.html redirects to `master`,
  - https://doc.cgal.org/5.5/Manual/index.html redirects to the documentation of 5.5-beta1.

As for the links to tarballs, the way we build the documentation, the documentation of CGAL-5.5-beta1 is presented as if it was the documentation of CGAL-5.5. I do not know what we should change so that the `-beta1` part can be taken into account. That will be "fixed" once CGAL-5.5 is published, but during the beta period, I understand that those links are confusing.

**Comment by albert-github** [comment]
I saw that the version 5.5. was released but here there is a reference to https://www.cgal.org/demo/5.5/triangulation_on_sphere_2.zip and this tries to redirect to the non existing page https://www.cgal.org/demo/3.9/triangulation_on_sphere_2.zip so it looks like @janetournois hasn't finished yet the "back-porting the creation script from a computer that unexpectedly fried."
For me this is not a big issue, but for real users ..., so maybe a temporary page or a temporary zip file should be installed with the message that the issue is know and that from the CGAL side work is in progress to get the example up and running.

**Comment by albert-github** [comment]
@lrineau, @janetournois 
What is the status regarding the demo: https://www.cgal.org/demo/5.5/triangulation_on_sphere_2.zip?

**Comment by albert-github** [comment]
I had a look at the 5.6 and 6.0 version of the documentation and here a file downloaded (looked like a file with recent content).
With the 5.5.3 version there is indeed still no version as also indicated by the:
![image](https://github.com/CGAL/cgal/assets/5223533/4f8657eb-02dd-4f0f-8cf9-be6e249c2aec)

in the history of this issue.

- will there still be an attempt to create the 5.5 version? or will the problem "vanish" as soon as the 5.5 version is not supported anymore (not a nice idea / thought).

**Comment by janetournois** [comment]
In my opinion we only need to publish the latest version of the precompiled demos.
For older versions, it is still possible to compile them from the branch, but it has not much interest.

@sloriot @lrineau can we close this issue?

**Comment by lrineau** [comment]
Yes, I think so.
