### ISSUE TITLE
edge_aware_upsample_point_set_example

### ISSUE THREAD

**Issue by cq0907** [CGAL/cgal#6952]
_Please use the following template to help us solving your issue._

## Issue Details

When I execute the program edge_aware_upsample_point_set_example.cpp, its input must provide normals, but the reference paper of this function says that normals do not need to be provided. Why are they different?

## Source Code

![image](https://user-images.githubusercontent.com/39946114/194985595-7489cbf4-ef69-48c5-b6a3-f9b2dec71e85.png)

## Environment

* Operating system: Windows
* CGAL version: 5.5
* Boost version: 1.70
* Eigen: 3.4

**Comment by afabri** [comment]
As you can see in Section 3 on page 4 of the [original publication](https://www.researchgate.net/publication/266228467_Edge-Aware_Point_Set_Resampling), their first step is to estimate normals with a classical algorithm, and then improve normals from there.  Instead of hardcoding a particular normal estimation algorithm we offer the possibility to provide the normals.

@cq0907 if you agree, please close this issue.
