### ISSUE TITLE
bug polygon_soup_to_polygon_mesh

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7011]
Hello,

Consider this mesh: [cube.off](https://gist.github.com/stla/975fe0981c62b9815d1278081cb4ac11). This is a cube with many duplicated vertices, and 12 distinct triangular faces. If you read it as a polygon soup and apply `PMP::repair_polygon_soup`, then you obtain the 8 vertices as expected, and 12 faces as expected. But then, if you apply `PMP::polygon_soup_to_polygon_mesh`, there are only 11 faces left.

I'm using **CGAL 5.4.1**.

```cpp
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Kernel/global_functions.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/IO/polygon_soup_io.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel EK;
typedef EK::Point_3                                       EPoint3;
typedef CGAL::Surface_mesh<EPoint3>                       EMesh3;

namespace PMP = CGAL::Polygon_mesh_processing;

int main() {
  std::vector<EPoint3> points;
  std::vector<std::vector<int>> faces;
  const bool ok = CGAL::IO::read_polygon_soup(
    "cube.off", points, faces, CGAL::parameters::verbose(true)
  );
  if(!ok) {
    std::cout << "Reading failure";
    std::exit(1);
  }
  const bool success = PMP::orient_polygon_soup(points, faces);
  PMP::repair_polygon_soup(points, faces);
  std::cout << faces.size() << "\n"; // this prints 12
  EMesh3 mesh;
  PMP::polygon_soup_to_polygon_mesh(points, faces, mesh);
  std::cout << mesh.number_of_faces() << "\n"; // this prints 11
  return 0;
}
```

**Comment by MaelRL** [comment]
Short version: call repair before orient.

Longer version:

Your input has 12 disconnected connected components :  `orient_polygon_soup` works on connected components (CC) and will do nothing to your 12 CCs. Then you call `repair_polygon_soup()`, which will merge vertices with identical geometry but different IDs.

The result is a single connected component but with incompatible orientations. If you run it in debug, you will see that it warns you about this:

```
Expr: is_polygon_soup_a_polygon_mesh(polygons)
File: /home/mrouxell/git/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
```

You call `polygon_soup_to_polygon_mesh()` and it does its best to add new faces, but stops when it can't add a new face due to incompatible orientations, hence not all faces in your output.

Hence, repair the soup first to remove defects and merge vertices together, and then orient it.

**Comment by stla** [comment]
Thank you! Indeed it works now.
