### ISSUE TITLE
warning: possibly dangling reference to a temporary [-Wdangling-reference]

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#7214]
## Issue Details

In this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-166/Periodic_3_mesh_3/TestReport_lrineau_Fedora-rawhide.gz) we get a warning for this 
[line](https://github.com/CGAL/cgal/blob/master/Periodic_3_mesh_3/include/CGAL/Periodic_3_mesh_3/Protect_edges_sizing_field.h#L1033) we get the warning about a possibly dangling reference.  Although it is a false alert, is there any gain from `const&` here.
Won't there anyways be a  returned objects optimization.

**Comment by afabri** [comment]
There are other places, for example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-166/Shape_detection/TestReport_lrineau_Fedora-rawhide.gz) where we access a property map with `get()`.   It would also be cleaner code using `boost::property_traits<PM>::reference`.

**Comment by sloriot** [comment]
Using `reference` is useful if you get out of the scope where the object is retrieved. Using `const&`  is the right choice if the object don't get out of the scope as it handles both lvalues and rvalues.

**Comment by afabri** [comment]
Can you give me a link to any C++ gurus book or blog that c;onfirms this choice.

**Comment by sloriot** [comment]
- https://en.cppreference.com/w/cpp/language/reference_initialization#Lifetime_of_a_temporary
- https://en.cppreference.com/w/cpp/language/copy_elision: In particular *Another way to describe C++17 mechanics is "unmaterialized value passing": prvalues are returned and used without ever materializing a temporary.*

**Comment by lrineau** [comment]
Let's have a look at https://github.com/CGAL/cgal/blob/5a962eb1984b0b3a404e7ad25d2af7df18794132/Polyhedron/demo/Polyhedron/Plugins/PMP/Jet_fitting_plugin.cpp#L70-L81

g++-13.2.1, with `-Wall -Wextra` gives the warning with the last line:
```c++
const Point& p = get( vpmap, target(opposite(he, *pMesh ), *pMesh)); 
```
but not with the first one:
```c++
const Point& central_point = get(vpmap,v); 
```
whereas, in our opinion, they are rather similar: `vpmap` contains a refrence to the mesh, and the reference `p` points to a sub-object of the mesh, and that has the same lifetime as the mesh itself.

@mglisse Is `-Wdangling-reference`-reference` one of those warnings you think we should not use?

In https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107532 a gcc developer seems to admit that there are false positives that cannot be solved. And expect a better behavior for g++-14 (planned for ~April 2024).

**Comment by mglisse** [comment]
> @mglisse Is `-Wdangling-reference` one of those warnings you think we should not use?

[rant]
Generally, the idea is that all the warnings that depend on optimizations are fragile. Quite often, after a number of optimizations including inlining, duplicating code for different code paths, etc, we end up with a piece of code that does something bad (use uninitialized memory, dereference a null pointer, return a reference to a temporary, etc), but that code is dead, there is no way it can ever be reached, the compiler just fails to realize that. That doesn't mean those warnings are useless, they may occasionally detect a real bug, and they often point at places where the code could be optimized a bit, but IMO it means that they should not be used by default and block development, they should only be used to help debug a bug detected by other means, or when we are ready to invest a lot of time to investigate likely false positives, or if we don't mind some false positives and only want to check if one of the messages is obvious, or other special circumstances. I fought to keep all those optimization-based warnings out of -Wall and lost. Since I stopped contributing to gcc, they added even more, and even enabled at least one by default...
[/rant]
-Wdangling-reference seems to be a normal, front-end warning, so it is not concerned by the rant above. I am not familiar with this warning and don't have a particular opinion about it. At least, as a front-end warning, if you have determined that it is a false positive, disabling it with a pragma should be reliable.

**Comment by sloriot** [comment]
Note that I already started to go into that direction in https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/135
