### ISSUE TITLE
Remove faces from SurfaceMesh

### ISSUE THREAD

**Issue by HlKun** [CGAL/cgal#7297]
## Issue Details

I try to remove some faces from SurfaceMesh,but it shows me a error.

This is my mesh file.
[Mesh.zip](https://github.com/CGAL/cgal/files/10880106/Mesh.zip)

This is the error I got.
    ![image](https://user-images.githubusercontent.com/46489569/222672369-2adaadcc-3e9b-48a5-a473-93494a2ded95.png)

## Source Code
```c++
    typedef boost::property_map<Mesh, CGAL::edge_is_feature_t>::type EIFMap;
    EIFMap eif = get(CGAL::edge_is_feature, mesh);
    PMP::detect_sharp_edges(mesh, 90, eif);
    std::set<face_descriptor> fds;
    for (edge_descriptor e : edges(mesh))
    {
        if (get(eif, e) && !is_border(e, mesh))
        {
            std::set<halfedge_descriptor> hd_set;
            hd_set.insert(e.halfedge());
            hd_set.insert(mesh.opposite(e.halfedge()));

            std::set<vertex_descriptor> vset;

            for (halfedge_descriptor hd : hd_set)
            {
                for (vertex_descriptor vd : mesh.vertices_around_face(hd))
                    vset.insert(vd);
            }

            for (vertex_descriptor vd : vset)
            {
                for (face_descriptor fd : mesh.faces_around_target(mesh.halfedge(vd)))
                    fds.insert(fd);
            }
        }
    }

    for (face_descriptor fd : fds)
    {
        mesh.remove_face(fd);
    }

    mesh.collect_garbage();
```
_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows 10 x64
* Compiler: VS2019
* Release or debug mode: all
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version:1.72
* Other libraries versions if used (Eigen, TBB, etc.):Eigen and tbb

**Comment by MaelRL** [comment]
Could be that `faces_around_target()` gives you a null face (the face incident to a border halfedge), which you don't want to remove

You should also probably be using [Euler::remove_face()](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gacfae7ff8e782da55b941e4487e86c738) instead of [`Surface_mesh::remove_face()`](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#af2311658bf6d730b276b23b5c304f90e) because the former removes meaningless elements while the latter is a rather low level function.
