### ISSUE TITLE
Feature request: Advancing_front_surface_reconstruction boundary

### ISSUE THREAD

**Issue by snroth** [CGAL/cgal#749]
The imposition of the boundary edges would be a great feature to improve surface reconstruction on some particular cases. Is this feasible?

**Comment by sgiraudot** [comment]
The advancing front reconstruction algorithm is based on a 3D Delaunay triangulation of the point set, which is a first limitation: if the boundary edge is not part of the triangulation, it can't possibly appear in the reconstruction (using a constrained Delaunay triangulation would sort this problem, but so far we do not have constrained 3D triangulations in CGAL).

Otherwise, a feature is currently in development to let the user define how facets are prioritized during the reconstruction algorithm: one solution for boundaries would be to give higher priority to facets adjacent to a set of user-defined edges. There would be no guarantee that the edges are _all_ used in the end, but it could improve how boundaries are reconstructed.
