### ISSUE TITLE
Region growing on polygon mesh example with custom input file - Run-time error

### ISSUE THREAD

**Issue by adokhugi** [CGAL/cgal#7603]
## Issue Details

I tried using the region growing on polygon mesh example with a custom input file. The input file was originally an OBJ file but I used a converter to convert it to OFF. Link to the file: https://hugi.scene.org/adok/cgal/Scene.zip - I got the following run-time error:

```
region_growing_on_polygon_mesh example started

* polygon mesh with 0 faces is loaded
CGAL error: precondition violation!
Expression : m_face_range.size() > 0
File       : C:\dev\vcpkg\installed\x64-windows\include\CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/One_ring_neighbor_query.h
Line       : 87
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: Visual Studio 2022
* Release or debug mode: Debug mode
* Specific flags used (if any):
* CGAL version: 5.5.2
* Boost version: the latest
* Other libraries versions if used (Eigen, TBB, etc.): the latest

**Comment by sloriot** [comment]
I think the problem comes from the fact that you mesh is not a valid polygon mesh. Can you try using [`CGAL::Polygon_mesh_processing::read_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html#gac5b3295bd1b6375628a46d1fbaf7e881)?

Note that CGAL 5.6 will include an improve version of region growing for polygon meshes, and to achieve that the API was a bit changed, and we could unfortunately not keep the backward compatibility.

**Comment by adokhugi** [comment]
That method worked. Merci!
