### ISSUE TITLE
Weighted Skeleton calculation possibly wrong? 

### ISSUE THREAD

**Issue by pcace** [CGAL/cgal#7658]
Hi,

i am not quite sure but with the new weighted skeleton feature i get some results i did not expect. 
Since i am quite new to the whole matter its totally possible that i am completely wrong here and i just dont understand it correctly. 

in this example i assume that all the edges have a weight of 1 exept the one in the middle wich has for example 1000. 
i would assume an output like this: 

![ss](https://github.com/CGAL/cgal/assets/1011875/ff709084-c1c6-4405-9106-88a171332702)

But: the output is exactly the same as if there is no weight given at all. Is this an expected behaviour?
so the output looks like this (wich is very weird for me): 
![photo1692689590](https://github.com/CGAL/cgal/assets/1011875/e4abe8d6-579d-449e-ac3d-9014f8accefd)

Thanks a lot,

pcace

**Comment by sloriot** [comment]
Could you please provide a minimal example that we can compile and run?

**Comment by MaelRL** [comment]
As documented in https://doc.cgal.org/latest/Straight_skeleton_2/group__PkgStraightSkeleton2WeightedSkeletonFunctions.html#ga47341a662706227c6b4aa808dd17cf32, consecutive collinear edges with different weights are not currently supported.

The primary reason is that it's not really clear what should be done there: if you go back to the definition of bisectors as the interface between fronts moving at different speed, the front of the edge moving slower should immediately "lose" (that is, the bisector is the edge with the lower speed). Another way to look at it is if you still give different weights but edges are no longer collinear, and then you observe the behavior of the bisector as the angle goes to 180°.

Another reason is that if you wanted to extract a 3D roof from a skeleton with such artificial bisectors (the skeleton extrusion part of the package), then I would need to add extra faces (vertical sections) on top of the faces of the skeleton, otherwise you would have holes in the roof where these fake bisectors exist. It could also be done, but it felt like a lot of unnatural twisting, so I let it aside then. 

Could you somehow rework the way of your problem? What is the 3D form of your problem?
