### ISSUE TITLE
Testing different inputs for the 3D skeleton algorithm

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7949]
## Issue Details
Hello, I encountered the problem of lack of memory on the code that used the .wkt output of the polyhedron demo program as input.  
![wkt-1](https://github.com/CGAL/cgal/assets/147084302/9584f3a0-f3ce-43c7-ac46-9296f52dcf17)
How can I read and write 3D data with the least amount of memory? Do you have any idea?
That's why I want to have the output points of your skeleton in the form of .txt. In the example skeleton code, I changed the input to bear.off, 
![IMG_20231224_103838_112](https://github.com/CGAL/cgal/assets/147084302/7122c5cf-715e-40fe-9acf-e72fc36672c8)

but I received the same error. 
![IMG_20231224_103834_462](https://github.com/CGAL/cgal/assets/147084302/44977af2-fe29-4628-860d-580789e3c278)

How can I run your skeleton code for different inputs and get the output?

**Comment by afabri** [comment]
Hello,
I am sorry, but what you write is not clear. Changing the file name, the file is expected to be in the directory `CGAL-5.6/data/meshes/` because that is what `CGAL::data_file_path` about. Also no need to do that. You can pass your off file as argument to the executable.   
Next, why is there a fatal compilation error?  
Then, the warning indicates that there is a problem with the mesh you use. Is it a watertight 2-manifold?   We can have a look at the mesh.
Finally, nothing in this issue is about  the WKT format.

**Comment by afabri** [comment]
I close this as we  wait for four months for a reply.
