### ISSUE TITLE
Least_squares_plane_fit_region is not using PCA

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#7992]
`CGAL::Shape_detection::Polygon_mesh::Least_squares_plane_fit_region` says in the doc that it uses PCA but that's not the case.

From a quick look only centroids are used for a point on the plane and normals are only evaluated using 3 consecutive points of a face (which is not a good idea for non triangular faces).

**Comment by lrineau** [comment]
For example, with the file `Data/data/meshes/mpi.off`, see the face with the *three* vertices (black squares) in the bottom right corner of the picture:

![Screenshot_20240122_180743](https://github.com/CGAL/cgal/assets/5746675/69d2dd66-3bb3-42fb-a851-29635c3557ce)

That face has actually *four* vertices, and its first three vertices are almost aligned:

![Screenshot_20240122_180835](https://github.com/CGAL/cgal/assets/5746675/c4749db7-5045-4282-a092-cc574abc0553)

For that face, the computed fitting plane of it is very wrong.

**Comment by soesau** [comment]
The method uses triangles if available. In case of polygonal faces, a triangle fan for all edges with the centroid is used. That is certainly not correct for non-convex faces. Doing this correctly requires the triangulation of polygonal faces. As this is called several times per face, it may be useful to keep a cache.

For the normal, I will just switch to PMP::compute_face_normal. May make sense to require a property map for face normals to be provided.

The face centroid and face normal is actually only used if the region has size 1. For larger regions, a PCA is performed. However, it uses the wrong way for triangulating non-convex faces.

I think the result of the MPI mesh is unsatisfying because of almost degenerate faces. I didn't debug through it yet to verify.
