### ISSUE TITLE
libCGAL.so is missing

### ISSUE THREAD

**Issue by wanfuse123** [CGAL/cgal#8289]
libcgal.so is missing from bookworm and buster too

Need to know what the latest version with the libraries source code is and compiled version, please

## Environment
Debian 12 g++ Linux

**Comment by sloriot** [comment]
CGAL is a header only library. Only headers are provided.

**Comment by wanfuse123** [comment]
I thought it was an open source product? does the source come with a
 license purchase?

let me know!

thanks!

**Comment by sloriot** [comment]
CGAL is an open source project using the GPL-3 license, but as you mention it is also available under a commercial license if you cannot compile with the terms of the GPL. So there is nothing different in the commercial and the open source license. About the header only, aybe the wikipedia definition [here](https://en.wikipedia.org/wiki/Header-only) will be helpful:

**In the context of the [C](https://en.wikipedia.org/wiki/C_(programming_language)) or [C++](https://en.wikipedia.org/wiki/C%2B%2B) programming languages, a [library](https://en.wikipedia.org/wiki/Library_(computing)) is called header-only if the full definitions of all [macros](https://en.wikipedia.org/wiki/Macro_(computer_science)), [functions](https://en.wikipedia.org/wiki/Function_(computer_science)) and [classes](https://en.wikipedia.org/wiki/Class_(computer_science)) comprising the library are visible to the [compiler](https://en.wikipedia.org/wiki/Compiler) in a [header file](https://en.wikipedia.org/wiki/Header_file) form.[[1]](https://en.wikipedia.org/wiki/Header-only#cite_note-Wilson-HeaderOnly-1) Header-only libraries do not need to be separately [compiled](https://en.wikipedia.org/wiki/Compiler), packaged and installed in order to be used. All that is required is to point the compiler at the location of the headers, and then [#include](https://en.wikipedia.org/wiki/C_preprocessor) the header files into the application source.**

**Comment by wanfuse123** [comment]
thank you one more question what is the license cost for providing source
code that uses this library commercially?

**Comment by sloriot** [comment]
Again, there is nothing to pay to see the code, it is entirely on github, That is only using the library in a non open source context that requires a commercial license. If you are developing a closed source product, you can get in touch with GeometryFactory using `contact@geometryfactory.com` but again you won't get more code than the one that is currently on github.
