### ISSUE TITLE
make_hexahedron  order of template parameters

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#8362]
## Issue Details

Is there a reason why [`make_hexahedron()` ](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/group__PkgBGLGeneratorFct.html#ga12fa3e202c24740dade5764e3ea80c41) has the point type before the graph type?

**Comment by MaelRL** [comment]
It was changed recently when @janetournois added NPs (https://github.com/CGAL/cgal/commit/6b75fea902cf1c4844170bd20d7cbaaa9f17b3df), probably because the point parameter(s) come before the graph parameter, and usually the template parameters follow the same order.

What is the issue with the point template parameter coming first (except that it is not inconsistent throughout the `make_...` functions)?

**Comment by afabri** [comment]
The inconsistency makes you run in a compilation error, when you have a code where you switch from one to the other. That happened to me.
