### ISSUE TITLE
CGAL fails to read OFF file generated by Minkowsky Sum

### ISSUE THREAD

**Issue by cebe** [CGAL/cgal#978]
I am using CGAL to read OFF files into Nef_Polyhedron_3 and compute the Minkowsky Sum.
After computation I store the OFF file to cache the result (i.e. use stored file if it exists to save time on multiple runs of the algorithm).

When trying to read the generated file CGAL fails on some meshes with the following message:

```
Error !!!!!!!!!!!!!!!!!!!!!!!
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: pe_prev->is_border() || !internal::Plane_constructor<Plane>::get_plane(pe_prev->facet(),pe_prev->facet()->plane()).is_degenerate()
File: /usr/include/CGAL/Nef_3/polyhedron_3_to_nef_3.h
Line: 251
Abgebrochen
```

There error message comes from here: https://github.com/CGAL/cgal/blob/2ae5d2cef6fd638c7ba81116415fbe4bf601aab7/Nef_3/include/CGAL/Nef_3/polyhedron_3_to_nef_3.h#L105-L107

I have made a little program to reproduce the issue:

https://gist.github.com/cebe/0dfdecbaf2a799f72f36c01e949da742

You can compile and run it like the following:

```
git clone https://gist.github.com/cebe/0dfdecbaf2a799f72f36c01e949da742 bug
cd bug
make
./bug load
# the following can be used to re-generate the mesh file
./bug generate
```

I have included the generated mesh so you do not have to run the `generate` command and wait for the computation to see the error.

It seems the export of the mesh generates facets with zero area. I can fix the mesh with MeshLab using the filter "Remove zero area faces". Which results in the removal of one facet from the mesh.
To make it a closed mesh again I can fix it by merging the equal vertices.

To fix this, as far as I see this facet should either not be generated by the export, or not fail on import.

**Comment by sloriot** [comment]
The issue you observe is a rounding to double issue (which is even worse since the precision of the `ofstream` is not set to the maximum precision of double).
If you try reading the output polyhedron into a nef directly after the export operation, you will see no error.
Also, if you increase the precision of the stream to 17 while writing the output polyhedron, then the reading from file operation will work fine.

Snap rounding in 3D is complicated. One solution is to use methods like you used (edge collapse, self-intersection removal ...)

**Comment by cebe** [comment]
Thanks for the detailed answer. did not think about the rounding when saving to a file.
