### ISSUE TITLE
Default constructor for geometric objects

### ISSUE THREAD

**Issue by freud14** [CGAL/cgal#984]
Hi,

I notice that geometric objects do not initialize their attributes when using the default constructor which is causing them to have garbage as values. Would it be possible to initialize them with default values like zeros? It is counter-intuitive as, for instance, the objects of the STL are initialized to default values.

Thank you.

Frédérik

**Comment by cebe** [comment]
what is the point of creating an object without specifying it? For Points it may make sense to have initialized to zero but for other objects, e.g. Triangle or line, what would be the default value?
I do not think there is any benefit in adding default values, better write explicit code and use the constructors that initialize the values instead of default constructor.

**Comment by freud14** [comment]
Actually, the problem I had was that I used a Iso_box as attribute of a class, and because there was no compiler error, I took for granted that the empty constructor was defined (as opposed to being private) and it had obviously initialized the object with zeros.

One way to solve this "problem" would be to initialize to zero the geometric objects (which does not break anything that currently uses these objects) or to put private the default constructors (which may break a lot of things).

**Comment by lrineau** [comment]
The reason CGAL objects have default constructors is to allow their use in standard containers, like `std::vector` (at least for C++<11, the default constructor is mandatory, and even in C++>=11, for several operations).

However, the CGAL objects are not initialized on purpose. A default constructed geometrical object has no geometrical meaning. If we chose to zero-initialize the objects, for most of the object types, that would create singular values (for example, a `CGAL::Segment_2` initialized by two zero-initialized points is singular).

@freud14 The objects of the STL are not all initialized either. STL Containers are initialized, because there is an obvious semantic. But even `std::array` is a good example: its data members are not initialized.

Note also that the non-initialization can be something that the compiler, a static code analyzer, or debugging tools like valgrind or AddressSanitizer, can detect, and that is a useful information. If we would have chosen to value-initialize all the data members of CGAL objects, in their default-constructor, then those debugging tools would no longer be usable.

So I close this issue as a "not-a-bug".

**Comment by freud14** [comment]
Ok. I see. Fair enough. Thank you.
